import { ENTRANCE_GATE_X, ENTRANCE_GATE_Z, ENTRANCE_PLAYER_X, ENTRANCE_PLAYER_Z, ENTRANCE_GATE_HALF_WIDTH } from '../../src/world/entrance/layout.ts';
console.log({ ENTRANCE_GATE_X, ENTRANCE_GATE_Z, ENTRANCE_PLAYER_X, ENTRANCE_PLAYER_Z, ENTRANCE_GATE_HALF_WIDTH });
