import { HALL_DECK } from './layout';
import { BoxGeometry, Group, Mesh, type Object3D } from 'three';
import { PALETTE } from '../../art/style/bridge';
import { addOutline, softMaterial, solid } from '../../art/style/materials';
import { INTERIOR_HALF_X, INTERIOR_HALF_Z, PARADE_MEMBER_RADIUS } from '../../core/constants';
import { createPetBowl } from '../../art/models/hotelAssets';
import {
  CASTLE_BENCH_HALF_LENGTH,
  CASTLE_BENCH_HALF_WIDTH,
  CASTLE_BENCH_SEAT,
  CASTLE_DAIS_HEIGHT,
  CASTLE_PLINTH_TOP,
  CASTLE_TABLE_HALF_LENGTH,
  CASTLE_TABLE_HALF_WIDTH,
  CASTLE_TABLE_TOP,
  CASTLE_TAPESTRY_RAIL_Y,
  createCastleArmour,
  createCastleArmourPlinth,
  createCastleBench,
  createCastleChest,
  createCastleFeastProp,
  createCastleFeastTable,
  createCastleTapestry,
  createCastleTapestryRail,
  createCastleThrone,
  type FeastProp,
} from '../../art/models/castleAssets';
import { castleFloorMaterial } from './castleFabric';

import { CASTLE_HEARTH, castleTorchAnchors, type WallAnchor } from './castleLighting';

/**
 * **The great hall's furniture** — batch 1 of the castle's authored geometry
 * (PR #368), placed.
 *
 * The assets landed as bytes and were wired into nothing: `castle.glb` existed,
 * regenerated byte-identically, and no player could see a single one of them.
 * This file is the other half.
 *
 * ## Where the hall is, and why it is one constant
 *
 * Issue #380 gives the castle three floors with jobs — ground is the mall,
 * **middle is the great hall**, roof is a garden. **That split has now landed**
 * (#377/#380), so the hall has moved off the ground floor and onto the middle
 * one, which is a floor of its own with nothing else on it.
 *
 * It was on deck 0 because that was the deck that already had a hall's
 * *fabric*: `castleDecor.ts` put the hearth, the coat of arms and the
 * portcullis behind `if (deck === 0)`, and a throne on a different storey from
 * the only fireplace in the castle would have read as two half-rooms rather
 * than one whole one. The note here promised that moving the hall would be
 * changing {@link CASTLE_GREAT_HALL_DECK}, and that `castleDecor.ts`'s own
 * block would move with it so the two could not be separated. **Both happened,
 * and it was one line each** — which is the whole argument for having written
 * the constant down rather than typing `0` in four places.
 *
 * ## The layout is derived from the wall, not typed against it
 *
 * Every X in this file comes out of {@link castleTorchAnchors} — the same list
 * the torches and the banners are placed from. A tapestry hangs on a **midpoint
 * between two torches**, and the throne stands centred on *its* tapestry, and
 * the feast table runs down the hall on the throne's own axis. So there is one
 * number, the anchor spacing, and everything inherits from it.
 *
 * That is not tidiness. The 3D Artist lost most of a day to a hall render in
 * which every sconce was **inside a tapestry** — tapestries centred on ±2.6 and
 * 3.2 m wide, sconces at ±1.2, so the pictures the sconce's size was being
 * judged from were not showing a sconce at all. Two independently-typed lists
 * of wall positions is exactly how that happens, and it cannot happen to
 * coordinates that are computed from the other list.
 *
 * ## No colliders, and that is not an oversight
 *
 * Indoor collision is height-blind — `registerInteriorCollision` walls the shell
 * once and it holds on every storey — so a collider under the throne on deck 0
 * would be an invisible pillar in the middle of floor 3. Nothing here registers
 * one. **Placement is the whole of the protection**, and `check:castle`'s prop
 * assertions are what enforce it.
 *
 * Issue #377's floor split removes that constraint by construction. What wants a
 * collider afterwards is written down in `HANDOFF-castle-great-hall.md` rather
 * than left to be rediscovered, and the interesting part is that **the bench,
 * the throne seat, the dais and the table top must not get a blocking one**: a
 * child is *meant* to climb onto all four, and a blocking body on a bench turns
 * the one object in the room built to be sat on into a wall. They take a
 * jump-on plate, the way `hotel/place.ts` already places props.
 */

/**
 * Which storey is the great hall.
 *
 * See this file's header: #380 moves it to the middle floor, and this is the
 * line that moves. It is deliberately the same value as `castleDecor.ts`'s hall
 * block so the throne and the fireplace cannot end up on different floors.
 */
export const CASTLE_GREAT_HALL_DECK = HALL_DECK;

/** Everything this file adds to a storey, so the check can find it. */
export function castleFurnitureGroupName(deck: number): string {
  return `castle-furniture-${deck}`;
}

/**
 * How wide a tapestry's cloth is, in metres — the Artist's A3 figure.
 *
 * Used only to keep other wall furniture out of the cloth's own band (see
 * {@link greatHallTapestries}), never to build anything, so it is an
 * *allowance* rather than a shared dimension: over-stating it costs a banner
 * moved along one bay, under-stating it costs a banner behind a tapestry.
 */
const TAPESTRY_WIDTH = 3.2;

/**
 * How much clear wall a tapestry claims either side of its own cloth.
 *
 * A banner hung 10 cm off the edge of a tapestry is not *behind* it but still
 * reads as a mistake, so the band is the cloth plus a hand's width.
 */
const TAPESTRY_MARGIN = 0.5;

/**
 * The three bays of the great hall's end wall, as wall anchors.
 *
 * **Midpoints between consecutive torches**, so a tapestry never lands on a
 * sconce — the fault described in this file's header — and consecutive, so the
 * three read as one composition behind the throne rather than as three
 * hangings scattered along a wall.
 *
 * Exported because `castleDecor.ts`'s banner run has to ask which bays are
 * taken. Two lists of wall positions kept in step by hand is the whole problem;
 * one list with an owner is the fix.
 */
export function greatHallTapestries(deck: number): readonly WallAnchor[] {
  if (deck !== CASTLE_GREAT_HALL_DECK) return [];

  // The end wall of the hall: the north wall (most negative Z), east half.
  // Anchors carry their own outward normal, so "which wall" is a property of
  // the anchor and never a sign this file has to get right.
  const northEast = castleTorchAnchors(deck)
    .filter((anchor) => anchor.out.z > 0.5 && anchor.x > 0)
    .sort((a, b) => a.x - b.x);
  if (northEast.length < 4) return [];

  const bays: WallAnchor[] = [];
  for (let i = 0; i + 1 < northEast.length && bays.length < 3; i += 1) {
    const left = northEast[i] as WallAnchor;
    const right = northEast[i + 1] as WallAnchor;
    // A bay only takes a 3.2 m cloth if the two torches are far enough apart to
    // leave it clear of both. Measured, so a change to the torch spacing moves
    // the tapestries or drops them rather than hanging one over a flame.
    if (right.x - left.x < TAPESTRY_WIDTH + TAPESTRY_MARGIN) continue;
    bays.push({ x: (left.x + right.x) / 2, z: left.z, yaw: left.yaw, out: left.out });
  }
  return bays;
}

/**
 * Is this point on a wall inside a bay a tapestry has claimed?
 *
 * `castleDecor.ts`'s banner run asks this so a banner is never hung behind a
 * tapestry. It is a question about *distance along the wall*, which on the
 * north wall is X.
 */
export function isTapestryBay(deck: number, x: number, z: number): boolean {
  const half = TAPESTRY_WIDTH / 2 + TAPESTRY_MARGIN;
  return greatHallTapestries(deck).some(
    (bay) => Math.abs(bay.x - x) < half && Math.abs(bay.z - z) < 1,
  );
}

/** The dais the throne stands on: broad enough to step onto from any side. */
const DAIS_HALF_X = 1.6;
const DAIS_HALF_Z = 1.2;

/**
 * Half the feast table's own length — **measured off the asset**, not typed.
 *
 * It stood here as `const TABLE_HALF_LENGTH = 3` with the comment "authored
 * size; it does not scale". Both halves of that were true and it was still a
 * second copy of a figure the asset already knows, which stopped being harmless
 * the moment #413 started *repeating* the table: the run's pitch is this
 * number, so a table that grew by a centimetre would open a centimetre gap
 * between every pair, and nothing would say so.
 */
const TABLE_HALF_LENGTH = CASTLE_TABLE_HALF_LENGTH;
/**
 * Clear floor between the dais and the table — the approach itself.
 *
 * A child's collision diameter is 1.24 m, so this is "two can pass abreast",
 * which is the least a hall's approach can be and still be one.
 */
const FEAST_APPROACH = 1.5;

/**
 * How far down the hall the feast table's centre sits from the throne.
 *
 * The table is 6 m long and the throne's dais is 2.4 m deep, so this leaves a
 * clear approach between the two — the space a child walks up to reach the
 * throne, which is the whole point of putting a throne at the end of a hall.
 *
 * ## Shortened from 10 m for #403, and this one is a judgement call
 *
 * Halving the plate's *area* left the ground floor 31.11 m deep instead of 44,
 * and the shafts that cross its middle did not shrink: the helter-skelter's
 * tube now reaches within 7.93 m of the north wall. At 10 m the feast's
 * benches stood at 15.75 m from that wall — past every shaft's north edge —
 * and `feastIsClearOfShafts` rejected **all three** bays, so `dressGreatHall`
 * returned early and built no hall at all. `check:castle`'s contract
 * assertion is what said so, out loud, rather than a hall quietly vanishing.
 *
 * Nothing here was made smaller to fix it: the throne, the dais, the table and
 * the benches are all the sizes the Artist authored. What closed is the *gap*
 * between the dais and the table, which is the same thing the shop run did and
 * is the density Jim asked for. 5.7 m is the shortest that still keeps a real
 * approach: the dais reaches 1.2 m from the throne, the table reaches 3 m back
 * towards it, leaving **1.5 m of clear floor** to walk up — a child is 1.24 m
 * across, so two can still pass. Any less and the table is on the dais.
 *
 * If #377 removes the helter-skelter, the constraint that forced this goes
 * with it and the hall can lengthen again. Do not lower this further to fit
 * something new in; move the something instead.
 */
const TABLE_FROM_THRONE = DAIS_HALF_Z + TABLE_HALF_LENGTH + FEAST_APPROACH;

/** How far the benches sit from the table's own axis. */
const BENCH_OFFSET = 1.85;

/**
 * The bench's own half-extents, and how far along the table each pair sits.
 *
 * Named rather than inlined because {@link feastIsClearOfShafts} has to predict
 * the footprint {@link feast} will build, and two copies of that arithmetic is
 * the bug this whole file's header is about.
 */
const BENCH_ALONG = 1.55;

/**
 * **How many feast tables stand end to end in one run — counted off the room,
 * not typed** (#413, #449).
 *
 * They are copies of the **same** asset butted together rather than one longer
 * table: #413's own instruction ("extend or repeat the one that exists; do not
 * author a second"), and the cheaper thing besides — an 18 m table authored in
 * Blender is a new node, a new style entry, a new `check:castle` contract
 * figure and a new thing that can disagree with {@link CASTLE_TABLE_TOP}. They
 * butt exactly, because the pitch is the asset's own measured length.
 *
 * Jim, on #453: *"have as many tables as is needed to fill the space."* So the
 * count is no longer a number somebody chose — the run grows south, table by
 * table, until the last bench's own end would come within
 * {@link FEAST_SOUTH_MARGIN} of the south wall. Change the plate's depth and
 * the run lengthens or shortens on its own; that is precisely what a hard 2 or
 * 3 could not do, and what went stale the moment the hall changed size.
 */
export function feastTableCount(plan: GreatHallPlan): number {
  // The first table is fixed: {@link FEAST_APPROACH} clear of the dais.
  const first = plan.wallZ + plan.inward * (THRONE_FROM_WALL + TABLE_FROM_THRONE);
  let count = 0;
  for (;;) {
    const centre = first + plan.inward * count * TABLE_HALF_LENGTH * 2;
    // The southernmost thing a table brings with it is the far end of its
    // outer bench, not the table top — so that is what is measured against the
    // wall, and it is measured off the bench asset rather than guessed.
    const reach = Math.abs(centre + plan.inward * (BENCH_ALONG + BENCH_HALF_LENGTH));
    if (reach > INTERIOR_HALF_Z - FEAST_SOUTH_MARGIN) return count;
    count += 1;
  }
}

/**
 * Clear floor left between the last bench and the south wall, in metres.
 *
 * A child is 1.24 m across, so this is "she can walk round the end of the
 * banquet without brushing the wall", twice over. Any less and the run reaches
 * a wall it has to be squeezed past; any more and the room starts looking
 * half-used again, which is the thing #453 is about.
 */
const FEAST_SOUTH_MARGIN = 3;

/** Half a bench's own length, measured off the asset. */
const BENCH_HALF_LENGTH = CASTLE_BENCH_HALF_LENGTH;

/**
 * **The hall fills with tables, and the count comes off the room** — Jim, on
 * #453.
 *
 * > *"the tables don't compose nicely into the space, they're kind of shoved
 * > into one end of a mostly empty room … have as many tables as is needed to
 * > fill the space."*
 *
 * He was right twice over, and the second half was not really about tables.
 * Two invisible discs in `keepOutsFor` — the roundel's and the front door's —
 * claimed the middle and the south of a storey that has neither a roundel nor
 * a door, and the banquet had been squeezed into what was left. Those are gone
 * (see `dressing.ts`), and with the floor back the runs simply march across it.
 *
 * ## The throne stands at the head of the first run, not at the end of an aisle
 *
 * The east-most run is **on the hall's own axis**, so the throne looks straight
 * down a table: the high table of a great hall, which is what a throne at the
 * head of a room has always meant. The version this replaces put an aisle on
 * that axis with a run either side, which was a good composition for exactly
 * two tables and cannot survive more of them — a grid of runs either side of a
 * centred aisle has to grow east as fast as it grows west, and east is the lift
 * lobby, the one disc on this storey that is really there.
 *
 * Putting a run on the axis instead means the grid only ever grows **west**,
 * into the open half of the hall, and the east-most run's benches sit 6.4 m
 * clear of the lift lobby whatever else changes.
 */

/**
 * Clear floor between one run's benches and the next run's, in metres.
 *
 * A child is 1.24 m across, so 2.6 m is two of her abreast: this is the aisle
 * she walks up between two tables of children, and it is what stops a hall of
 * five runs reading as one enormous slab of furniture.
 */
const FEAST_AISLE = 2.6;

/**
 * Middle to middle of two neighbouring runs — the aisle plus what a run itself
 * claims either side of its own axis.
 *
 * Derived rather than typed, so widening a bench or moving it out from the
 * table moves every run in the hall together and cannot leave two of them
 * overlapping.
 */
const FEAST_ROW_PITCH = 2 * (BENCH_OFFSET + CASTLE_BENCH_HALF_WIDTH) + FEAST_AISLE;

/**
 * Clear floor left between the west-most run's benches and the west wall.
 *
 * Two metres: enough to walk down the outside of the banquet, which is how a
 * child reaches the far tables at all, and not so much that the hall goes back
 * to having an empty half. It is what decides the number of runs, so it is the
 * one number to move if the hall ever wants one fewer.
 */
const FEAST_WALL_MARGIN = 2;

/**
 * **Every run's axis, east to west** — the east-most on the hall's own axis
 * with the throne at its head, then one every {@link FEAST_ROW_PITCH} until the
 * next would come within {@link FEAST_WALL_MARGIN} of the west wall.
 *
 * East to west and not the other way round, because index 0 is the run the
 * blank places and the pets' table belong to (see {@link FREE_PLACE_ROW}), and
 * that wants to be the run nearest the lift she arrives by rather than the one
 * furthest from it.
 */
function feastRowAxes(plan: GreatHallPlan): number[] {
  const axes: number[] = [];
  for (;;) {
    const axis = plan.axisX - axes.length * FEAST_ROW_PITCH;
    // A run reaches this far west of its own axis: the outer bench, plus the
    // plank's half-width. Measured off the assets, never typed.
    const reach = axis - BENCH_OFFSET - CASTLE_BENCH_HALF_WIDTH;
    if (reach < -INTERIOR_HALF_X + FEAST_WALL_MARGIN) return axes;
    axes.push(axis);
  }
}

/**
 * How far along a bench the two diners sitting on it are placed, either side of
 * its middle.
 *
 * Two per bench. Three would fit at a pinch and would read as a queue rather
 * than as a table people chose to sit at.
 *
 * **0.75 rather than 0.70, chosen off a screenshot.** At 0.70 the run's spacing
 * alternates 1.40 m within a bench and 1.70 m between benches, and a child's
 * *hair* is 1.53 m across even though her head is 1.36 — so the pairs sat with
 * their hair merged and a visible gap between pairs, which reads as six clumps
 * rather than as one full table. 0.75 makes it 1.50 and 1.60, near enough even
 * that the eye stops seeing pairs.
 *
 * It does not go further. The children would stop overlapping entirely at about
 * 0.90, and the table would then look half empty — which is the opposite of
 * what #413 asked for. Children at a feast sitting shoulder to shoulder is the
 * brief.
 */
const DINER_ALONG = 0.75;

/**
 * **Where the hall is laid out**, resolved once — its axis, its end wall, and
 * which way is into the room.
 *
 * Extracted from {@link dressGreatHall} because the banquet's diners
 * (`greatHallBanquet.ts`) sit on benches this file places, and they must be
 * placed from the **same** arithmetic rather than from a second copy of it. A
 * diner list derived independently is precisely the "two definitions of one
 * thing, kept in step by hand" that CLAUDE.md opens on, and it would fail in
 * the least visible way available: two dozen children floating beside a bench
 * that had moved a metre.
 */
export interface GreatHallPlan {
  /** The hall's long axis, in interior-local metres. */
  readonly axisX: number;
  /** The end wall the throne stands against. */
  readonly wallZ: number;
  /** +1 or -1: into the room, away from that wall. */
  readonly inward: number;
  /** The three tapestry bays behind the throne. */
  readonly bays: readonly WallAnchor[];
}

/** See {@link GreatHallPlan}. `null` on a storey that is not the great hall. */
export function greatHallPlan(deck: number): GreatHallPlan | null {
  if (deck !== CASTLE_GREAT_HALL_DECK) return null;
  const bays = greatHallTapestries(deck);
  if (bays.length < 3) return null;
  const centre = hallAxis(bays);
  if (!centre) return null;
  return { axisX: centre.x, wallZ: centre.z, inward: centre.out.z, bays };
}

/** The middle of each table in the run, nearest the throne first. */
function feastTableCentres(plan: GreatHallPlan): number[] {
  const first = plan.wallZ + plan.inward * (THRONE_FROM_WALL + TABLE_FROM_THRONE);
  return Array.from(
    { length: feastTableCount(plan) },
    (_, i) => first + plan.inward * i * TABLE_HALF_LENGTH * 2,
  );
}

/** One bench in the run: where its middle is, and which side of its table. */
interface BenchPlacement {
  readonly x: number;
  readonly z: number;
  /** -1 west of its own run's axis, +1 east. */
  readonly side: number;
  /**
   * Which run this bench belongs to, 0 west and 1 east.
   *
   * Carried rather than recovered from `x`. {@link greatHallSeats} counts the
   * free places along each run's own bench line, and recovering the run by
   * undoing `x ± BENCH_OFFSET` in floating point does not give back the same
   * number on both sides of a table — which silently put the count out of step
   * halfway down a run and left five free places where six were intended.
   */
  readonly row: number;
}

/**
 * Every bench at the banquet, in placement order: west run first, and within a
 * run, table by table down the hall.
 *
 * The order is load-bearing rather than incidental — {@link greatHallSeats}
 * counts along it to decide which places are left free, and
 * `greatHallBanquet.ts` seats children off the list it returns. One list, one
 * order, one owner.
 */
function feastBenches(plan: GreatHallPlan): BenchPlacement[] {
  const benches: BenchPlacement[] = [];
  feastRowAxes(plan).forEach((rowX, row) => {
    for (const tableZ of feastTableCentres(plan)) {
      for (const side of [-1, 1]) {
        for (const along of [-BENCH_ALONG, BENCH_ALONG]) {
          benches.push({ x: rowX + side * BENCH_OFFSET, z: tableZ + along, side, row });
        }
      }
    }
  });
  return benches;
}

/**
 * **Where a child sits at the banquet, and which way she faces.**
 *
 * `greatHallBanquet.ts` is the only caller. It is here rather than there
 * because a seat is a fact about a bench, and the benches are placed here.
 *
 * ## Why `x` is the plank's *inner face* and not the plank's middle
 *
 * The kid rig has no knee, so a seated child's legs can only hang vertically —
 * any rotation about the hip lifts her foot by `0.36·(1 − cos θ)`. Her hip
 * pivot is at `KID_HIP_HEIGHT`, so hips on a {@link CASTLE_BENCH_SEAT} plank
 * and feet on the floor is not one pose among several: it is the only one, and
 * it is the entire reason the Artist cut the bench to 0.360 m.
 *
 * But her torso reaches **0.18 m below her own hip pivot**. A child placed on
 * the middle of the plank therefore has 0.18 m of herself inside it. Placing
 * her on the plank's inner face puts that 0.18 m *behind* her instead, where
 * her own body hides it from a camera on the table's side — and it is the only
 * placement that does, because the gap between the table's edge and the
 * plank's inner face is 0.45 m and her hem is 0.80 m across. She does not fit
 * in front of the bench; she has to be half on it.
 *
 * The clearance that leaves in front of her is 5.2 cm against the table's edge,
 * which is thin enough that it is asserted rather than trusted — see
 * `check:castle`'s banquet assertion.
 */
export interface GreatHallSeat {
  readonly x: number;
  readonly z: number;
  /** Turns a +Z-facing child to look across the table. */
  readonly yaw: number;
  /**
   * **Nobody is sitting here** — one of #449's blank spaces, kept clear for
   * the player. See {@link FREE_PLACE_STRIDE}.
   *
   * A property of the seat rather than a second list of coordinates, because
   * the two questions a free place is asked — "seat no child here" and "offer
   * a Sit chip here" — must never be able to disagree about which seat they
   * mean. `greatHallBanquet.ts` skips these; {@link greatHallFreePlaces}
   * hands the same ones to `Building`'s interact zones.
   */
  readonly free: boolean;
  /** Where a child stands to sit down here. See {@link greatHallFreePlaces}. */
  readonly standX: number;
  readonly standZ: number;
}

/**
 * **How many places are left blank, and where along the run they are** — #449's
 * "a few spaces".
 *
 * Jim: *"no free spaces for the player to sit."* The fix is not one gap at the
 * end of a table, which reads as the table having run out of children; it is
 * gaps **among** the diners, which read as places laid for somebody who has not
 * sat down yet.
 *
 * Three of them, every other place, at the **south end** of the run — which is
 * where the pets' table stands and where she walks in from the lift. That
 * clustering is not tidiness: a run is 18 m long, there is one pets' table, and
 * #449's fourth ask is that she *watches* her cat go and eat. Free places
 * spread evenly down the whole run measured 12 m from the nearest bowl, and on
 * screen that is the animal walking out of the bottom of the frame — the first
 * version of this, built and thrown away. `check:castle`'s places assertion
 * fails on it now.
 *
 * It has a second virtue: three gaps together are something a six-year-old
 * finds while scanning a hall of a hundred children, where one here and one
 * fifteen metres away are not.
 */
const FREE_PLACE_COUNT = 3;

/** Every other place, so no two blanks are adjacent and read as a missing pair. */
const FREE_PLACE_STRIDE = 2;

/**
 * Which side of a run's table the free places are on: the **camera-facing**
 * one.
 *
 * The camera is fixed isometric and always shows an object's +X/+Z faces, so a
 * child sitting west of a table (`side < 0`) looks east, into the camera, and
 * one sitting east of it shows her back. Both are true of the diners either
 * way — a banquet has two sides and children sit on both of them — but **the
 * player only ever sits in a free place**, and a six-year-old watching herself
 * from behind for the length of a meal is the fault #447 files against the
 * market's south row. So every free place is on the side she will be seen from
 * the front at.
 */
const FREE_PLACE_SIDE = -1;

/**
 * **Which run the blank places are on: the first, the one on the hall's own
 * axis with the throne at its head.**
 *
 * The run nearest the lift she arrives by, so the blank places and the pets'
 * table are the first things she reaches rather than something across the
 * width of a hall of five tables. {@link greatHallPetTable} reads the same
 * index, so the two cannot come to mean different runs.
 */
const FREE_PLACE_ROW = 0;

/**
 * How far back from her seat a child stands to sit down in it, in metres.
 *
 * She has to arrive somewhere the bench is not: her seat is on the plank's
 * inner face, so a stand spot a chair's depth behind it would be inside the
 * plank. This is measured from the seat out past the plank's far edge —
 * `CASTLE_BENCH_HALF_WIDTH × 2` of bench plus room to stand — rather than
 * typed, so a wider bench moves the spot with it.
 *
 * Castle props carry no colliders, so nothing would *stop* her standing in the
 * bench; it would simply look like she was standing in the bench.
 */
const SIT_STAND_BACK = CASTLE_BENCH_HALF_WIDTH * 2 + 0.85;

/**
 * How close a tap has to land to a blank place to mean *that* place, in metres.
 *
 * The hotel breakfast chair's own figure. It lives here rather than in
 * `interactZones.ts` because {@link SIT_STAND_BACK} has to stay inside it —
 * a stand spot further from its seat than the pick radius is a chip that comes
 * into view and can never be pressed, which is what the hotel's window zones
 * were found doing — and a check can only assert that if both numbers have one
 * home.
 */
export const SIT_PICK_RADIUS = 1.6;

/** Every seat at the banquet, taken and free alike. See {@link GreatHallSeat}. */
export function greatHallSeats(deck: number): readonly GreatHallSeat[] {
  const plan = greatHallPlan(deck);
  if (!plan) return [];

  /** Every seat, and where along {@link FREE_PLACE_ROW}'s blank-side bench line
   *  it falls — `-1` for a seat that is not on that line at all. */
  const seats: { seat: GreatHallSeat; along: number }[] = [];
  let alongLine = 0;

  for (const bench of feastBenches(plan)) {
    // The plank's inner face: its middle, pulled back towards the table by half
    // its own measured width. Never a typed 0.30.
    const x = bench.x - bench.side * CASTLE_BENCH_HALF_WIDTH;
    // A child faces +Z, so a quarter turn one way or the other looks across the
    // table. West of the axis she looks east.
    const yaw = bench.side < 0 ? Math.PI / 2 : -Math.PI / 2;
    const onFreeLine = bench.side === FREE_PLACE_SIDE && bench.row === FREE_PLACE_ROW;
    for (const along of [-DINER_ALONG, DINER_ALONG]) {
      seats.push({
        seat: {
          x,
          z: bench.z + along,
          yaw,
          free: false,
          // Straight back out from the table, which is the way she walked in.
          standX: x + bench.side * SIT_STAND_BACK,
          standZ: bench.z + along,
        },
        along: onFreeLine ? alongLine : -1,
      });
      if (onFreeLine) alongLine += 1;
    }
  }

  // **The blank places, counted back from the south end of that line.**
  // Counted from the end rather than from the start because the end is the
  // fixed one: the run grows southwards as the hall gets deeper
  // ({@link feastTableCount}), so a count from the north would slide the gaps
  // — and the pets' table — a table's length every time the room changed size.
  const last = alongLine - 1;
  const free = new Set<number>();
  for (let i = 0; i < FREE_PLACE_COUNT; i += 1) {
    const at = last - i * FREE_PLACE_STRIDE;
    if (at >= 0) free.add(at);
  }

  return seats.map(({ seat, along }) =>
    free.has(along) ? { ...seat, free: true } : seat,
  );
}

/**
 * The blank places, for whoever offers the Sit chip.
 *
 * A filter over {@link greatHallSeats} rather than a second derivation, so
 * "which seats are free" has exactly one answer in this game.
 */
export function greatHallFreePlaces(deck: number): readonly GreatHallSeat[] {
  return greatHallSeats(deck).filter((seat) => seat.free);
}

/**
 * **The gap a diner has to fit in**: clear floor between the bench plank's
 * inner face — where she sits — and the table's edge, in metres. 0.45 m.
 *
 * Derived from the two measured half-widths rather than read off the built
 * scene, so `check:castle` can compare a *prediction* against what was built
 * instead of restating it. A child's hem is 0.80 m across, which is what makes
 * this a fit rather than a placement: see {@link GreatHallSeat}.
 */
export const DINER_TABLE_GAP = BENCH_OFFSET - CASTLE_BENCH_HALF_WIDTH - CASTLE_TABLE_HALF_WIDTH;

/**
 * How far in front of a blank place its lone goblet stands, in metres.
 *
 * Past {@link DINER_TABLE_GAP} — so it is on the table rather than balanced on
 * its edge — and past `Building`'s own `FEAST_DISH_REACH` of 0.5 m, so the dish
 * she chooses when she sits down lands beside it and never inside it.
 */
const FREE_PLACE_GOBLET_REACH = 0.62;

// ------------------------------------------------------- the pets' table

/**
 * **A small table for the pets, alongside the banquet** — #449's fourth ask,
 * and the one that makes the hall a scene rather than furniture.
 *
 * Jim: *"There should also be a small pets table for the pets to eat at, and
 * they go there when the player sits."* A child who brings her cat to dinner
 * sees it leave her side and settle at its own little table.
 *
 * ## The numbers, and what each is for
 *
 * The top is at {@link GREAT_HALL_PET_TABLE_TOP}, roughly a third of the feast
 * tables' 0.675 m. That is not "small" for its own sake: the pets are between
 * 0.3 and 0.6 m tall, and a bowl on a 0.675 m table would be over every one of
 * their heads. At 0.30 m a bunny's nose reaches its own bowl, which is the
 * whole read.
 *
 * It is 2.4 m long, which is *large* for four small animals and deliberately
 * so — a table the size of the bowls on it disappears at this camera, and this
 * one has to be recognisable as a table from across the hall or the moment it
 * exists for does not land.
 *
 * **Its long axis runs down the hall, like the feast tables' own**, so it reads
 * as a little one alongside the big ones rather than as a bench pushed across
 * the end of them — and so its animals can line up facing the same way as the
 * children.
 */
const PET_TABLE_HALF_X = 0.45;
const PET_TABLE_HALF_Z = 1.2;
/** The plank's thickness, and therefore where the legs stop. */
const PET_TABLE_PLANK = 0.09;

/** The pets' table's own top surface, in metres. See {@link petTable}. */
export const GREAT_HALL_PET_TABLE_TOP = 0.3;

/**
 * Where the pets' table stands relative to {@link FREE_PLACE_ROW}'s run: a
 * little west of its axis, and south of the last bench on it.
 *
 * **In the clear band at the south end of the hall**, which is floor the
 * banquet deliberately leaves ({@link FEAST_SOUTH_MARGIN}) rather than floor
 * borrowed from it — so the animals eat beside the feast rather than among the
 * children's legs, and nothing has to be moved to make room for them.
 *
 * ## It has to be in shot from her seat, and that is the requirement that is
 * easy to miss
 *
 * The point of #449 is that she *watches* her cat leave her side and go and
 * eat, so a pets' table she cannot see while sitting down would satisfy the
 * ticket's words and none of its purpose. Two placements were built and thrown
 * away for this — at the mouth of an aisle it was 12 m from the nearest blank
 * place, and beside a run it was 12 m from the blank places on the *other* run.
 * Both were measured in the running game, not reasoned about: the animal was
 * where it should be and the moment was not there. The blank places now cluster
 * at the south end of one run ({@link FREE_PLACE_COUNT}) and this stands beside
 * them, which puts the farthest of them a few strides apart.
 *
 * The westward nudge keeps the table out of the walking lane straight off the
 * end of the run, and puts the animals between her seat and the camera rather
 * than directly behind her.
 */
const PET_TABLE_WEST_OF_ROW = 2.0;

/**
 * How far south of the last bench's own end the pets' table's middle sits.
 *
 * Its own half-length plus room for the animals standing at its north end, so
 * nothing at the pets' table is ever inside the last bench of the banquet —
 * and no more than that, because every centimetre further south is a
 * centimetre further from the blank place at the *far* end of the run. At 2.2
 * the worst of the three measured 8.4 m and `check:castle` failed it; the
 * clearance is what it has to be and not a round number.
 */
const PET_TABLE_SOUTH_OF_FEAST = 1.2;

/**
 * How far out from the table's edge a pet stands, and how far in its bowl sits.
 *
 * The stand-off is a pet's own body plus a little: {@link PARADE_MEMBER_RADIUS}
 * is what the parade spaces the line with, so a pet standing this far out has
 * its nose at the table rather than its shoulders through it.
 *
 * **0.25 rather than 0.45, off a screenshot.** These are small animals —
 * `PARADE_MEMBER_RADIUS` is 0.22 m — and at 0.45 the extra hand's width read
 * as a pet standing *near* its table rather than *at* it. There is no lower
 * useful figure either: at 0 the body is against the plank and the head goes
 * through it.
 */
const PET_STAND_OFF = PARADE_MEMBER_RADIUS + 0.25;
const PET_BOWL_INSET = 0.17;

/**
 * **Where each pet stands, and which way it turns**, in the hall's own local
 * metres — the one owner of the pets' seating plan.
 *
 * `Building` maps these into world coordinates and hands them to the parade;
 * {@link petTable} lays a bowl at each of them. One list, so a bowl cannot end
 * up in front of nobody or a pet in front of no bowl.
 *
 * ## All of them on the far side, and that is the camera talking
 *
 * The camera is fixed isometric and always shows an object's +X/+Z faces. A
 * pet on the near (east or south) side of the table would face away into it
 * and show the camera its tail; on the west edge it faces +X, and at the north
 * end +Z, so every animal at this table is looked at from the front. It is the
 * same rule the free places at the feast are chosen by — and, pleasingly, it
 * turns them the same way as the children, so a row of pets reads as a smaller
 * echo of the row of diners rather than as a separate arrangement.
 *
 * Four places: three down the long west edge at 0.8 m — comfortably more than
 * a companion's own {@link PARADE_MEMBER_RADIUS} — and one at the north end,
 * which stops three-in-a-row reading as a queue. A child with more than four
 * companions keeps the rest in the line beside her, which is a perfectly good
 * thing for them to be doing.
 */
export interface PetPlace {
  readonly x: number;
  readonly z: number;
  /** Which way it turns to face its bowl. A pet's model faces +Z at yaw 0. */
  readonly facing: number;
}

/** Where the pets' table stands on `deck`, or `null` on any other storey. */
export function greatHallPetTable(deck: number): { readonly x: number; readonly z: number } | null {
  const plan = greatHallPlan(deck);
  if (!plan) return null;
  const centres = feastTableCentres(plan);
  const last = centres[centres.length - 1];
  const row = feastRowAxes(plan)[FREE_PLACE_ROW];
  if (last === undefined || row === undefined) return null;
  return {
    x: row - PET_TABLE_WEST_OF_ROW,
    // Clear of the last bench's own far end, which is the southernmost thing
    // the banquet puts on the floor — measured off the assets, never guessed.
    z:
      last +
      plan.inward *
        (BENCH_ALONG + CASTLE_BENCH_HALF_LENGTH + PET_TABLE_HALF_Z + PET_TABLE_SOUTH_OF_FEAST),
  };
}

/** Every place at the pets' table. See {@link PetPlace}. */
export function greatHallPetPlaces(deck: number): readonly PetPlace[] {
  const table = greatHallPetTable(deck);
  if (!table) return [];
  const places: PetPlace[] = [];
  // Down the west edge, facing east across the table: +X, into the camera, and
  // the same way the children at the feast are facing.
  for (const along of [-0.8, 0, 0.8]) {
    places.push({
      x: table.x - PET_TABLE_HALF_X - PET_STAND_OFF,
      z: table.z + along,
      facing: Math.PI / 2,
    });
  }
  // And one at the north end, facing down the table: +Z, into the camera too.
  places.push({ x: table.x, z: table.z - PET_TABLE_HALF_Z - PET_STAND_OFF, facing: 0 });
  return places;
}

/**
 * The pets' table itself: a plank on four legs, and a bowl at every place.
 *
 * Built here from boxes rather than authored, for the reason `dais` is: it is
 * a rectangle, and a rectangle is not worth a node in `castle.glb`, a style
 * entry and a contract figure. Its colours are the **feast tables' own** —
 * `woodLight` over `woodDark` — so it reads as a small piece of the same
 * furniture rather than as something from another room.
 *
 * The bowls are `createPetBowl()`, the hotel's. That is one definition of
 * "a bowl a pet eats out of" being used twice, which is the rule this codebase
 * is built on; a second castle-flavoured pet bowl would be a second thing to
 * keep in step and would look, at this camera, exactly the same.
 */
function petTable(x: number, z: number, places: readonly PetPlace[]): Object3D[] {
  const out: Object3D[] = [];

  const top = new BoxGeometry(PET_TABLE_HALF_X * 2, PET_TABLE_PLANK, PET_TABLE_HALF_Z * 2);
  top.translate(0, GREAT_HALL_PET_TABLE_TOP - PET_TABLE_PLANK / 2, 0);
  const plank = solid(new Mesh(top, softMaterial(PALETTE.woodLight, 0.78)));
  plank.name = 'castle-pet-table-top';
  plank.position.set(x, 0, z);
  plank.receiveShadow = true;
  addOutline(plank, 0.018);
  out.push(plank);

  const legHeight = GREAT_HALL_PET_TABLE_TOP - PET_TABLE_PLANK;
  for (const dx of [-1, 1]) {
    for (const dz of [-1, 1]) {
      const geometry = new BoxGeometry(0.12, legHeight, 0.12);
      geometry.translate(0, legHeight / 2, 0);
      const leg = solid(new Mesh(geometry, softMaterial(PALETTE.woodDark, 0.78)));
      leg.name = 'castle-pet-table-leg';
      leg.position.set(x + dx * (PET_TABLE_HALF_X - 0.18), 0, z + dz * (PET_TABLE_HALF_Z - 0.18));
      addOutline(leg, 0.016);
      out.push(leg);
    }
  }

  // One bowl per place, laid on the table's measured top in front of whoever
  // is standing there — never a second list of bowl positions.
  for (const place of places) {
    const bowl = createPetBowl();
    bowl.root.position.set(
      towards(place.x, x, PET_TABLE_HALF_X - PET_BOWL_INSET),
      GREAT_HALL_PET_TABLE_TOP,
      towards(place.z, z, PET_TABLE_HALF_Z - PET_BOWL_INSET),
    );
    out.push(bowl.root);
  }

  return out;
}

/**
 * The point on the table's own edge nearest a place: the place's coordinate,
 * pulled back to at most `limit` from the table's centre.
 *
 * So a bowl lands in front of the animal that has to reach it, whichever side
 * of the table it is standing on, without a per-side table of offsets.
 */
function towards(place: number, centre: number, limit: number): number {
  return centre + Math.max(-limit, Math.min(limit, place - centre));
}

/**
 * Where the throne stands, measured back from the end wall.
 *
 * Far enough off the wall that the **room's** 3.30 m ceiling applies rather
 * than the 3.08 m under the perimeter wall-plate: the throne is 2.75 m on a
 * 0.30 m dais, so it clears 3.30 with 25 cm to spare and would clear 3.08 by
 * only 1 cm. A throne that only fits because of where it happens to stand is a
 * placement rule nobody will remember.
 */
const THRONE_FROM_WALL = 2.8;

/**
 * How far either side of the hall's axis the two suits of armour stand.
 *
 * **East of the whole banquet**, because the banquet now grows west from the
 * hall's axis and there is no floor left on that side to stand a knight in.
 * The east-most run's benches reach 2.15 m from the axis, so a plinth 4.2 m
 * out clears it by 2 m — a stride and a half of walking room between the
 * armour and the end of the top table — and stays well clear of the lift
 * lobby's disc, which `check:castle` measures it against.
 *
 * One either side used to flank the approach. With the throne now at the head
 * of a table rather than at the end of an aisle, the pair stands **both to the
 * east**, one forward of the other, so they still flank the walk up to the
 * dais without one of them standing in the middle of a run.
 */
const ARMOUR_FROM_AXIS = 4.2;

/**
 * Stands the great hall's furniture on `deck`.
 *
 * Called by `castleDecor.ts`'s `dressCastle` so that everything here lands
 * inside `check:castle`'s prop assertions for free — they walk the built group
 * and ask nothing about what a prop *is*.
 */
export function dressGreatHall(deck: number, floor: Group): void {
  const plan = greatHallPlan(deck);
  if (!plan) return;

  const group = new Group();
  group.name = castleFurnitureGroupName(deck);

  const { bays, wallZ, inward, axisX } = plan;

  for (const bay of bays) group.add(...tapestry(bay));

  const throneZ = wallZ + inward * THRONE_FROM_WALL;
  group.add(dais(axisX, throneZ));

  const throne = createCastleThrone();
  throne.root.position.set(axisX, CASTLE_DAIS_HEIGHT, throneZ);
  // The sitter faces +Z; `inward` is +1 on the north wall, so a throne on the
  // north wall looks down the hall at the door with no rotation at all.
  throne.root.rotation.y = inward > 0 ? 0 : Math.PI;
  group.add(throne.root);

  // A guard of honour flanking the approach, rather than two suits of armour
  // pushed into the corners where nobody walks past them.
  //
  // **Outboard of both runs since #449.** They stood at ±5 m, which was clear
  // floor when one table ran down the axis and is inside the west run's bench
  // band now that there are two — 0.25 m apart on the plan, saved only by 1.25 m
  // of Z. `ARMOUR_FROM_AXIS` puts them outside the whole banquet, where they
  // flank the feast rather than growing out of the end of a bench.
  for (const along of [4.3, 8.1]) {
    group.add(...armourOnPlinth(axisX + ARMOUR_FROM_AXIS, wallZ + inward * along, inward));
  }

  group.add(...feast(plan, deck));

  // The pets' table, at the mouth of the aisle (#449). Placed from the same
  // plan as the feast, so it cannot end up in a hall that laid out somewhere
  // else — and from the same `greatHallPetPlaces` the parade is handed, so
  // every bowl has an animal in front of it.
  const pets = greatHallPetTable(deck);
  if (pets) group.add(...petTable(pets.x, pets.z, greatHallPetPlaces(deck)));

  // A bench by the fire, where `castleDecor.ts` has already put the cat and the
  // woodpile. Its Z comes from the hearth's own constant, so it cannot end up
  // warming a fireplace that has moved.
  if (deck === CASTLE_HEARTH.deck) {
    const fireside = createCastleBench();
    fireside.root.position.set(CASTLE_HEARTH.x, 0, CASTLE_HEARTH.z + 2.4);
    // Turned to face the fire — the long axis is +Z, so a quarter turn lays it
    // along the hearth wall.
    fireside.root.rotation.y = Math.PI / 2;
    group.add(fireside.root);
  }

  const chest = createCastleChest();
  chest.root.position.set(axisX + 9.5, 0, wallZ + inward * 3.4);
  chest.root.rotation.y = inward > 0 ? 0 : Math.PI;
  group.add(chest.root);

  floor.add(group);
}

/**
 * Which bay the hall is laid out on — **chosen by testing, not typed.**
 *
 * The middle of the three is preferred, because a throne centred among its
 * tapestries with one either side is the composition a great hall wants.
 *
 * **And it now gets it.** The middle bay used to be rejected: the
 * helter-skelter's tube came down through `HELTER_SHAFT` (x 16.5–23.5) and the
 * middle bay's eastern benches stood at x 16.50–17.10, inside it — a slide
 * growing out of the dinner table, found by looking at a screenshot because
 * `keepOutsFor` guarded the helter's disc on the deck a child got *on* at,
 * not the deck the tube passed through.
 *
 * The version of this function that stood here ended with a prediction:
 * *"when #377 removes the helter-skelter the middle bay becomes usable again
 * and the hall re-centres itself with no edit here. A typed axis would have had
 * to be remembered."* #377 has removed it — along with every other shaft — and
 * that is exactly what happened. The `feastIsClearOfShafts` test it guarded
 * itself with is gone with the shafts it tested against; the preference order
 * it wrapped is all that was ever needed once there is nothing in the way.
 */
function hallAxis(bays: readonly WallAnchor[]): WallAnchor | null {
  // Middle first, then out to the sides — best composition, and now nothing
  // can refuse it.
  const order = [1, 0, 2].filter((i) => i < bays.length);
  for (const index of order) {
    const bay = bays[index];
    if (bay) return bay;
  }
  return null;
}



/** One tapestry: cloth and rail, both hung from {@link CASTLE_TAPESTRY_RAIL_Y}. */
function tapestry(bay: WallAnchor): Object3D[] {
  const cloth = createCastleTapestry();
  cloth.root.position.set(bay.x, CASTLE_TAPESTRY_RAIL_Y, bay.z);
  cloth.root.rotation.y = bay.yaw;

  const rail = createCastleTapestryRail();
  // The same Y, from the same constant, for the same reason §4.4 insists the
  // hang point and the rail centre are one number: a cloth authored to hang
  // from 2.90 on a rail fixed anywhere else shows a strip of daylight along the
  // top of every tapestry in the castle.
  rail.root.position.set(bay.x, CASTLE_TAPESTRY_RAIL_Y, bay.z);
  rail.root.rotation.y = bay.yaw;

  return [cloth.root, rail.root];
}

/**
 * The step the throne stands on — mine to build, per the asset contract, and
 * {@link CASTLE_DAIS_HEIGHT} high.
 *
 * It is a *step*, not a plinth: 0.30 m is below a child's hip, so getting onto
 * the throne is one stride up and then a sit, rather than a climb. That is the
 * same reasoning that puts the throne's own seat at `KID_HIP_HEIGHT`.
 */
function dais(x: number, z: number): Mesh {
  const geometry = new BoxGeometry(DAIS_HALF_X * 2, CASTLE_DAIS_HEIGHT, DAIS_HALF_Z * 2);
  geometry.translate(0, CASTLE_DAIS_HEIGHT / 2, 0);
  const mesh = solid(new Mesh(geometry, castleFloorMaterial(PALETTE.stonePinkDark)));
  mesh.name = 'castle-throne-dais';
  mesh.position.set(x, 0, z);
  mesh.receiveShadow = true;
  addOutline(mesh, 0.02);
  return mesh;
}

/** A suit of armour on its plinth, facing into the room. */
function armourOnPlinth(x: number, z: number, inward: number): Object3D[] {
  const plinth = createCastleArmourPlinth();
  plinth.root.position.set(x, 0, z);

  const armour = createCastleArmour();
  // Stood on the plinth's **measured surface**, not on its dressed height —
  // the dressed figure includes the outline hull and would float the knight
  // 2 cm. See `castleAssets.ts`'s `surfaceTop`.
  armour.root.position.set(x, CASTLE_PLINTH_TOP, z);
  armour.root.rotation.y = inward > 0 ? 0 : Math.PI;

  return [plinth.root, armour.root];
}

/** What is on the table, and in what order down its length. */
const FEAST_SETTING: readonly FeastProp[] = [
  'goblet',
  'loaf',
  'goblet',
  'roast',
  'goblet',
  'pie',
  'goblet',
  'loaf',
];

/**
 * **The banquet**: three tables end to end down the middle of the hall, benches
 * both sides of every one of them, and the meal laid the whole length.
 *
 * This was one 6 m table parked at the throne end. #413 makes it a run — see
 * {@link FEAST_TABLE_COUNT} for why it repeats the asset rather than growing
 * one, and why three.
 *
 * The tables **butt**, because the pitch is `TABLE_HALF_LENGTH * 2` and that is
 * the asset's own measured length: there is no gap to tune and no seam to
 * notice, and there could not be one without the asset changing size.
 */
function feast(plan: GreatHallPlan, deck: number): Object3D[] {
  const out: Object3D[] = [];

  for (const rowX of feastRowAxes(plan)) {
    for (const z of feastTableCentres(plan)) {
      const table = createCastleFeastTable();
      table.root.position.set(rowX, 0, z);
      out.push(table.root);

      // Laid down the middle of the table, on its **measured** top. A goblet
      // standing on a typed 1.05 would have been 37 cm in the air ever since the
      // furniture was cut to a child.
      FEAST_SETTING.forEach((kind, index) => {
        const prop = createCastleFeastProp(kind);
        const along = (index - (FEAST_SETTING.length - 1) / 2) * 0.72;
        // Alternate sides of the centre line so it reads as places laid for people
        // sitting on both benches, not as a row of objects.
        prop.root.position.set(rowX + (index % 2 === 0 ? -0.55 : 0.55), CASTLE_TABLE_TOP, z + along);
        // Turned by its own place at the table rather than by its index within
        // one table's setting, so no two tables are identical rows.
        prop.root.rotation.y = (index + z + rowX) * 1.31;
        out.push(prop.root);
      });
    }
  }

  // **A goblet standing alone in front of every blank place** (#449).
  //
  // The gaps read as gaps from a metre away and as very little from across the
  // hall, where a child first sees the room — the rainbow outline and the Sit
  // chip only arrive once she is near. A place laid with nobody at it is what a
  // laid table says instead: this one is for somebody who has not sat down yet.
  //
  // The castle's own goblet, in the castle's own place setting, pushed out past
  // where her chosen dish lands so the two never share a spot.
  for (const seat of greatHallSeats(deck)) {
    if (!seat.free) continue;
    const goblet = createCastleFeastProp('goblet');
    goblet.root.position.set(
      seat.x + Math.sin(seat.yaw) * FREE_PLACE_GOBLET_REACH,
      CASTLE_TABLE_TOP,
      seat.z + Math.cos(seat.yaw) * FREE_PLACE_GOBLET_REACH,
    );
    out.push(goblet.root);
  }

  // Two benches a side per table rather than one long one: the asset is 2.80 m,
  // and `feastBenches` is the same list `greatHallSeats` seats children from, so
  // a diner cannot end up beside a bench rather than on it.
  for (const { x, z } of feastBenches(plan)) {
    const bench = createCastleBench();
    bench.root.position.set(x, 0, z);
    out.push(bench.root);
  }

  return out;
}

/** Where the bench seat and table top ended up, for anything that asks. */
export const GREAT_HALL_SEAT_HEIGHT = CASTLE_BENCH_SEAT;
export const GREAT_HALL_TABLE_HEIGHT = CASTLE_TABLE_TOP;
