import { HALL_DECK } from './layout';
import { BoxGeometry, Group, Mesh, type Object3D } from 'three';
import { PALETTE } from '../../art/style/bridge';
import { addOutline, solid } from '../../art/style/materials';
import {
  CASTLE_BENCH_HALF_WIDTH,
  CASTLE_BENCH_SEAT,
  CASTLE_DAIS_HEIGHT,
  CASTLE_PLINTH_TOP,
  CASTLE_TABLE_HALF_LENGTH,
  CASTLE_TABLE_HALF_WIDTH,
  CASTLE_TABLE_TOP,
  CASTLE_TAPESTRY_RAIL_Y,
  createCastleArmour,
  createCastleArmourPlinth,
  createCastleBench,
  createCastleChest,
  createCastleFeastProp,
  createCastleFeastTable,
  createCastleTapestry,
  createCastleTapestryRail,
  createCastleThrone,
  type FeastProp,
} from '../../art/models/castleAssets';
import { castleFloorMaterial } from './castleFabric';

import { CASTLE_HEARTH, castleTorchAnchors, type WallAnchor } from './castleLighting';

/**
 * **The great hall's furniture** — batch 1 of the castle's authored geometry
 * (PR #368), placed.
 *
 * The assets landed as bytes and were wired into nothing: `castle.glb` existed,
 * regenerated byte-identically, and no player could see a single one of them.
 * This file is the other half.
 *
 * ## Where the hall is, and why it is one constant
 *
 * Issue #380 gives the castle three floors with jobs — ground is the mall,
 * **middle is the great hall**, roof is a garden. **That split has now landed**
 * (#377/#380), so the hall has moved off the ground floor and onto the middle
 * one, which is a floor of its own with nothing else on it.
 *
 * It was on deck 0 because that was the deck that already had a hall's
 * *fabric*: `castleDecor.ts` put the hearth, the coat of arms and the
 * portcullis behind `if (deck === 0)`, and a throne on a different storey from
 * the only fireplace in the castle would have read as two half-rooms rather
 * than one whole one. The note here promised that moving the hall would be
 * changing {@link CASTLE_GREAT_HALL_DECK}, and that `castleDecor.ts`'s own
 * block would move with it so the two could not be separated. **Both happened,
 * and it was one line each** — which is the whole argument for having written
 * the constant down rather than typing `0` in four places.
 *
 * ## The layout is derived from the wall, not typed against it
 *
 * Every X in this file comes out of {@link castleTorchAnchors} — the same list
 * the torches and the banners are placed from. A tapestry hangs on a **midpoint
 * between two torches**, and the throne stands centred on *its* tapestry, and
 * the feast table runs down the hall on the throne's own axis. So there is one
 * number, the anchor spacing, and everything inherits from it.
 *
 * That is not tidiness. The 3D Artist lost most of a day to a hall render in
 * which every sconce was **inside a tapestry** — tapestries centred on ±2.6 and
 * 3.2 m wide, sconces at ±1.2, so the pictures the sconce's size was being
 * judged from were not showing a sconce at all. Two independently-typed lists
 * of wall positions is exactly how that happens, and it cannot happen to
 * coordinates that are computed from the other list.
 *
 * ## No colliders, and that is not an oversight
 *
 * Indoor collision is height-blind — `registerInteriorCollision` walls the shell
 * once and it holds on every storey — so a collider under the throne on deck 0
 * would be an invisible pillar in the middle of floor 3. Nothing here registers
 * one. **Placement is the whole of the protection**, and `check:castle`'s prop
 * assertions are what enforce it.
 *
 * Issue #377's floor split removes that constraint by construction. What wants a
 * collider afterwards is written down in `HANDOFF-castle-great-hall.md` rather
 * than left to be rediscovered, and the interesting part is that **the bench,
 * the throne seat, the dais and the table top must not get a blocking one**: a
 * child is *meant* to climb onto all four, and a blocking body on a bench turns
 * the one object in the room built to be sat on into a wall. They take a
 * jump-on plate, the way `hotel/place.ts` already places props.
 */

/**
 * Which storey is the great hall.
 *
 * See this file's header: #380 moves it to the middle floor, and this is the
 * line that moves. It is deliberately the same value as `castleDecor.ts`'s hall
 * block so the throne and the fireplace cannot end up on different floors.
 */
export const CASTLE_GREAT_HALL_DECK = HALL_DECK;

/** Everything this file adds to a storey, so the check can find it. */
export function castleFurnitureGroupName(deck: number): string {
  return `castle-furniture-${deck}`;
}

/**
 * How wide a tapestry's cloth is, in metres — the Artist's A3 figure.
 *
 * Used only to keep other wall furniture out of the cloth's own band (see
 * {@link greatHallTapestries}), never to build anything, so it is an
 * *allowance* rather than a shared dimension: over-stating it costs a banner
 * moved along one bay, under-stating it costs a banner behind a tapestry.
 */
const TAPESTRY_WIDTH = 3.2;

/**
 * How much clear wall a tapestry claims either side of its own cloth.
 *
 * A banner hung 10 cm off the edge of a tapestry is not *behind* it but still
 * reads as a mistake, so the band is the cloth plus a hand's width.
 */
const TAPESTRY_MARGIN = 0.5;

/**
 * The three bays of the great hall's end wall, as wall anchors.
 *
 * **Midpoints between consecutive torches**, so a tapestry never lands on a
 * sconce — the fault described in this file's header — and consecutive, so the
 * three read as one composition behind the throne rather than as three
 * hangings scattered along a wall.
 *
 * Exported because `castleDecor.ts`'s banner run has to ask which bays are
 * taken. Two lists of wall positions kept in step by hand is the whole problem;
 * one list with an owner is the fix.
 */
export function greatHallTapestries(deck: number): readonly WallAnchor[] {
  if (deck !== CASTLE_GREAT_HALL_DECK) return [];

  // The end wall of the hall: the north wall (most negative Z), east half.
  // Anchors carry their own outward normal, so "which wall" is a property of
  // the anchor and never a sign this file has to get right.
  const northEast = castleTorchAnchors(deck)
    .filter((anchor) => anchor.out.z > 0.5 && anchor.x > 0)
    .sort((a, b) => a.x - b.x);
  if (northEast.length < 4) return [];

  const bays: WallAnchor[] = [];
  for (let i = 0; i + 1 < northEast.length && bays.length < 3; i += 1) {
    const left = northEast[i] as WallAnchor;
    const right = northEast[i + 1] as WallAnchor;
    // A bay only takes a 3.2 m cloth if the two torches are far enough apart to
    // leave it clear of both. Measured, so a change to the torch spacing moves
    // the tapestries or drops them rather than hanging one over a flame.
    if (right.x - left.x < TAPESTRY_WIDTH + TAPESTRY_MARGIN) continue;
    bays.push({ x: (left.x + right.x) / 2, z: left.z, yaw: left.yaw, out: left.out });
  }
  return bays;
}

/**
 * Is this point on a wall inside a bay a tapestry has claimed?
 *
 * `castleDecor.ts`'s banner run asks this so a banner is never hung behind a
 * tapestry. It is a question about *distance along the wall*, which on the
 * north wall is X.
 */
export function isTapestryBay(deck: number, x: number, z: number): boolean {
  const half = TAPESTRY_WIDTH / 2 + TAPESTRY_MARGIN;
  return greatHallTapestries(deck).some(
    (bay) => Math.abs(bay.x - x) < half && Math.abs(bay.z - z) < 1,
  );
}

/** The dais the throne stands on: broad enough to step onto from any side. */
const DAIS_HALF_X = 1.6;
const DAIS_HALF_Z = 1.2;

/**
 * Half the feast table's own length — **measured off the asset**, not typed.
 *
 * It stood here as `const TABLE_HALF_LENGTH = 3` with the comment "authored
 * size; it does not scale". Both halves of that were true and it was still a
 * second copy of a figure the asset already knows, which stopped being harmless
 * the moment #413 started *repeating* the table: the run's pitch is this
 * number, so a table that grew by a centimetre would open a centimetre gap
 * between every pair, and nothing would say so.
 */
const TABLE_HALF_LENGTH = CASTLE_TABLE_HALF_LENGTH;
/**
 * Clear floor between the dais and the table — the approach itself.
 *
 * A child's collision diameter is 1.24 m, so this is "two can pass abreast",
 * which is the least a hall's approach can be and still be one.
 */
const FEAST_APPROACH = 1.5;

/**
 * How far down the hall the feast table's centre sits from the throne.
 *
 * The table is 6 m long and the throne's dais is 2.4 m deep, so this leaves a
 * clear approach between the two — the space a child walks up to reach the
 * throne, which is the whole point of putting a throne at the end of a hall.
 *
 * ## Shortened from 10 m for #403, and this one is a judgement call
 *
 * Halving the plate's *area* left the ground floor 31.11 m deep instead of 44,
 * and the shafts that cross its middle did not shrink: the helter-skelter's
 * tube now reaches within 7.93 m of the north wall. At 10 m the feast's
 * benches stood at 15.75 m from that wall — past every shaft's north edge —
 * and `feastIsClearOfShafts` rejected **all three** bays, so `dressGreatHall`
 * returned early and built no hall at all. `check:castle`'s contract
 * assertion is what said so, out loud, rather than a hall quietly vanishing.
 *
 * Nothing here was made smaller to fix it: the throne, the dais, the table and
 * the benches are all the sizes the Artist authored. What closed is the *gap*
 * between the dais and the table, which is the same thing the shop run did and
 * is the density Jim asked for. 5.7 m is the shortest that still keeps a real
 * approach: the dais reaches 1.2 m from the throne, the table reaches 3 m back
 * towards it, leaving **1.5 m of clear floor** to walk up — a child is 1.24 m
 * across, so two can still pass. Any less and the table is on the dais.
 *
 * If #377 removes the helter-skelter, the constraint that forced this goes
 * with it and the hall can lengthen again. Do not lower this further to fit
 * something new in; move the something instead.
 */
const TABLE_FROM_THRONE = DAIS_HALF_Z + TABLE_HALF_LENGTH + FEAST_APPROACH;

/** How far the benches sit from the table's own axis. */
const BENCH_OFFSET = 1.85;

/**
 * The bench's own half-extents, and how far along the table each pair sits.
 *
 * Named rather than inlined because {@link feastIsClearOfShafts} has to predict
 * the footprint {@link feast} will build, and two copies of that arithmetic is
 * the bug this whole file's header is about.
 */
const BENCH_ALONG = 1.55;

/**
 * **How many feast tables stand end to end down the hall** (#413).
 *
 * Jim, 31 August 2026: *"ok let's do the banquet with the huge table, lots of
 * other children eating at the tables, and a large fireplace with a roaring
 * fire"* — and the ticket is explicit that the huge table runs **down the
 * middle of the hall, not at the end of it**.
 *
 * Three, and they are three copies of the **same** asset butted together
 * rather than one longer table. #413's own instruction ("extend or repeat the
 * one that exists; do not author a second"), and it is also the cheaper thing:
 * a 18 m table authored in Blender is a new node, a new style entry, a new
 * `check:castle` contract figure and a new thing that can disagree with
 * {@link CASTLE_TABLE_TOP}. Three of an asset whose top is already measured
 * and already asserted is none of that.
 *
 * They butt exactly because the pitch is the asset's own measured length. See
 * {@link TABLE_HALF_LENGTH}.
 *
 * Three is what the room has: the first table's far end is
 * {@link FEAST_APPROACH} clear of the dais, and the third's near end lands at
 * z ≈ +8.2 with 7 m of floor still behind it — so the run fills the hall's
 * middle without either crowding the throne or reaching the south wall.
 */
export const FEAST_TABLE_COUNT = 3;

/**
 * How far along a bench the two diners sitting on it are placed, either side of
 * its middle.
 *
 * Two per bench. Three would fit at a pinch and would read as a queue rather
 * than as a table people chose to sit at.
 *
 * **0.75 rather than 0.70, chosen off a screenshot.** At 0.70 the run's spacing
 * alternates 1.40 m within a bench and 1.70 m between benches, and a child's
 * *hair* is 1.53 m across even though her head is 1.36 — so the pairs sat with
 * their hair merged and a visible gap between pairs, which reads as six clumps
 * rather than as one full table. 0.75 makes it 1.50 and 1.60, near enough even
 * that the eye stops seeing pairs.
 *
 * It does not go further. The children would stop overlapping entirely at about
 * 0.90, and the table would then look half empty — which is the opposite of
 * what #413 asked for. Children at a feast sitting shoulder to shoulder is the
 * brief.
 */
const DINER_ALONG = 0.75;

/**
 * **Where the hall is laid out**, resolved once — its axis, its end wall, and
 * which way is into the room.
 *
 * Extracted from {@link dressGreatHall} because the banquet's diners
 * (`greatHallBanquet.ts`) sit on benches this file places, and they must be
 * placed from the **same** arithmetic rather than from a second copy of it. A
 * diner list derived independently is precisely the "two definitions of one
 * thing, kept in step by hand" that CLAUDE.md opens on, and it would fail in
 * the least visible way available: two dozen children floating beside a bench
 * that had moved a metre.
 */
export interface GreatHallPlan {
  /** The hall's long axis, in interior-local metres. */
  readonly axisX: number;
  /** The end wall the throne stands against. */
  readonly wallZ: number;
  /** +1 or -1: into the room, away from that wall. */
  readonly inward: number;
  /** The three tapestry bays behind the throne. */
  readonly bays: readonly WallAnchor[];
}

/** See {@link GreatHallPlan}. `null` on a storey that is not the great hall. */
export function greatHallPlan(deck: number): GreatHallPlan | null {
  if (deck !== CASTLE_GREAT_HALL_DECK) return null;
  const bays = greatHallTapestries(deck);
  if (bays.length < 3) return null;
  const centre = hallAxis(bays);
  if (!centre) return null;
  return { axisX: centre.x, wallZ: centre.z, inward: centre.out.z, bays };
}

/** The middle of each table in the run, nearest the throne first. */
function feastTableCentres(plan: GreatHallPlan): number[] {
  const first = plan.wallZ + plan.inward * (THRONE_FROM_WALL + TABLE_FROM_THRONE);
  return Array.from(
    { length: FEAST_TABLE_COUNT },
    (_, i) => first + plan.inward * i * TABLE_HALF_LENGTH * 2,
  );
}

/** One bench in the run: where its middle is, and which side of the table. */
interface BenchPlacement {
  readonly x: number;
  readonly z: number;
  /** -1 west of the axis, +1 east. */
  readonly side: number;
}

/** Every bench at the banquet, in placement order. */
function feastBenches(plan: GreatHallPlan): BenchPlacement[] {
  const benches: BenchPlacement[] = [];
  for (const tableZ of feastTableCentres(plan)) {
    for (const side of [-1, 1]) {
      for (const along of [-BENCH_ALONG, BENCH_ALONG]) {
        benches.push({ x: plan.axisX + side * BENCH_OFFSET, z: tableZ + along, side });
      }
    }
  }
  return benches;
}

/**
 * **Where a child sits at the banquet, and which way she faces.**
 *
 * `greatHallBanquet.ts` is the only caller. It is here rather than there
 * because a seat is a fact about a bench, and the benches are placed here.
 *
 * ## Why `x` is the plank's *inner face* and not the plank's middle
 *
 * The kid rig has no knee, so a seated child's legs can only hang vertically —
 * any rotation about the hip lifts her foot by `0.36·(1 − cos θ)`. Her hip
 * pivot is at `KID_HIP_HEIGHT`, so hips on a {@link CASTLE_BENCH_SEAT} plank
 * and feet on the floor is not one pose among several: it is the only one, and
 * it is the entire reason the Artist cut the bench to 0.360 m.
 *
 * But her torso reaches **0.18 m below her own hip pivot**. A child placed on
 * the middle of the plank therefore has 0.18 m of herself inside it. Placing
 * her on the plank's inner face puts that 0.18 m *behind* her instead, where
 * her own body hides it from a camera on the table's side — and it is the only
 * placement that does, because the gap between the table's edge and the
 * plank's inner face is 0.45 m and her hem is 0.80 m across. She does not fit
 * in front of the bench; she has to be half on it.
 *
 * The clearance that leaves in front of her is 5.2 cm against the table's edge,
 * which is thin enough that it is asserted rather than trusted — see
 * `check:castle`'s banquet assertion.
 */
export interface GreatHallSeat {
  readonly x: number;
  readonly z: number;
  /** Turns a +Z-facing child to look across the table. */
  readonly yaw: number;
}

/** Every seat at the banquet. See {@link GreatHallSeat}. */
export function greatHallSeats(deck: number): readonly GreatHallSeat[] {
  const plan = greatHallPlan(deck);
  if (!plan) return [];

  const seats: GreatHallSeat[] = [];
  for (const bench of feastBenches(plan)) {
    // The plank's inner face: its middle, pulled back towards the table by half
    // its own measured width. Never a typed 0.30.
    const x = bench.x - bench.side * CASTLE_BENCH_HALF_WIDTH;
    // A child faces +Z, so a quarter turn one way or the other looks across the
    // table. West of the axis she looks east.
    const yaw = bench.side < 0 ? Math.PI / 2 : -Math.PI / 2;
    for (const along of [-DINER_ALONG, DINER_ALONG]) {
      seats.push({ x, z: bench.z + along, yaw });
    }
  }
  return seats;
}

/**
 * **The gap a diner has to fit in**: clear floor between the bench plank's
 * inner face — where she sits — and the table's edge, in metres. 0.45 m.
 *
 * Derived from the two measured half-widths rather than read off the built
 * scene, so `check:castle` can compare a *prediction* against what was built
 * instead of restating it. A child's hem is 0.80 m across, which is what makes
 * this a fit rather than a placement: see {@link GreatHallSeat}.
 */
export const DINER_TABLE_GAP = BENCH_OFFSET - CASTLE_BENCH_HALF_WIDTH - CASTLE_TABLE_HALF_WIDTH;

/**
 * Where the throne stands, measured back from the end wall.
 *
 * Far enough off the wall that the **room's** 3.30 m ceiling applies rather
 * than the 3.08 m under the perimeter wall-plate: the throne is 2.75 m on a
 * 0.30 m dais, so it clears 3.30 with 25 cm to spare and would clear 3.08 by
 * only 1 cm. A throne that only fits because of where it happens to stand is a
 * placement rule nobody will remember.
 */
const THRONE_FROM_WALL = 2.8;

/**
 * Stands the great hall's furniture on `deck`.
 *
 * Called by `castleDecor.ts`'s `dressCastle` so that everything here lands
 * inside `check:castle`'s prop assertions for free — they walk the built group
 * and ask nothing about what a prop *is*.
 */
export function dressGreatHall(deck: number, floor: Group): void {
  const plan = greatHallPlan(deck);
  if (!plan) return;

  const group = new Group();
  group.name = castleFurnitureGroupName(deck);

  const { bays, wallZ, inward, axisX } = plan;

  for (const bay of bays) group.add(...tapestry(bay));

  const throneZ = wallZ + inward * THRONE_FROM_WALL;
  group.add(dais(axisX, throneZ));

  const throne = createCastleThrone();
  throne.root.position.set(axisX, CASTLE_DAIS_HEIGHT, throneZ);
  // The sitter faces +Z; `inward` is +1 on the north wall, so a throne on the
  // north wall looks down the hall at the door with no rotation at all.
  throne.root.rotation.y = inward > 0 ? 0 : Math.PI;
  group.add(throne.root);

  // A guard of honour flanking the approach, rather than two suits of armour
  // pushed into the corners where nobody walks past them.
  for (const side of [-1, 1]) {
    group.add(...armourOnPlinth(axisX + side * 5, wallZ + inward * 4.3, inward));
  }

  group.add(...feast(plan));

  // A bench by the fire, where `castleDecor.ts` has already put the cat and the
  // woodpile. Its Z comes from the hearth's own constant, so it cannot end up
  // warming a fireplace that has moved.
  if (deck === CASTLE_HEARTH.deck) {
    const fireside = createCastleBench();
    fireside.root.position.set(CASTLE_HEARTH.x, 0, CASTLE_HEARTH.z + 2.4);
    // Turned to face the fire — the long axis is +Z, so a quarter turn lays it
    // along the hearth wall.
    fireside.root.rotation.y = Math.PI / 2;
    group.add(fireside.root);
  }

  const chest = createCastleChest();
  chest.root.position.set(axisX + 9.5, 0, wallZ + inward * 3.4);
  chest.root.rotation.y = inward > 0 ? 0 : Math.PI;
  group.add(chest.root);

  floor.add(group);
}

/**
 * Which bay the hall is laid out on — **chosen by testing, not typed.**
 *
 * The middle of the three is preferred, because a throne centred among its
 * tapestries with one either side is the composition a great hall wants.
 *
 * **And it now gets it.** The middle bay used to be rejected: the
 * helter-skelter's tube came down through `HELTER_SHAFT` (x 16.5–23.5) and the
 * middle bay's eastern benches stood at x 16.50–17.10, inside it — a slide
 * growing out of the dinner table, found by looking at a screenshot because
 * `keepOutsFor` guarded the helter's disc on the deck a child got *on* at,
 * not the deck the tube passed through.
 *
 * The version of this function that stood here ended with a prediction:
 * *"when #377 removes the helter-skelter the middle bay becomes usable again
 * and the hall re-centres itself with no edit here. A typed axis would have had
 * to be remembered."* #377 has removed it — along with every other shaft — and
 * that is exactly what happened. The `feastIsClearOfShafts` test it guarded
 * itself with is gone with the shafts it tested against; the preference order
 * it wrapped is all that was ever needed once there is nothing in the way.
 */
function hallAxis(bays: readonly WallAnchor[]): WallAnchor | null {
  // Middle first, then out to the sides — best composition, and now nothing
  // can refuse it.
  const order = [1, 0, 2].filter((i) => i < bays.length);
  for (const index of order) {
    const bay = bays[index];
    if (bay) return bay;
  }
  return null;
}



/** One tapestry: cloth and rail, both hung from {@link CASTLE_TAPESTRY_RAIL_Y}. */
function tapestry(bay: WallAnchor): Object3D[] {
  const cloth = createCastleTapestry();
  cloth.root.position.set(bay.x, CASTLE_TAPESTRY_RAIL_Y, bay.z);
  cloth.root.rotation.y = bay.yaw;

  const rail = createCastleTapestryRail();
  // The same Y, from the same constant, for the same reason §4.4 insists the
  // hang point and the rail centre are one number: a cloth authored to hang
  // from 2.90 on a rail fixed anywhere else shows a strip of daylight along the
  // top of every tapestry in the castle.
  rail.root.position.set(bay.x, CASTLE_TAPESTRY_RAIL_Y, bay.z);
  rail.root.rotation.y = bay.yaw;

  return [cloth.root, rail.root];
}

/**
 * The step the throne stands on — mine to build, per the asset contract, and
 * {@link CASTLE_DAIS_HEIGHT} high.
 *
 * It is a *step*, not a plinth: 0.30 m is below a child's hip, so getting onto
 * the throne is one stride up and then a sit, rather than a climb. That is the
 * same reasoning that puts the throne's own seat at `KID_HIP_HEIGHT`.
 */
function dais(x: number, z: number): Mesh {
  const geometry = new BoxGeometry(DAIS_HALF_X * 2, CASTLE_DAIS_HEIGHT, DAIS_HALF_Z * 2);
  geometry.translate(0, CASTLE_DAIS_HEIGHT / 2, 0);
  const mesh = solid(new Mesh(geometry, castleFloorMaterial(PALETTE.stonePinkDark)));
  mesh.name = 'castle-throne-dais';
  mesh.position.set(x, 0, z);
  mesh.receiveShadow = true;
  addOutline(mesh, 0.02);
  return mesh;
}

/** A suit of armour on its plinth, facing into the room. */
function armourOnPlinth(x: number, z: number, inward: number): Object3D[] {
  const plinth = createCastleArmourPlinth();
  plinth.root.position.set(x, 0, z);

  const armour = createCastleArmour();
  // Stood on the plinth's **measured surface**, not on its dressed height —
  // the dressed figure includes the outline hull and would float the knight
  // 2 cm. See `castleAssets.ts`'s `surfaceTop`.
  armour.root.position.set(x, CASTLE_PLINTH_TOP, z);
  armour.root.rotation.y = inward > 0 ? 0 : Math.PI;

  return [plinth.root, armour.root];
}

/** What is on the table, and in what order down its length. */
const FEAST_SETTING: readonly FeastProp[] = [
  'goblet',
  'loaf',
  'goblet',
  'roast',
  'goblet',
  'pie',
  'goblet',
  'loaf',
];

/**
 * **The banquet**: three tables end to end down the middle of the hall, benches
 * both sides of every one of them, and the meal laid the whole length.
 *
 * This was one 6 m table parked at the throne end. #413 makes it a run — see
 * {@link FEAST_TABLE_COUNT} for why it repeats the asset rather than growing
 * one, and why three.
 *
 * The tables **butt**, because the pitch is `TABLE_HALF_LENGTH * 2` and that is
 * the asset's own measured length: there is no gap to tune and no seam to
 * notice, and there could not be one without the asset changing size.
 */
function feast(plan: GreatHallPlan): Object3D[] {
  const out: Object3D[] = [];
  const { axisX } = plan;

  for (const z of feastTableCentres(plan)) {
    const table = createCastleFeastTable();
    table.root.position.set(axisX, 0, z);
    out.push(table.root);

    // Laid down the middle of the table, on its **measured** top. A goblet
    // standing on a typed 1.05 would have been 37 cm in the air ever since the
    // furniture was cut to a child.
    FEAST_SETTING.forEach((kind, index) => {
      const prop = createCastleFeastProp(kind);
      const along = (index - (FEAST_SETTING.length - 1) / 2) * 0.72;
      // Alternate sides of the centre line so it reads as places laid for people
      // sitting on both benches, not as a row of objects.
      prop.root.position.set(axisX + (index % 2 === 0 ? -0.55 : 0.55), CASTLE_TABLE_TOP, z + along);
      // Turned by its own place at the table rather than by its index within
      // one table's setting, so the three tables are not three identical rows.
      prop.root.rotation.y = (index + z) * 1.31;
      out.push(prop.root);
    });
  }

  // Two benches a side per table rather than one long one: the asset is 2.80 m,
  // and `feastBenches` is the same list `greatHallSeats` seats children from, so
  // a diner cannot end up beside a bench rather than on it.
  for (const { x, z } of feastBenches(plan)) {
    const bench = createCastleBench();
    bench.root.position.set(x, 0, z);
    out.push(bench.root);
  }

  return out;
}

/** Where the bench seat and table top ended up, for anything that asks. */
export const GREAT_HALL_SEAT_HEIGHT = CASTLE_BENCH_SEAT;
export const GREAT_HALL_TABLE_HEIGHT = CASTLE_TABLE_TOP;
