import { BoxGeometry, Group, Mesh, type Object3D } from 'three';
import { PALETTE } from '../../art/style/bridge';
import { addOutline, solid } from '../../art/style/materials';
import {
  CASTLE_BENCH_SEAT,
  CASTLE_DAIS_HEIGHT,
  CASTLE_PLINTH_TOP,
  CASTLE_TABLE_TOP,
  CASTLE_TAPESTRY_RAIL_Y,
  createCastleArmour,
  createCastleArmourPlinth,
  createCastleBench,
  createCastleChest,
  createCastleFeastProp,
  createCastleFeastTable,
  createCastleTapestry,
  createCastleTapestryRail,
  createCastleThrone,
  type FeastProp,
} from '../../art/models/castleAssets';
import { castleFloorMaterial } from './castleFabric';
import { CASTLE_HEARTH, castleTorchAnchors, type WallAnchor } from './castleLighting';

/**
 * **The great hall's furniture** — batch 1 of the castle's authored geometry
 * (PR #368), placed.
 *
 * The assets landed as bytes and were wired into nothing: `castle.glb` existed,
 * regenerated byte-identically, and no player could see a single one of them.
 * This file is the other half.
 *
 * ## Where the hall is, and why it is one constant
 *
 * Issue #380 gives the castle three floors with jobs — ground is the mall,
 * **middle is the great hall**, roof is a garden — but that split has not landed
 * and the building still has five storeys. So the hall goes on the deck that
 * already has a hall's *fabric* on it: `castleDecor.ts` puts the hearth, the
 * coat of arms and the portcullis behind `if (deck === 0)`, and a throne on a
 * different storey from the only fireplace in the castle would read as two
 * half-rooms rather than one whole one.
 *
 * {@link CASTLE_GREAT_HALL_DECK} is therefore a single constant, and moving the
 * hall when #380 lands is changing it. That is the same one-line promise
 * `castleDecor.ts` makes about its own `deck === 0` block, deliberately, so the
 * two move together rather than one being found later on the wrong floor.
 *
 * ## The layout is derived from the wall, not typed against it
 *
 * Every X in this file comes out of {@link castleTorchAnchors} — the same list
 * the torches and the banners are placed from. A tapestry hangs on a **midpoint
 * between two torches**, and the throne stands centred on *its* tapestry, and
 * the feast table runs down the hall on the throne's own axis. So there is one
 * number, the anchor spacing, and everything inherits from it.
 *
 * That is not tidiness. The 3D Artist lost most of a day to a hall render in
 * which every sconce was **inside a tapestry** — tapestries centred on ±2.6 and
 * 3.2 m wide, sconces at ±1.2, so the pictures the sconce's size was being
 * judged from were not showing a sconce at all. Two independently-typed lists
 * of wall positions is exactly how that happens, and it cannot happen to
 * coordinates that are computed from the other list.
 *
 * ## No colliders, and that is not an oversight
 *
 * Indoor collision is height-blind — `registerInteriorCollision` walls the shell
 * once and it holds on every storey — so a collider under the throne on deck 0
 * would be an invisible pillar in the middle of floor 3. Nothing here registers
 * one. **Placement is the whole of the protection**, and `check:castle`'s prop
 * assertions are what enforce it.
 *
 * Issue #377's floor split removes that constraint by construction. What wants a
 * collider afterwards is written down in `HANDOFF-castle-great-hall.md` rather
 * than left to be rediscovered, and the interesting part is that **the bench,
 * the throne seat, the dais and the table top must not get a blocking one**: a
 * child is *meant* to climb onto all four, and a blocking body on a bench turns
 * the one object in the room built to be sat on into a wall. They take a
 * jump-on plate, the way `hotel/place.ts` already places props.
 */

/**
 * Which storey is the great hall.
 *
 * See this file's header: #380 moves it to the middle floor, and this is the
 * line that moves. It is deliberately the same value as `castleDecor.ts`'s hall
 * block so the throne and the fireplace cannot end up on different floors.
 */
export const CASTLE_GREAT_HALL_DECK = 0;

/** Everything this file adds to a storey, so the check can find it. */
export function castleFurnitureGroupName(deck: number): string {
  return `castle-furniture-${deck}`;
}

/**
 * How wide a tapestry's cloth is, in metres — the Artist's A3 figure.
 *
 * Used only to keep other wall furniture out of the cloth's own band (see
 * {@link greatHallTapestries}), never to build anything, so it is an
 * *allowance* rather than a shared dimension: over-stating it costs a banner
 * moved along one bay, under-stating it costs a banner behind a tapestry.
 */
const TAPESTRY_WIDTH = 3.2;

/**
 * How much clear wall a tapestry claims either side of its own cloth.
 *
 * A banner hung 10 cm off the edge of a tapestry is not *behind* it but still
 * reads as a mistake, so the band is the cloth plus a hand's width.
 */
const TAPESTRY_MARGIN = 0.5;

/**
 * The three bays of the great hall's end wall, as wall anchors.
 *
 * **Midpoints between consecutive torches**, so a tapestry never lands on a
 * sconce — the fault described in this file's header — and consecutive, so the
 * three read as one composition behind the throne rather than as three
 * hangings scattered along a wall.
 *
 * Exported because `castleDecor.ts`'s banner run has to ask which bays are
 * taken. Two lists of wall positions kept in step by hand is the whole problem;
 * one list with an owner is the fix.
 */
export function greatHallTapestries(deck: number): readonly WallAnchor[] {
  if (deck !== CASTLE_GREAT_HALL_DECK) return [];

  // The end wall of the hall: the north wall (most negative Z), east half.
  // Anchors carry their own outward normal, so "which wall" is a property of
  // the anchor and never a sign this file has to get right.
  const northEast = castleTorchAnchors(deck)
    .filter((anchor) => anchor.out.z > 0.5 && anchor.x > 0)
    .sort((a, b) => a.x - b.x);
  if (northEast.length < 4) return [];

  const bays: WallAnchor[] = [];
  for (let i = 0; i + 1 < northEast.length && bays.length < 3; i += 1) {
    const left = northEast[i] as WallAnchor;
    const right = northEast[i + 1] as WallAnchor;
    // A bay only takes a 3.2 m cloth if the two torches are far enough apart to
    // leave it clear of both. Measured, so a change to the torch spacing moves
    // the tapestries or drops them rather than hanging one over a flame.
    if (right.x - left.x < TAPESTRY_WIDTH + TAPESTRY_MARGIN) continue;
    bays.push({ x: (left.x + right.x) / 2, z: left.z, yaw: left.yaw, out: left.out });
  }
  return bays;
}

/**
 * Is this point on a wall inside a bay a tapestry has claimed?
 *
 * `castleDecor.ts`'s banner run asks this so a banner is never hung behind a
 * tapestry. It is a question about *distance along the wall*, which on the
 * north wall is X.
 */
export function isTapestryBay(deck: number, x: number, z: number): boolean {
  const half = TAPESTRY_WIDTH / 2 + TAPESTRY_MARGIN;
  return greatHallTapestries(deck).some(
    (bay) => Math.abs(bay.x - x) < half && Math.abs(bay.z - z) < 1,
  );
}

/**
 * How far down the hall the feast table's centre sits from the throne.
 *
 * The table is 6 m long and the throne's dais is 2.4 m deep, so this leaves a
 * clear approach between the two — the space a child walks up to reach the
 * throne, which is the whole point of putting a throne at the end of a hall.
 */
const TABLE_FROM_THRONE = 10;

/** How far the benches sit from the table's own axis. */
const BENCH_OFFSET = 1.85;

/** The dais the throne stands on: broad enough to step onto from any side. */
const DAIS_HALF_X = 1.6;
const DAIS_HALF_Z = 1.2;

/**
 * Where the throne stands, measured back from the end wall.
 *
 * Far enough off the wall that the **room's** 3.30 m ceiling applies rather
 * than the 3.08 m under the perimeter wall-plate: the throne is 2.75 m on a
 * 0.30 m dais, so it clears 3.30 with 25 cm to spare and would clear 3.08 by
 * only 1 cm. A throne that only fits because of where it happens to stand is a
 * placement rule nobody will remember.
 */
const THRONE_FROM_WALL = 2.8;

/**
 * Stands the great hall's furniture on `deck`.
 *
 * Called by `castleDecor.ts`'s `dressCastle` so that everything here lands
 * inside `check:castle`'s prop assertions for free — they walk the built group
 * and ask nothing about what a prop *is*.
 */
export function dressGreatHall(deck: number, floor: Group): void {
  if (deck !== CASTLE_GREAT_HALL_DECK) return;

  const bays = greatHallTapestries(deck);
  if (bays.length < 3) return;

  const group = new Group();
  group.name = castleFurnitureGroupName(deck);

  // The hall's axis: the middle bay of the three, so the throne is centred on
  // its own tapestry by construction rather than by two numbers that agree.
  const centre = bays[1] as WallAnchor;
  const wallZ = centre.z;
  // Into the room, away from whichever wall the bay is on.
  const inward = centre.out.z;
  const axisX = centre.x;

  for (const bay of bays) group.add(...tapestry(bay));

  const throneZ = wallZ + inward * THRONE_FROM_WALL;
  group.add(dais(axisX, throneZ));

  const throne = createCastleThrone();
  throne.root.position.set(axisX, CASTLE_DAIS_HEIGHT, throneZ);
  // The sitter faces +Z; `inward` is +1 on the north wall, so a throne on the
  // north wall looks down the hall at the door with no rotation at all.
  throne.root.rotation.y = inward > 0 ? 0 : Math.PI;
  group.add(throne.root);

  // A guard of honour flanking the approach, rather than two suits of armour
  // pushed into the corners where nobody walks past them.
  for (const side of [-1, 1]) {
    group.add(...armourOnPlinth(axisX + side * 5, wallZ + inward * 4.3, inward));
  }

  const tableZ = wallZ + inward * (THRONE_FROM_WALL + TABLE_FROM_THRONE);
  group.add(...feast(axisX, tableZ));

  // A bench by the fire, where `castleDecor.ts` has already put the cat and the
  // woodpile. Its Z comes from the hearth's own constant, so it cannot end up
  // warming a fireplace that has moved.
  if (deck === CASTLE_HEARTH.deck) {
    const fireside = createCastleBench();
    fireside.root.position.set(CASTLE_HEARTH.x, 0, CASTLE_HEARTH.z + 2.4);
    // Turned to face the fire — the long axis is +Z, so a quarter turn lays it
    // along the hearth wall.
    fireside.root.rotation.y = Math.PI / 2;
    group.add(fireside.root);
  }

  const chest = createCastleChest();
  chest.root.position.set(axisX + 9.5, 0, wallZ + inward * 3.4);
  chest.root.rotation.y = inward > 0 ? 0 : Math.PI;
  group.add(chest.root);

  floor.add(group);
}

/** One tapestry: cloth and rail, both hung from {@link CASTLE_TAPESTRY_RAIL_Y}. */
function tapestry(bay: WallAnchor): Object3D[] {
  const cloth = createCastleTapestry();
  cloth.root.position.set(bay.x, CASTLE_TAPESTRY_RAIL_Y, bay.z);
  cloth.root.rotation.y = bay.yaw;

  const rail = createCastleTapestryRail();
  // The same Y, from the same constant, for the same reason §4.4 insists the
  // hang point and the rail centre are one number: a cloth authored to hang
  // from 2.90 on a rail fixed anywhere else shows a strip of daylight along the
  // top of every tapestry in the castle.
  rail.root.position.set(bay.x, CASTLE_TAPESTRY_RAIL_Y, bay.z);
  rail.root.rotation.y = bay.yaw;

  return [cloth.root, rail.root];
}

/**
 * The step the throne stands on — mine to build, per the asset contract, and
 * {@link CASTLE_DAIS_HEIGHT} high.
 *
 * It is a *step*, not a plinth: 0.30 m is below a child's hip, so getting onto
 * the throne is one stride up and then a sit, rather than a climb. That is the
 * same reasoning that puts the throne's own seat at `KID_HIP_HEIGHT`.
 */
function dais(x: number, z: number): Mesh {
  const geometry = new BoxGeometry(DAIS_HALF_X * 2, CASTLE_DAIS_HEIGHT, DAIS_HALF_Z * 2);
  geometry.translate(0, CASTLE_DAIS_HEIGHT / 2, 0);
  const mesh = solid(new Mesh(geometry, castleFloorMaterial(PALETTE.stonePinkDark)));
  mesh.name = 'castle-throne-dais';
  mesh.position.set(x, 0, z);
  mesh.receiveShadow = true;
  addOutline(mesh, 0.02);
  return mesh;
}

/** A suit of armour on its plinth, facing into the room. */
function armourOnPlinth(x: number, z: number, inward: number): Object3D[] {
  const plinth = createCastleArmourPlinth();
  plinth.root.position.set(x, 0, z);

  const armour = createCastleArmour();
  // Stood on the plinth's **measured surface**, not on its dressed height —
  // the dressed figure includes the outline hull and would float the knight
  // 2 cm. See `castleAssets.ts`'s `surfaceTop`.
  armour.root.position.set(x, CASTLE_PLINTH_TOP, z);
  armour.root.rotation.y = inward > 0 ? 0 : Math.PI;

  return [plinth.root, armour.root];
}

/** What is on the table, and in what order down its length. */
const FEAST_SETTING: readonly FeastProp[] = [
  'goblet',
  'loaf',
  'goblet',
  'roast',
  'goblet',
  'pie',
  'goblet',
  'loaf',
];

/** The banqueting table, its benches, and the meal laid on it. */
function feast(x: number, z: number): Object3D[] {
  const out: Object3D[] = [];

  const table = createCastleFeastTable();
  table.root.position.set(x, 0, z);
  out.push(table.root);

  // Two benches a side rather than one 6 m one: the asset is 2.80 m, and four
  // of them is what the contract asked for.
  for (const side of [-1, 1]) {
    for (const along of [-1.55, 1.55]) {
      const bench = createCastleBench();
      bench.root.position.set(x + side * BENCH_OFFSET, 0, z + along);
      out.push(bench.root);
    }
  }

  // Laid down the middle of the table, on its **measured** top. A goblet
  // standing on a typed 1.05 would have been 37 cm in the air ever since the
  // furniture was cut to a child.
  FEAST_SETTING.forEach((kind, index) => {
    const prop = createCastleFeastProp(kind);
    const along = (index - (FEAST_SETTING.length - 1) / 2) * 0.72;
    // Alternate sides of the centre line so it reads as places laid for people
    // sitting on both benches, not as a row of objects.
    prop.root.position.set(x + (index % 2 === 0 ? -0.55 : 0.55), CASTLE_TABLE_TOP, z + along);
    prop.root.rotation.y = index * 1.31;
    out.push(prop.root);
  });

  return out;
}

/** Where the bench seat and table top ended up, for anything that asks. */
export const GREAT_HALL_SEAT_HEIGHT = CASTLE_BENCH_SEAT;
export const GREAT_HALL_TABLE_HEIGHT = CASTLE_TABLE_TOP;
