/**
 * **The park's warp vector** — the decision overrides the warp search found
 * for this seed, applied when the pipeline replays (issue: park-warp solver;
 * Jim's ruling 2 Sep 2026: prefer "park-warping mutations" over blind
 * backtracking).
 *
 * ## What a warp is
 *
 * The procgen pipeline is deterministic in `PARK_SEED` plus a handful of
 * seeded candidate streams. A *warp* perturbs one named decision — "draw the
 * dodgems' layout candidates from restart stream 3 instead of 0" — and the
 * whole pipeline is then replayed from scratch. A warp never edits a built
 * park in place: every warped park is a complete fresh solve, so no
 * half-mutated park can exist (the whack-a-mole failure mode recorded on
 * #414 is unrepresentable).
 *
 * ## Where a vector comes from
 *
 * - **Baked** (the shipped game): `WARPS_BY_SEED` below, written by the
 *   offline warp search and checked in. A pool seed that needs no warp has
 *   no entry. This is the ONLY source in the browser.
 * - **`LGP_WARP`** (Node only): a JSON `WarpVector`, for the search itself
 *   and for measurement scripts. Overrides the baked entry entirely when
 *   set, exactly as `LGP_SEED` overrides the seed.
 *
 * With no baked entry and no env override every stream runs at offset 0 and
 * the pipeline is byte-identical to a build of this module's parent commit —
 * that inertness is load-bearing: it is what makes the warp machinery safe
 * to land ahead of the search that uses it.
 */
import { PARK_SEED } from './parkManifest';

export interface WarpVector {
  /**
   * Per-manifest-entry layout stream bump: `layout['dodgems'] = 3` makes the
   * dodgems draw its placement candidates from `restart + 3` while every
   * other entry keeps `restart + 0`. Per-entry streams (parkLayout.ts,
   * issue #241) are what make this a *local* move: no other entry's
   * candidates shift, though later entries still validate against the moved
   * plot, which is the point.
   */
  readonly layout?: Readonly<Record<string, number>>;
  /**
   * Start the whole-park layout restart loop here instead of 0 — the
   * coarsest layout move, re-rolling every entry's arrangement at once.
   */
  readonly layoutRestart?: number;
  /**
   * Rail distances (rounded to the metre, as printed by `LGP_DEBUG_BRIDGE`)
   * of crossing candidates the crossing march must refuse. Banning a site
   * makes `selectSpaced` choose its next-best spacing, which is how the
   * search re-sites a crossing that paths cannot use well.
   */
  readonly banCrossingsAt?: readonly number[];
}

/**
 * Warp vectors the offline search has baked for pool seeds. Regenerated by
 * the warp-search script, never edited by hand; absence means "this seed
 * solves unwarped".
 *
 * ## Two vintages live here, and the difference matters
 *
 * A vector is only meaningful against the geometry it was searched on, so a
 * change to the geometry invalidates every vector baked before it. There have
 * been two such moments, and each entry below says which vintage it belongs
 * to:
 *
 * - **2 Sep 2026, the level-tier-empty park.** The original bake
 *   (`measurements/warp-search-2sep-*.jsonl`). Gate at the time: ratchet-on
 *   `check:park` exit 0 with zero stranded, plus the unallowanced vitest
 *   oracle on the seeds that have a per-seed invariant file (#437). These
 *   exist to reconnect the garden pockets the level crossings used to carry.
 * - **2 Sep 2026, after the rail route's dead spot was fixed.**
 *   `rail/generate.ts`'s `buildRoute` used to give only the first piece a
 *   `t = 0` stop, so every route answered with the same point for up to
 *   0.35 m at each join. Fixing it moves **every** route slightly, which
 *   re-solves every park, which is exactly the thing a baked vector cannot
 *   survive. Seeds **5, 115 and 326** were re-searched against the fixed
 *   geometry (`measurements/warp-search-2sep-railroute-fix.jsonl`); the other
 *   four were re-vetted and still hold.
 *
 * **If you change the geometry again, the vectors are stale again.** The tell
 * is neither gate on its own, because the three that went stale failed in
 * both directions: 115 was `check:park`-green with three invariants red, 326
 * was invariant-green (81/81) with `check:park` stranding 8. The tell is
 * `pnpm run vet:seeds` over the whole pool, which runs both.
 *
 * And note `check:park` is **canonical-only** — it never builds a pool seed's
 * park at all — while `CI_SWEEP_SEEDS` covers six of the sixteen. So the
 * blocking chain structurally cannot see a stale vector on the other ten, and
 * did not see 326's even though 326 is in the sweep list. See
 * `parkSeedPool.ts`'s note beside `CI_SWEEP_SEEDS`.
 */
const WARPS_BY_SEED: Readonly<Record<number, WarpVector>> = {
  // First baked as {ferrisWheel:2}, which passed check:park and all 81
  // invariants yet failed check:path-preference's kerb-step clause in CI
  // (84.1% vs 73% ceiling) — the canonical seed answers to canonical-only
  // gates the pool seeds do not (#437). Re-searched with that gate in the
  // acceptance loop: {hotel:2}, candidate 22.
  20260728: { layout: { hotel: 2 } },
  // Re-searched 2 Sep 2026, after `rail/generate.ts`'s `buildRoute` stopped
  // leaving a dead spot at every piece join: that fix moves every route
  // slightly, so the vector baked against the old geometry
  // (`{ferrisWheel:2}`) is no longer the one this seed wants — it now leaves
  // one pair of destinations with a 30.8x paved detour. Re-run of
  // `scripts/warp-search.mts 5`, control passed first: SOLVED after 5
  // candidates, stranded=0, oracle=pass.
  // (measurements/warp-search-2sep-railroute-fix.jsonl.)
  //
  // Note the empty vector is *not* enough here even though seed 5 passes all
  // 81 of its own invariants unwarped — check:park still strands 10 waypoints
  // on it. Both gates, or it is not a vector.
  5: { layout: { waterFight: 1 } },
  // Not a stranded seed originally: 24's unwarped network crossed the rail
  // at railD 47.8, off every proven site — absorbed silently as a fence gap
  // while the level tier existed, invisible to check:park (which samples only
  // the entrance route), surfaced the moment crossings.ts learned to throw.
  //
  // **Re-searched 3 Sep 2026, after this branch was rebased onto main
  // c95facf6.** The old vector was {waterFight:1}, baked before #499's
  // round-robin spine reordered generation, #502 moved the bushes and #508
  // stopped check scripts building a randomly drawn park. On the rebased tree
  // it strands one waypoint at (9.1, -55.8) — check:park red, all 88
  // invariants still green, which is the same split 115 showed in the other
  // direction and the reason the whole pool has to be vetted rather than
  // either gate trusted. Control run first and passed; SOLVED after 28
  // candidates, stranded=0, oracle=pass.
  // (measurements/warp-search-post-rebase-24-428.jsonl.)
  24: { layout: { 'stall.skyCruiser': 2 } },
  // 225 was one of the full pool re-vet's catches (2 Sep): green under
  // check:park, red under the invariant suite (Sky Cruiser clearance) — the
  // same #437 shape as 326. Proved with a throwaway vet-style oracle, since
  // it has no checked-in test file. Still holds on the fixed geometry
  // (re-vetted, 81/81).
  //
  // **115 is second-vintage.** It was `{dodgems:1}`, baked against the park
  // the route's dead spot produced. On the fixed geometry that vector goes to
  // 78/81 — three red: the bridge-tunnel ray clearance, the coping stones,
  // and "every crossing on a site the planner proved bridgeable still carries
  // its bridge". `check:park` stayed green throughout and 115 is not in
  // `CI_SWEEP_SEEDS`, so nothing in the blocking chain could see it; only
  // `vet:seeds` over the whole pool could, and did.
  //
  // Worth recording why this is *not* the other explanation that was on the
  // table. The bridge-tunnel invariant takes its across-track direction from
  // a 0.1 m finite difference on `route.pointAt`, which inside the old dead
  // spot returned the identical point twice — `norm` 0, the `|| 1` guard, and
  // the whole probe fan collapsing onto the centreline. That is a real latent
  // blindness and the fix removes it, so "a pre-existing breach merely
  // uncovered" was the obvious suspicion. Measured instead of assumed: on the
  // pre-fix geometry, with that tangent replaced by the route's own
  // `tangentAt` so the fan is honest, 115 still passes **81/81**. The breach
  // is not older than the fix; it is this seed's vector being stale.
  //
  // Re-searched 2 Sep 2026, control passed first: SOLVED after 8 candidates,
  // stranded=0, oracle=pass.
  115: { layout: { hotel: 1 } },
  225: { layout: { 'stall.railRacer': 1 } },
  288: { layout: { waterFight: 1 } },
  // **326 is second-vintage**, and it is the #437 blind spot pointing the
  // other way from 115's. First baked as {fountain:1} on check:park evidence
  // alone; the moment seed-326.test.ts existed that went red on ONE invariant
  // the check cannot see (the slide climbing 0.001 m), so it was re-searched
  // with the oracle in the loop to {waterFight:1}.
  //
  // On the fixed geometry {waterFight:1} keeps passing all 81 invariants and
  // fails the *other* gate instead: check:park strands 8 waypoints
  // (216/216 connected before, 208/216 after). So neither gate implies the
  // other in either direction, which is why vet:seeds runs both — and note
  // check:park is **canonical-only**, so even though 326 is in
  // CI_SWEEP_SEEDS nothing in the blocking chain builds its park under
  // check:park. The `--- seed N: passed` lines in a `check` log are
  // check:fountain-hop's sweep, not check:park's.
  //
  // Re-searched 2 Sep 2026: SOLVED after 3 candidates, stranded=0,
  // oracle=pass.
  326: { layout: { building: 1 } },
  // **New on 3 Sep 2026, and the one that shows a seed can go bad without
  // ever having had a vector.** 428 passed both gates unwarped on this branch
  // before the rebase (measurements/rebased-vet-seeds.jsonl records it), so
  // it had no entry here at all. Rebased onto main c95facf6 it strands six
  // waypoints, clustered along the top of the park — (18.2, 53.2) (6.9, 57.1)
  // (10.7, 58.2) (14.6, 57.1) (18.4, 57.1) (20.6, 55.1) — with its invariants
  // still green.
  //
  // The absence of an entry is therefore NOT evidence a seed is safe across a
  // rebase; only a whole-pool vet:seeds is. 428 has no per-seed invariant file
  // either, so nothing in the blocking chain could see this (issue #510).
  // Control run first and passed; SOLVED after 16 candidates, stranded=0,
  // oracle=pass. (measurements/warp-search-post-rebase-24-428.jsonl.)
  428: { layout: { fountain: 2 } },
};

function envWarp(): WarpVector | null {
  try {
    const nodeProcess = (globalThis as { process?: { env?: Record<string, string> } }).process;
    const raw = nodeProcess?.env?.['LGP_WARP'];
    if (!raw) return null;
    return JSON.parse(raw) as WarpVector;
  } catch {
    return null;
  }
}

/** The one vector this park is built with, resolved once at module load. */
export const PARK_WARP: WarpVector = envWarp() ?? WARPS_BY_SEED[PARK_SEED] ?? {};

/** The layout stream bump for one manifest entry (0 when unwarped). */
export function layoutStreamBump(entryId: string): number {
  return PARK_WARP.layout?.[entryId] ?? 0;
}

/** Where the layout's whole-park restart loop starts (0 when unwarped). */
export function layoutRestartBase(): number {
  return PARK_WARP.layoutRestart ?? 0;
}

/** Whether the crossing march must refuse a candidate at this rail distance. */
export function crossingSiteBanned(railDistance: number): boolean {
  const banned = PARK_WARP.banCrossingsAt;
  if (!banned || banned.length === 0) return false;
  return banned.some((d) => Math.abs(d - railDistance) < 0.5);
}
