/**
 * **The park's warp vector** — the decision overrides the warp search found
 * for this seed, applied when the pipeline replays (issue: park-warp solver;
 * Jim's ruling 2 Sep 2026: prefer "park-warping mutations" over blind
 * backtracking).
 *
 * ## What a warp is
 *
 * The procgen pipeline is deterministic in `PARK_SEED` plus a handful of
 * seeded candidate streams. A *warp* perturbs one named decision — "draw the
 * dodgems' layout candidates from restart stream 3 instead of 0" — and the
 * whole pipeline is then replayed from scratch. A warp never edits a built
 * park in place: every warped park is a complete fresh solve, so no
 * half-mutated park can exist (the whack-a-mole failure mode recorded on
 * #414 is unrepresentable).
 *
 * ## Where a vector comes from
 *
 * - **Baked** (the shipped game): `WARPS_BY_SEED` below, written by the
 *   offline warp search and checked in. A pool seed that needs no warp has
 *   no entry. This is the ONLY source in the browser.
 * - **`LGP_WARP`** (Node only): a JSON `WarpVector`, for the search itself
 *   and for measurement scripts. Overrides the baked entry entirely when
 *   set, exactly as `LGP_SEED` overrides the seed.
 *
 * With no baked entry and no env override every stream runs at offset 0 and
 * the pipeline is byte-identical to a build of this module's parent commit —
 * that inertness is load-bearing: it is what makes the warp machinery safe
 * to land ahead of the search that uses it.
 */
import { PARK_SEED } from './parkManifest';

export interface WarpVector {
  /**
   * Per-manifest-entry layout stream bump: `layout['dodgems'] = 3` makes the
   * dodgems draw its placement candidates from `restart + 3` while every
   * other entry keeps `restart + 0`. Per-entry streams (parkLayout.ts,
   * issue #241) are what make this a *local* move: no other entry's
   * candidates shift, though later entries still validate against the moved
   * plot, which is the point.
   */
  readonly layout?: Readonly<Record<string, number>>;
  /**
   * Start the whole-park layout restart loop here instead of 0 — the
   * coarsest layout move, re-rolling every entry's arrangement at once.
   */
  readonly layoutRestart?: number;
  /**
   * Rail distances (rounded to the metre, as printed by `LGP_DEBUG_BRIDGE`)
   * of crossing candidates the crossing march must refuse. Banning a site
   * makes `selectSpaced` choose its next-best spacing, which is how the
   * search re-sites a crossing that paths cannot use well.
   */
  readonly banCrossingsAt?: readonly number[];
}

/**
 * Warp vectors the offline search has baked for pool seeds. Regenerated by
 * the warp-search script, never edited by hand; absence means "this seed
 * solves unwarped".
 */
const WARPS_BY_SEED: Readonly<Record<number, WarpVector>> = {
  // Found by scripts/warp-search.mts, 2 Sep 2026, against the level-tier-empty
  // park (measurements/warp-search-2sep-*.jsonl). Gates at time of baking:
  // ratchet-on check:park exit 0 + zero stranded on all four; the
  // unallowanced vitest oracle additionally passed on the two seeds it
  // covers (canonical, 5) — 288 and 326 have no per-seed invariant file
  // (#437). These vectors are meaningless until the level tier is gone:
  // they exist to reconnect the garden pockets the level crossings used to
  // carry.
  20260728: { layout: { ferrisWheel: 2 } },
  5: { layout: { ferrisWheel: 2 } },
  288: { layout: { waterFight: 1 } },
  // First baked as {fountain:1} on check:park evidence alone; the moment
  // seed-326.test.ts existed, that vector went red on ONE invariant the
  // check cannot see (the slide climbing 0.001 m) — the #437 blind spot,
  // measured. Re-searched with the oracle in the loop, 2 Sep 2026:
  // {waterFight:1} passes all 81.
  326: { layout: { waterFight: 1 } },
};

function envWarp(): WarpVector | null {
  try {
    const nodeProcess = (globalThis as { process?: { env?: Record<string, string> } }).process;
    const raw = nodeProcess?.env?.['LGP_WARP'];
    if (!raw) return null;
    return JSON.parse(raw) as WarpVector;
  } catch {
    return null;
  }
}

/** The one vector this park is built with, resolved once at module load. */
export const PARK_WARP: WarpVector = envWarp() ?? WARPS_BY_SEED[PARK_SEED] ?? {};

/** The layout stream bump for one manifest entry (0 when unwarped). */
export function layoutStreamBump(entryId: string): number {
  return PARK_WARP.layout?.[entryId] ?? 0;
}

/** Where the layout's whole-park restart loop starts (0 when unwarped). */
export function layoutRestartBase(): number {
  return PARK_WARP.layoutRestart ?? 0;
}

/** Whether the crossing march must refuse a candidate at this rail distance. */
export function crossingSiteBanned(railDistance: number): boolean {
  const banned = PARK_WARP.banCrossingsAt;
  if (!banned || banned.length === 0) return false;
  return banned.some((d) => Math.abs(d - railDistance) < 0.5);
}
