/**
 * **The park's warp vector** — the decision overrides the warp search found
 * for this seed, applied when the pipeline replays (issue: park-warp solver;
 * Jim's ruling 2 Sep 2026: prefer "park-warping mutations" over blind
 * backtracking).
 *
 * ## What a warp is
 *
 * The procgen pipeline is deterministic in `PARK_SEED` plus a handful of
 * seeded candidate streams. A *warp* perturbs one named decision — "draw the
 * dodgems' layout candidates from restart stream 3 instead of 0" — and the
 * whole pipeline is then replayed from scratch. A warp never edits a built
 * park in place: every warped park is a complete fresh solve, so no
 * half-mutated park can exist (the whack-a-mole failure mode recorded on
 * #414 is unrepresentable).
 *
 * ## Where a vector comes from
 *
 * - **Baked** (the shipped game): `WARPS_BY_SEED` below, written by the
 *   offline warp search and checked in. A pool seed that needs no warp has
 *   no entry. This is the ONLY source in the browser.
 * - **`LGP_WARP`** (Node only): a JSON `WarpVector`, for the search itself
 *   and for measurement scripts. Overrides the baked entry entirely when
 *   set, exactly as `LGP_SEED` overrides the seed.
 *
 * With no baked entry and no env override every stream runs at offset 0 and
 * the pipeline is byte-identical to a build of this module's parent commit —
 * that inertness is load-bearing: it is what makes the warp machinery safe
 * to land ahead of the search that uses it.
 */
import { PARK_SEED } from './parkManifest';

export interface WarpVector {
  /**
   * Per-manifest-entry layout stream bump: `layout['dodgems'] = 3` makes the
   * dodgems draw its placement candidates from `restart + 3` while every
   * other entry keeps `restart + 0`. Per-entry streams (parkLayout.ts,
   * issue #241) are what make this a *local* move: no other entry's
   * candidates shift, though later entries still validate against the moved
   * plot, which is the point.
   */
  readonly layout?: Readonly<Record<string, number>>;
  /**
   * Start the whole-park layout restart loop here instead of 0 — the
   * coarsest layout move, re-rolling every entry's arrangement at once.
   */
  readonly layoutRestart?: number;
  /**
   * Rail distances (rounded to the metre, as printed by `LGP_DEBUG_BRIDGE`)
   * of crossing candidates the crossing march must refuse. Banning a site
   * makes `selectSpaced` choose its next-best spacing, which is how the
   * search re-sites a crossing that paths cannot use well.
   */
  readonly banCrossingsAt?: readonly number[];
}

/**
 * Warp vectors the offline search has baked for pool seeds. Regenerated by
 * the warp-search script, never edited by hand; absence means "this seed
 * solves unwarped".
 *
 * ## Two vintages live here, and the difference matters
 *
 * A vector is only meaningful against the geometry it was searched on, so a
 * change to the geometry invalidates every vector baked before it. There have
 * been two such moments, and each entry below says which vintage it belongs
 * to:
 *
 * - **2 Sep 2026, the level-tier-empty park.** The original bake
 *   (`measurements/warp-search-2sep-*.jsonl`). Gate at the time: ratchet-on
 *   `check:park` exit 0 with zero stranded, plus the unallowanced vitest
 *   oracle on the seeds that have a per-seed invariant file (#437). These
 *   exist to reconnect the garden pockets the level crossings used to carry.
 * - **2 Sep 2026, after the rail route's dead spot was fixed.**
 *   `rail/generate.ts`'s `buildRoute` used to give only the first piece a
 *   `t = 0` stop, so every route answered with the same point for up to
 *   0.35 m at each join. Fixing it moves **every** route slightly, which
 *   re-solves every park, which is exactly the thing a baked vector cannot
 *   survive. Seeds **5, 115 and 326** were re-searched against the fixed
 *   geometry (`measurements/warp-search-2sep-railroute-fix.jsonl`); the other
 *   four were re-vetted and still hold.
 *
 * **If you change the geometry again, the vectors are stale again.** The tell
 * is neither gate on its own, because the three that went stale failed in
 * both directions: 115 was `check:park`-green with three invariants red, 326
 * was invariant-green (81/81) with `check:park` stranding 8. The tell is
 * `pnpm run vet:seeds` over the whole pool, which runs both.
 *
 * And note `check:park` is **canonical-only** — it never builds a pool seed's
 * park at all — while `CI_SWEEP_SEEDS` covers six of the sixteen. So the
 * blocking chain structurally cannot see a stale vector on the other ten, and
 * did not see 326's even though 326 is in the sweep list. See
 * `parkSeedPool.ts`'s note beside `CI_SWEEP_SEEDS`.
 */
/**
 * **Empty, on purpose.** Every entry this held was a baked backtrack for one
 * of the sixteen arbitrary seeds the pool used to contain (20260728, 5, 24,
 * 115, 225, 288, 326, 428 had vectors). Jim, 6 September 2026, retiring those
 * seeds for 0..15: *"just delete any such work."* A seed in 0..15 that needs a
 * warp is a generator that needs fixing (or, once stage 4 lands, a decision the
 * round-robin backtracks on its own) — not a vector to search for and bake.
 * `LGP_WARP` still works for an experiment.
 */
const WARPS_BY_SEED: Readonly<Record<number, WarpVector>> = {
};

function envWarp(): WarpVector | null {
  try {
    const nodeProcess = (globalThis as { process?: { env?: Record<string, string> } }).process;
    const raw = nodeProcess?.env?.['LGP_WARP'];
    if (!raw) return null;
    return JSON.parse(raw) as WarpVector;
  } catch {
    return null;
  }
}

/** The one vector this park is built with, resolved once at module load. */
export const PARK_WARP: WarpVector = envWarp() ?? WARPS_BY_SEED[PARK_SEED] ?? {};

/** The layout stream bump for one manifest entry (0 when unwarped). */
export function layoutStreamBump(entryId: string): number {
  return PARK_WARP.layout?.[entryId] ?? 0;
}

/** Where the layout's whole-park restart loop starts (0 when unwarped). */
export function layoutRestartBase(): number {
  return PARK_WARP.layoutRestart ?? 0;
}

/** Whether the crossing march must refuse a candidate at this rail distance. */
export function crossingSiteBanned(railDistance: number): boolean {
  const banned = PARK_WARP.banCrossingsAt;
  if (!banned || banned.length === 0) return false;
  return banned.some((d) => Math.abs(d - railDistance) < 0.5);
}
