/**
 * **`Math`'s transcendental functions, giving the same bits on every machine.**
 *
 * The park is generated by Node on a Linux x64 CI runner and accepted on an
 * arm64 Mac, and the two disagreed about it. Not by much. On the same Node
 * (26.10.0, V8 14.6.202.34), `Math.sin`, `cos`, `tan`, `atan`, `atan2`, `asin`,
 * `acos`, `exp`, `log`, `pow`, `**`, `sinh`, `tanh` and `expm1` returned
 * different bits for the same input on the two platforms. That is measured,
 * not inferred: `scripts/math-determinism.mts` hashes each function over a
 * fixed sweep, and the park-identity workflow compares the hashes across the
 * two platforms. `sqrt`, `fround`, `hypot`, `cbrt` and `log2` matched.
 *
 * The cause: V8 computes these in C++ (fdlibm, plus glibc's `sin`/`cos`). The
 * arm64 compiler is allowed to fuse `a * b + c` into one fused multiply-add,
 * which rounds once where x64 rounds twice. An ulp is enough. A fairy pole
 * whose clearance came out 1e-16 m either side of its threshold stood
 * somewhere else, and from there seeds 0, 2, 4, 8 and 11 grew different parks.
 *
 * JavaScript's own `+ - * /` are single correctly-rounded IEEE operations on
 * every platform, and V8 never contracts them into a fused multiply-add. So the
 * same fdlibm algorithms written in JavaScript give the same answer
 * everywhere. They are what this file is: line-for-line ports of fdlibm 5.3
 * (Sun Microsystems, freely redistributable; the notice is kept below).
 * Accuracy is fdlibm's own, under 1 ulp. `test/deterministicMath.test.ts`
 * measures that against the native functions.
 *
 * {@link installDeterministicMath} puts them on the global `Math`, so three.js
 * and every module in `src/` use them without being told. It has to run before
 * anything else is evaluated, because a module-level constant computed with
 * the native function keeps that value. It is installed by
 * `scripts/ts-extension-resolver-register.mjs` for Node scripts, by
 * `test/setupDeterministicMath.ts` for vitest, and by the first import of
 * `main.ts` (and of each art-sample page) in the browser. That last one holds
 * in a production build only because `vite.config.ts` sets
 * `strictExecutionOrder`: by default the bundler evaluates the chunks an entry
 * imports before the entry itself, and `parkManifest.ts` sits in one of them,
 * so the first production build after this change refused to boot. {@link assertDeterministicMath}, called when
 * `parkManifest.ts` loads, refuses to generate a park without them.
 *
 * Not covered: the `**` operator. V8 compiles it to its native pow, and
 * nothing can intercept it. It is exact for integer powers up to 2 (`x ** 2 ===
 * x * x` everywhere); any other exponent belongs in `Math.pow`.
 *
 * One departure from fdlibm's code, not its answers: for |x| above 2^19·π/2
 * (about 823,550) the trig argument reduction is done exactly in BigInt
 * ({@link remPio2Large}) rather than by porting `__kernel_rem_pio2`.
 *
 * ====================================================
 * Copyright (C) 1993 by Sun Microsystems, Inc. All rights reserved.
 *
 * Developed at SunPro, a Sun Microsystems, Inc. business.
 * Permission to use, copy, modify, and distribute this
 * software is freely granted, provided that this notice
 * is preserved.
 * ====================================================
 */

// ---------------------------------------------------------------------------
// Word access. Little-endian is asserted below: every platform this runs on is.

const f64 = new Float64Array(1);
const u32 = new Uint32Array(f64.buffer);
const i32 = new Int32Array(f64.buffer);
f64[0] = 1;
if (i32[1] !== 0x3ff00000) throw new Error('deterministicMath: expected a little-endian platform');

/** The high word, signed — fdlibm's `__HI(x)`. */
const hiWord = (x: number): number => {
  f64[0] = x;
  return i32[1]!;
};
/** The low word, unsigned — fdlibm's `__LO(x)`. */
const loWord = (x: number): number => {
  f64[0] = x;
  return u32[0]!;
};
const fromWords = (hi: number, lo: number): number => {
  i32[1] = hi;
  u32[0] = lo;
  return f64[0]!;
};
/** `x` with its low word cleared — fdlibm's `__LO(x) = 0`. */
const clearLow = (x: number): number => {
  f64[0] = x;
  u32[0] = 0;
  return f64[0]!;
};
const withHigh = (x: number, hi: number): number => {
  f64[0] = x;
  i32[1] = hi;
  return f64[0]!;
};

// Captured once, before anything is installed: `sqrt` and `abs` are exact on
// every platform, so the ports use the native ones.
const nativeSqrt = Math.sqrt;
const fabs = Math.abs;

const huge = 1.0e300;
const tiny = 1.0e-300;

// ---------------------------------------------------------------------------
// Trigonometric kernels, valid on [-π/4, π/4].

const S1 = -1.66666666666666324348e-1;
const S2 = 8.33333333332248946124e-3;
const S3 = -1.98412698298579493134e-4;
const S4 = 2.75573137070700676789e-6;
const S5 = -2.50507602534068634195e-8;
const S6 = 1.58969099521155010221e-10;

function kernelSin(x: number, y: number, iy: number): number {
  const ix = hiWord(x) & 0x7fffffff;
  if (ix < 0x3e400000 && Math.trunc(x) === 0) return x;
  const z = x * x;
  const v = z * x;
  const r = S2 + z * (S3 + z * (S4 + z * (S5 + z * S6)));
  if (iy === 0) return x + v * (S1 + z * r);
  return x - ((z * (0.5 * y - v * r) - y) - v * S1);
}

const C1 = 4.16666666666666019037e-2;
const C2 = -1.38888888888741095749e-3;
const C3 = 2.48015872894767294178e-5;
const C4 = -2.75573143513906633035e-7;
const C5 = 2.08757232129817482790e-9;
const C6 = -1.13596475577881948265e-11;

function kernelCos(x: number, y: number): number {
  const ix = hiWord(x) & 0x7fffffff;
  if (ix < 0x3e400000 && Math.trunc(x) === 0) return 1;
  const z = x * x;
  const r = z * (C1 + z * (C2 + z * (C3 + z * (C4 + z * (C5 + z * C6)))));
  if (ix < 0x3fd33333) return 1 - (0.5 * z - (z * r - x * y));
  const qx = ix > 0x3fe90000 ? 0.28125 : fromWords(ix - 0x00200000, 0);
  const hz = 0.5 * z - qx;
  const a = 1 - qx;
  return a - (hz - (z * r - x * y));
}

const T = [
  3.33333333333334091986e-1, 1.33333333333201242699e-1, 5.39682539762260521377e-2, 2.18694882948595424599e-2,
  8.86323982359930005737e-3, 3.59207910759131235356e-3, 1.45620945432529025516e-3, 5.88041240820264096874e-4,
  2.46463134818469906812e-4, 7.81794442939557092300e-5, 7.14072491382608190305e-5, -1.85586374855275456654e-5,
  2.59073051863633712884e-5,
] as const;
const pio4 = 7.85398163397448278999e-1;
const pio4lo = 3.06161699786838301793e-17;

function kernelTan(xIn: number, yIn: number, iy: number): number {
  let x = xIn;
  let y = yIn;
  const hx = hiWord(x);
  const ix = hx & 0x7fffffff;
  if (ix < 0x3e300000 && Math.trunc(x) === 0) {
    if (((ix | loWord(x)) | (iy + 1)) === 0) return 1 / fabs(x);
    if (iy === 1) return x;
    // -1 / (x + y), computed carefully.
    const w = x + y;
    const z = clearLow(w);
    const v = y - (z - x);
    const a = -1 / w;
    const t = clearLow(a);
    const s = 1 + t * z;
    return t + a * (s + t * v);
  }
  if (ix >= 0x3fe59428) {
    if (hx < 0) {
      x = -x;
      y = -y;
    }
    const z = pio4 - x;
    const w = pio4lo - y;
    x = z + w;
    y = 0;
  }
  let z = x * x;
  let w = z * z;
  let r = T[1] + w * (T[3] + w * (T[5] + w * (T[7] + w * (T[9] + w * T[11]))));
  let v = z * (T[2] + w * (T[4] + w * (T[6] + w * (T[8] + w * (T[10] + w * T[12])))));
  const s = z * x;
  r = y + z * (s * (r + v) + y);
  r += T[0] * s;
  w = x + r;
  if (ix >= 0x3fe59428) {
    v = iy;
    return (1 - ((hx >> 30) & 2)) * (v - 2.0 * (x - ((w * w) / (w + v) - r)));
  }
  if (iy === 1) return w;
  z = clearLow(w);
  v = r - (z - x);
  const a = -1.0 / w;
  const t = clearLow(a);
  const s2 = 1.0 + t * z;
  return t + a * (s2 + t * v);
}

// ---------------------------------------------------------------------------
// Argument reduction: x = n·π/2 + (y0 + y1), |y0 + y1| <= π/4.

const invpio2 = 6.36619772367581382433e-1;
const pio2_1 = 1.57079632673412561417e0;
const pio2_1t = 6.07710050650619224932e-11;
const pio2_2 = 6.07710050630396597660e-11;
const pio2_2t = 2.02226624879595063154e-21;
const pio2_3 = 2.02226624871116645580e-21;
const pio2_3t = 8.47842766036889956997e-32;

/** The reduced argument, written here rather than allocated per call. */
let y0 = 0;
let y1 = 0;

/** Returns the quadrant, 0..3; the reduced argument is left in {@link y0}, {@link y1}. */
function remPio2(x: number): number {
  const hx = hiWord(x);
  const ix = hx & 0x7fffffff;
  if (ix <= 0x3fe921fb) {
    y0 = x;
    y1 = 0;
    return 0;
  }
  if (ix < 0x4002d97c) {
    // |x| < 3π/4: one subtraction of π/2.
    if (hx > 0) {
      let z = x - pio2_1;
      if (ix !== 0x3ff921fb) {
        y0 = z - pio2_1t;
        y1 = (z - y0) - pio2_1t;
      } else {
        z -= pio2_2;
        y0 = z - pio2_2t;
        y1 = (z - y0) - pio2_2t;
      }
      return 1;
    }
    let z = x + pio2_1;
    if (ix !== 0x3ff921fb) {
      y0 = z + pio2_1t;
      y1 = (z - y0) + pio2_1t;
    } else {
      z += pio2_2;
      y0 = z + pio2_2t;
      y1 = (z - y0) + pio2_2t;
    }
    return 3;
  }
  if (ix >= 0x7ff00000) {
    y0 = x - x;
    y1 = y0;
    return 0;
  }
  if (ix > 0x413921fb) return remPio2Large(x, hx);
  // Cody–Waite in three parts, always taking fdlibm's careful branch (the
  // `npio2_hw` shortcut only skips work, never changes a well-conditioned
  // answer).
  const t0 = fabs(x);
  const fn = Math.floor(t0 * invpio2 + 0.5);
  let r = t0 - fn * pio2_1;
  let w = fn * pio2_1t;
  const j = ix >> 20;
  y0 = r - w;
  let i = j - ((hiWord(y0) >> 20) & 0x7ff);
  if (i > 16) {
    let t = r;
    w = fn * pio2_2;
    r = t - w;
    w = fn * pio2_2t - ((t - r) - w);
    y0 = r - w;
    i = j - ((hiWord(y0) >> 20) & 0x7ff);
    if (i > 49) {
      t = r;
      w = fn * pio2_3;
      r = t - w;
      w = fn * pio2_3t - ((t - r) - w);
      y0 = r - w;
    }
  }
  y1 = (r - y0) - w;
  const n = fn % 4;
  if (hx < 0) {
    y0 = -y0;
    y1 = -y1;
    return (4 - n) % 4;
  }
  return n;
}

/**
 * 2/π and π/2 as fixed-point integers, derived once from Machin's formula
 * rather than copied from a table: `TWO_OVER_PI` is ⌊2/π · 2^PREC⌋, and
 * `PIO2_128` is ⌊π/2 · 2^128⌋. 1300 bits covers every finite double: the
 * reduction needs the fraction of x·2/π to ~2^-130, and x reaches 2^1024.
 */
const PREC = 1300n;
const { TWO_OVER_PI, PIO2_128 } = (() => {
  const guard = 64n;
  const one = 1n << (PREC + guard);
  const arctanInv = (k: bigint): bigint => {
    // arctan(1/k) = Σ (-1)^n / ((2n+1) k^(2n+1))
    let term = one / k;
    let sum = term;
    const k2 = k * k;
    for (let n = 1n; term !== 0n; n += 1n) {
      term /= k2;
      sum += (n & 1n ? -term : term) / (2n * n + 1n);
    }
    return sum;
  };
  const piFixed = 16n * arctanInv(5n) - 4n * arctanInv(239n); // π · 2^(PREC+guard)
  return {
    TWO_OVER_PI: ((2n << (2n * (PREC + guard))) / piFixed) >> guard,
    PIO2_128: piFixed >> (PREC + guard - 127n),
  };
})();

/**
 * Payne–Hanek-style reduction for |x| > 2^19·π/2, done exactly with BigInt in
 * place of fdlibm's `__kernel_rem_pio2`. Same contract as {@link remPio2}.
 */
function remPio2Large(x: number, hx: number): number {
  // |x| = m · 2^e exactly, m a 53-bit integer.
  const ax = fabs(x);
  const biasedExp = (hiWord(ax) >> 20) & 0x7ff;
  const m = BigInt((hiWord(ax) & 0x000fffff) | 0x00100000) * 0x100000000n + BigInt(loWord(ax));
  const e = BigInt(biasedExp - 1075);
  // x · 2/π = m · TWO_OVER_PI · 2^(e - PREC)
  const product = m * TWO_OVER_PI;
  const shift = PREC - e;
  let quadrant = Number((product >> shift) & 3n);
  // The top 128 bits of the fraction, rounded to the nearest quadrant.
  let frac = (product & ((1n << shift) - 1n)) >> (shift - 128n);
  if (frac >= 1n << 127n) {
    frac -= 1n << 128n;
    quadrant = (quadrant + 1) & 3;
  }
  // r = frac/2^128 · π/2 = big / 2^256, split into two doubles.
  const big = frac * PIO2_128;
  const scale = fromWords((1023 - 256) << 20, 0); // 2^-256, exactly
  const hi = Number(big);
  y0 = hi * scale;
  const rest = big - BigInt(hi);
  y1 = Number(rest) * scale;
  if (hx < 0) {
    y0 = -y0;
    y1 = -y1;
    return (4 - quadrant) & 3;
  }
  return quadrant;
}

export function sin(x: number): number {
  const ix = hiWord(x) & 0x7fffffff;
  if (ix <= 0x3fe921fb) return kernelSin(x, 0, 0);
  if (ix >= 0x7ff00000) return x - x;
  switch (remPio2(x)) {
    case 0:
      return kernelSin(y0, y1, 1);
    case 1:
      return kernelCos(y0, y1);
    case 2:
      return -kernelSin(y0, y1, 1);
    default:
      return -kernelCos(y0, y1);
  }
}

export function cos(x: number): number {
  const ix = hiWord(x) & 0x7fffffff;
  if (ix <= 0x3fe921fb) return kernelCos(x, 0);
  if (ix >= 0x7ff00000) return x - x;
  switch (remPio2(x)) {
    case 0:
      return kernelCos(y0, y1);
    case 1:
      return -kernelSin(y0, y1, 1);
    case 2:
      return -kernelCos(y0, y1);
    default:
      return kernelSin(y0, y1, 1);
  }
}

export function tan(x: number): number {
  const ix = hiWord(x) & 0x7fffffff;
  if (ix <= 0x3fe921fb) return kernelTan(x, 0, 1);
  if (ix >= 0x7ff00000) return x - x;
  const n = remPio2(x);
  return kernelTan(y0, y1, 1 - ((n & 1) << 1));
}

// ---------------------------------------------------------------------------
// Inverse trigonometric functions.

const atanhi = [4.63647609000806093515e-1, 7.85398163397448278999e-1, 9.82793723247329054082e-1, 1.57079632679489655800e0] as const;
const atanlo = [2.26987774529616870924e-17, 3.06161699786838301793e-17, 1.39033110312309984516e-17, 6.12323399573676603587e-17] as const;
const aT = [
  3.33333333333329318027e-1, -1.99999999998764832476e-1, 1.42857142725034663711e-1, -1.11111104054623557880e-1,
  9.09088713343650656196e-2, -7.69187620504482999495e-2, 6.66107313738753120669e-2, -5.83357013379057348645e-2,
  4.97687799461593236017e-2, -3.65315727442169155270e-2, 1.62858201153657823623e-2,
] as const;

export function atan(xIn: number): number {
  let x = xIn;
  const hx = hiWord(x);
  const ix = hx & 0x7fffffff;
  let id: number;
  if (ix >= 0x44100000) {
    // |x| >= 2^66
    if (x !== x) return x + x;
    return hx > 0 ? atanhi[3] + atanlo[3] : -atanhi[3] - atanlo[3];
  }
  if (ix < 0x3fdc0000) {
    // |x| < 0.4375
    if (ix < 0x3e200000 && huge + x > 1) return x;
    id = -1;
  } else {
    x = fabs(x);
    if (ix < 0x3ff30000) {
      if (ix < 0x3fe60000) {
        id = 0;
        x = (2.0 * x - 1) / (2.0 + x);
      } else {
        id = 1;
        x = (x - 1) / (x + 1);
      }
    } else if (ix < 0x40038000) {
      id = 2;
      x = (x - 1.5) / (1 + 1.5 * x);
    } else {
      id = 3;
      x = -1.0 / x;
    }
  }
  const z = x * x;
  const w = z * z;
  const s1 = z * (aT[0] + w * (aT[2] + w * (aT[4] + w * (aT[6] + w * (aT[8] + w * aT[10])))));
  const s2 = w * (aT[1] + w * (aT[3] + w * (aT[5] + w * (aT[7] + w * aT[9]))));
  if (id < 0) return x - x * (s1 + s2);
  const r = atanhi[id as 0]! - ((x * (s1 + s2) - atanlo[id as 0]!) - x);
  return hx < 0 ? -r : r;
}

const pi_o_4 = 7.8539816339744827900e-1;
const pi_o_2 = 1.5707963267948965580e0;
const pi = 3.1415926535897931160e0;
const pi_lo = 1.2246467991473531772e-16;

export function atan2(y: number, x: number): number {
  if (x !== x || y !== y) return x + y;
  const hx = hiWord(x);
  const ix = hx & 0x7fffffff;
  const lx = loWord(x);
  const hy = hiWord(y);
  const iy = hy & 0x7fffffff;
  const ly = loWord(y);
  if (hx === 0x3ff00000 && lx === 0) return atan(y); // x = 1.0
  let m = ((hy >> 31) & 1) | ((hx >> 30) & 2);
  if ((iy | ly) === 0) {
    switch (m) {
      case 0:
      case 1:
        return y;
      case 2:
        return pi + tiny;
      default:
        return -pi - tiny;
    }
  }
  if ((ix | lx) === 0) return hy < 0 ? -pi_o_2 - tiny : pi_o_2 + tiny;
  if (ix === 0x7ff00000) {
    if (iy === 0x7ff00000) {
      switch (m) {
        case 0:
          return pi_o_4 + tiny;
        case 1:
          return -pi_o_4 - tiny;
        case 2:
          return 3.0 * pi_o_4 + tiny;
        default:
          return -3.0 * pi_o_4 - tiny;
      }
    }
    switch (m) {
      case 0:
        return 0;
      case 1:
        return -0;
      case 2:
        return pi + tiny;
      default:
        return -pi - tiny;
    }
  }
  if (iy === 0x7ff00000) return hy < 0 ? -pi_o_2 - tiny : pi_o_2 + tiny;
  const k = (iy - ix) >> 20;
  let z: number;
  if (k > 60) {
    z = pi_o_2 + 0.5 * pi_lo;
    m &= 1;
  } else if (hx < 0 && k < -60) {
    z = 0.0;
  } else {
    z = atan(fabs(y / x));
  }
  switch (m) {
    case 0:
      return z;
    case 1:
      return -z;
    case 2:
      return pi - (z - pi_lo);
    default:
      return (z - pi_lo) - pi;
  }
}

const pio2_hi = 1.57079632679489655800e0;
const pio2_lo = 6.12323399573676603587e-17;
const pio4_hi = 7.85398163397448278999e-1;
const pS0 = 1.66666666666666657415e-1;
const pS1 = -3.25565818622400915405e-1;
const pS2 = 2.01212532134862925881e-1;
const pS3 = -4.00555345006794114027e-2;
const pS4 = 7.91534994289814532176e-4;
const pS5 = 3.47933107596021167570e-5;
const qS1 = -2.40339491173441421878e0;
const qS2 = 2.02094576023350569471e0;
const qS3 = -6.88283971605453293030e-1;
const qS4 = 7.70381505559019352791e-2;

const asinP = (t: number): number => t * (pS0 + t * (pS1 + t * (pS2 + t * (pS3 + t * (pS4 + t * pS5)))));
const asinQ = (t: number): number => 1 + t * (qS1 + t * (qS2 + t * (qS3 + t * qS4)));

export function asin(x: number): number {
  const hx = hiWord(x);
  const ix = hx & 0x7fffffff;
  if (ix >= 0x3ff00000) {
    if (((ix - 0x3ff00000) | loWord(x)) === 0) return x * pio2_hi + x * pio2_lo;
    return (x - x) / (x - x);
  }
  if (ix < 0x3fe00000) {
    if (ix < 0x3e400000 && huge + x > 1) return x;
    const t = x * x;
    return x + x * (asinP(t) / asinQ(t));
  }
  const w0 = 1 - fabs(x);
  const t = w0 * 0.5;
  let p = asinP(t);
  let q = asinQ(t);
  const s = nativeSqrt(t);
  let r: number;
  if (ix >= 0x3fef3333) {
    const w = p / q;
    r = pio2_hi - (2.0 * (s + s * w) - pio2_lo);
  } else {
    const w = clearLow(s);
    const c = (t - w * w) / (s + w);
    const rr = p / q;
    p = 2.0 * s * rr - (pio2_lo - 2.0 * c);
    q = pio4_hi - 2.0 * w;
    r = pio4_hi - (p - q);
  }
  return hx > 0 ? r : -r;
}

export function acos(x: number): number {
  const hx = hiWord(x);
  const ix = hx & 0x7fffffff;
  if (ix >= 0x3ff00000) {
    if (((ix - 0x3ff00000) | loWord(x)) === 0) return hx > 0 ? 0.0 : pi + 2.0 * pio2_lo;
    return (x - x) / (x - x);
  }
  if (ix < 0x3fe00000) {
    if (ix <= 0x3c600000) return pio2_hi + pio2_lo;
    const z = x * x;
    const r = asinP(z) / asinQ(z);
    return pio2_hi - (x - (pio2_lo - x * r));
  }
  if (hx < 0) {
    const z = (1 + x) * 0.5;
    const s = nativeSqrt(z);
    const r = asinP(z) / asinQ(z);
    const w = r * s - pio2_lo;
    return pi - 2.0 * (s + w);
  }
  const z = (1 - x) * 0.5;
  const s = nativeSqrt(z);
  const df = clearLow(s);
  const c = (z - df * df) / (s + df);
  const r = asinP(z) / asinQ(z);
  const w = r * s + c;
  return 2.0 * (df + w);
}

// ---------------------------------------------------------------------------
// Exponential and logarithm.

const o_threshold = 7.09782712893383973096e2;
const u_threshold = -7.45133219101941108420e2;
const ln2_hi = 6.93147180369123816490e-1;
const ln2_lo = 1.90821492927058770002e-10;
const invln2 = 1.44269504088896338700e0;
const P1 = 1.66666666666666019037e-1;
const P2 = -2.77777777770155933842e-3;
const P3 = 6.61375632143793436117e-5;
const P4 = -1.65339022054652515390e-6;
const P5 = 4.13813679705723846039e-8;
const twom1000 = 9.33263618503218878990e-302;

export function exp(xIn: number): number {
  let x = xIn;
  let hx = hiWord(x);
  const xsb = (hx >> 31) & 1;
  hx &= 0x7fffffff;
  if (hx >= 0x40862e42) {
    // |x| >= 709.78...
    if (hx >= 0x7ff00000) {
      if (((hx & 0xfffff) | loWord(x)) !== 0) return x + x;
      return xsb === 0 ? x : 0.0;
    }
    if (x > o_threshold) return Infinity;
    if (x < u_threshold) return 0;
  }
  let hi = 0;
  let lo = 0;
  let k = 0;
  if (hx > 0x3fd62e42) {
    // |x| > 0.5 ln2
    if (hx < 0x3ff0a2b2) {
      hi = xsb === 0 ? x - ln2_hi : x + ln2_hi;
      lo = xsb === 0 ? ln2_lo : -ln2_lo;
      k = 1 - xsb - xsb;
    } else {
      k = Math.trunc(invln2 * x + (xsb === 0 ? 0.5 : -0.5));
      hi = x - k * ln2_hi;
      lo = k * ln2_lo;
    }
    x = hi - lo;
  } else if (hx < 0x3e300000) {
    if (huge + x > 1) return 1 + x;
  }
  const t = x * x;
  const c = x - t * (P1 + t * (P2 + t * (P3 + t * (P4 + t * P5))));
  if (k === 0) return 1 - ((x * c) / (c - 2.0) - x);
  const y = 1 - ((lo - (x * c) / (2.0 - c)) - hi);
  if (k >= -1021) return withHigh(y, hiWord(y) + (k << 20));
  return withHigh(y, hiWord(y) + ((k + 1000) << 20)) * twom1000;
}

const two54 = 1.80143985094819840000e16;
const Lg1 = 6.666666666666735130e-1;
const Lg2 = 3.999999999940941908e-1;
const Lg3 = 2.857142874366239149e-1;
const Lg4 = 2.222219843214978396e-1;
const Lg5 = 1.818357216161805012e-1;
const Lg6 = 1.531383769920937332e-1;
const Lg7 = 1.479819860511658591e-1;

export function log(xIn: number): number {
  let x = xIn;
  let hx = hiWord(x);
  const lx = loWord(x);
  let k = 0;
  if (hx < 0x00100000) {
    if (((hx & 0x7fffffff) | lx) === 0) return -Infinity;
    if (hx < 0) return NaN;
    k -= 54;
    x *= two54;
    hx = hiWord(x);
  }
  if (hx >= 0x7ff00000) return x + x;
  k += (hx >> 20) - 1023;
  hx &= 0x000fffff;
  let i = (hx + 0x95f64) & 0x100000;
  x = withHigh(x, hx | (i ^ 0x3ff00000));
  k += i >> 20;
  const f = x - 1.0;
  if ((0x000fffff & (2 + hx)) < 3) {
    if (f === 0) {
      if (k === 0) return 0;
      return k * ln2_hi + k * ln2_lo;
    }
    const R = f * f * (0.5 - 0.33333333333333333 * f);
    if (k === 0) return f - R;
    return k * ln2_hi - ((R - k * ln2_lo) - f);
  }
  const s = f / (2.0 + f);
  const dk = k;
  const z = s * s;
  i = hx - 0x6147a;
  const w = z * z;
  const j = 0x6b851 - hx;
  const t1 = w * (Lg2 + w * (Lg4 + w * Lg6));
  const t2 = z * (Lg1 + w * (Lg3 + w * (Lg5 + w * Lg7)));
  i |= j;
  const R = t2 + t1;
  if (i > 0) {
    const hfsq = 0.5 * f * f;
    if (k === 0) return f - (hfsq - s * (hfsq + R));
    return dk * ln2_hi - ((hfsq - (s * (hfsq + R) + dk * ln2_lo)) - f);
  }
  if (k === 0) return f - s * (f - R);
  return dk * ln2_hi - ((s * (f - R) - dk * ln2_lo) - f);
}

const Q1 = -3.33333333333331316428e-2;
const Q2 = 1.58730158725481460165e-3;
const Q3 = -7.93650757867487942473e-5;
const Q4 = 4.00821782732936239552e-6;
const Q5 = -2.01099218183624371326e-7;

export function expm1(xIn: number): number {
  let x = xIn;
  let hx = hiWord(x);
  const xsb = hx & 0x80000000;
  hx &= 0x7fffffff;
  if (hx >= 0x4043687a) {
    // |x| >= 56 ln2
    if (hx >= 0x40862e42) {
      if (hx >= 0x7ff00000) {
        if (((hx & 0xfffff) | loWord(x)) !== 0) return x + x;
        return xsb === 0 ? x : -1.0;
      }
      if (x > o_threshold) return Infinity;
    }
    if (xsb !== 0 && x + tiny < 0.0) return tiny - 1;
  }
  let k: number;
  let c = 0;
  if (hx > 0x3fd62e42) {
    let hi: number;
    let lo: number;
    if (hx < 0x3ff0a2b2) {
      if (xsb === 0) {
        hi = x - ln2_hi;
        lo = ln2_lo;
        k = 1;
      } else {
        hi = x + ln2_hi;
        lo = -ln2_lo;
        k = -1;
      }
    } else {
      k = Math.trunc(invln2 * x + (xsb === 0 ? 0.5 : -0.5));
      hi = x - k * ln2_hi;
      lo = k * ln2_lo;
    }
    x = hi - lo;
    c = (hi - x) - lo;
  } else if (hx < 0x3c900000) {
    const t = huge + x;
    return x - (t - (huge + x));
  } else {
    k = 0;
  }
  const hfx = 0.5 * x;
  const hxs = x * hfx;
  const r1 = 1 + hxs * (Q1 + hxs * (Q2 + hxs * (Q3 + hxs * (Q4 + hxs * Q5))));
  const t = 3.0 - r1 * hfx;
  let e = hxs * ((r1 - t) / (6.0 - x * t));
  if (k === 0) return x - (x * e - hxs);
  e = x * (e - c) - c;
  e -= hxs;
  if (k === -1) return 0.5 * (x - e) - 0.5;
  if (k === 1) {
    if (x < -0.25) return -2.0 * (e - (x + 0.5));
    return 1 + 2.0 * (x - e);
  }
  if (k <= -2 || k > 56) {
    const y = 1 - (e - x);
    return withHigh(y, hiWord(y) + (k << 20)) - 1;
  }
  if (k < 20) {
    const tt = fromWords(0x3ff00000 - (0x200000 >> k), 0);
    const y = tt - (e - x);
    return withHigh(y, hiWord(y) + (k << 20));
  }
  const tt = fromWords((0x3ff - k) << 20, 0);
  let y = x - (e + tt);
  y += 1;
  return withHigh(y, hiWord(y) + (k << 20));
}

// ---------------------------------------------------------------------------
// pow

const bp = [1.0, 1.5] as const;
const dp_h = [0.0, 5.84962487220764160156e-1] as const;
const dp_l = [0.0, 1.35003920212974897128e-8] as const;
const two53 = 9007199254740992.0;
const L1 = 5.99999999999994648725e-1;
const L2 = 4.28571428578550184252e-1;
const L3 = 3.33333329818377432918e-1;
const L4 = 2.72728123808534006489e-1;
const L5 = 2.30660745775561754067e-1;
const L6 = 2.06975017800338417784e-1;
const lg2 = 6.93147180559945286227e-1;
const lg2_h = 6.93147182464599609375e-1;
const lg2_l = -1.90465429995776804525e-9;
const ovt = 8.0085662595372944372e-17;
const cp = 9.61796693925975554329e-1;
const cp_h = 9.61796700954437255859e-1;
const cp_l = -7.02846165095275826516e-9;
const ivln2 = 1.44269504088896338700e0;
const ivln2_h = 1.44269502162933349609e0;
const ivln2_l = 1.92596299112661746887e-8;

/** `x · 2^n`, deterministic (exact unless the result is subnormal). */
function scalbn(x: number, n: number): number {
  let r = x;
  let m = n;
  while (m > 1023) {
    r *= fromWords(0x7fe00000, 0);
    m -= 1023;
  }
  while (m < -1022) {
    r *= fromWords(0x00100000, 0);
    m += 1022;
  }
  return r * fromWords((m + 1023) << 20, 0);
}

export function pow(x: number, y: number): number {
  const hx = hiWord(x);
  const lx = loWord(x);
  const hy = hiWord(y);
  const ly = loWord(y);
  let ix = hx & 0x7fffffff;
  const iy = hy & 0x7fffffff;

  if ((iy | ly) === 0) return 1;
  // JavaScript, unlike C99: 1 ** NaN and 1 ** ±Infinity are NaN.
  if (x !== x || y !== y) return NaN;

  // yisint: 0 not an integer, 1 odd, 2 even — only needed for x < 0.
  let yisint = 0;
  if (hx < 0) {
    if (iy >= 0x43400000) yisint = 2;
    else if (iy >= 0x3ff00000) {
      const k = (iy >> 20) - 0x3ff;
      if (k > 20) {
        const j = ly >>> (52 - k);
        if (((j << (52 - k)) >>> 0) === ly) yisint = 2 - (j & 1);
      } else if (ly === 0) {
        const j = iy >> (20 - k);
        if (j << (20 - k) === iy) yisint = 2 - (j & 1);
      }
    }
  }

  if (ly === 0) {
    if (iy === 0x7ff00000) {
      if (((ix - 0x3ff00000) | lx) === 0) return NaN; // ±1 ** ±Infinity
      if (ix >= 0x3ff00000) return hy >= 0 ? y : 0;
      return hy < 0 ? -y : 0;
    }
    if (iy === 0x3ff00000) return hy < 0 ? 1 / x : x;
    if (hy === 0x40000000) return x * x;
    if (hy === 0x3fe00000 && hx >= 0) return nativeSqrt(x);
  }

  let ax = fabs(x);
  if (lx === 0 && (ix === 0x7ff00000 || ix === 0 || ix === 0x3ff00000)) {
    let z = ax;
    if (hy < 0) z = 1 / z;
    if (hx < 0) {
      if (((ix - 0x3ff00000) | yisint) === 0) z = NaN;
      else if (yisint === 1) z = -z;
    }
    return z;
  }

  let n = (hx >> 31) + 1;
  if ((n | yisint) === 0) return NaN;
  let s = 1;
  if ((n | (yisint - 1)) === 0) s = -1;

  let t1: number;
  let t2: number;
  if (iy > 0x41e00000) {
    // |y| > 2^31
    if (iy > 0x43f00000) {
      if (ix <= 0x3fefffff) return hy < 0 ? huge * huge : tiny * tiny;
      if (ix >= 0x3ff00000) return hy > 0 ? huge * huge : tiny * tiny;
    }
    if (ix < 0x3fefffff) return hy < 0 ? s * huge * huge : s * tiny * tiny;
    if (ix > 0x3ff00000) return hy > 0 ? s * huge * huge : s * tiny * tiny;
    const t = ax - 1;
    const w = t * t * (0.5 - t * (0.3333333333333333333333 - t * 0.25));
    const u = ivln2_h * t;
    const v = t * ivln2_l - w * ivln2;
    t1 = clearLow(u + v);
    t2 = v - (t1 - u);
  } else {
    n = 0;
    if (ix < 0x00100000) {
      ax *= two53;
      n -= 53;
      ix = hiWord(ax);
    }
    n += (ix >> 20) - 0x3ff;
    const j = ix & 0x000fffff;
    let k: 0 | 1;
    ix = j | 0x3ff00000;
    if (j <= 0x3988e) k = 0;
    else if (j < 0xbb67a) k = 1;
    else {
      k = 0;
      n += 1;
      ix -= 0x00100000;
    }
    ax = withHigh(ax, ix);

    const u0 = ax - bp[k];
    const v0 = 1 / (ax + bp[k]);
    const ss = u0 * v0;
    const s_h = clearLow(ss);
    let t_h = fromWords(((ix >> 1) | 0x20000000) + 0x00080000 + (k << 18), 0);
    let t_l = ax - (t_h - bp[k]);
    const s_l = v0 * ((u0 - s_h * t_h) - s_h * t_l);
    let s2 = ss * ss;
    let r = s2 * s2 * (L1 + s2 * (L2 + s2 * (L3 + s2 * (L4 + s2 * (L5 + s2 * L6)))));
    r += s_l * (s_h + ss);
    s2 = s_h * s_h;
    t_h = clearLow(3.0 + s2 + r);
    t_l = r - ((t_h - 3.0) - s2);
    const u = s_h * t_h;
    const v = s_l * t_h + t_l * ss;
    const p_h = clearLow(u + v);
    const p_l = v - (p_h - u);
    const z_h = cp_h * p_h;
    const z_l = cp_l * p_h + p_l * cp + dp_l[k];
    const t = n;
    t1 = clearLow(((z_h + z_l) + dp_h[k]) + t);
    t2 = z_l - (((t1 - t) - dp_h[k]) - z_h);
  }

  // (y1 + y2) · (t1 + t2)
  const yy1 = clearLow(y);
  const p_l = (y - yy1) * t1 + y * t2;
  let p_h = yy1 * t1;
  let z = p_l + p_h;
  let j = hiWord(z);
  let i = loWord(z);
  if (j >= 0x40900000) {
    if (j !== 0x40900000 || i !== 0) return s * huge * huge;
    if (p_l + ovt > z - p_h) return s * huge * huge;
  } else if ((j & 0x7fffffff) >= 0x4090cc00) {
    if ((j >>> 0) !== 0xc090cc00 || i !== 0) return s * tiny * tiny;
    if (p_l <= z - p_h) return s * tiny * tiny;
  }

  // 2^(p_h + p_l)
  i = j & 0x7fffffff;
  let k = (i >> 20) - 0x3ff;
  n = 0;
  if (i > 0x3fe00000) {
    n = j + (0x00100000 >> (k + 1));
    k = ((n & 0x7fffffff) >> 20) - 0x3ff;
    const t = fromWords(n & ~(0x000fffff >> k), 0);
    n = ((n & 0x000fffff) | 0x00100000) >> (20 - k);
    if (j < 0) n = -n;
    p_h -= t;
  }
  const t = clearLow(p_l + p_h);
  const u = t * lg2_h;
  const v = (p_l - (t - p_h)) * lg2 + t * lg2_l;
  z = u + v;
  const w = v - (z - u);
  const tt = z * z;
  const tt1 = z - tt * (P1 + tt * (P2 + tt * (P3 + tt * (P4 + tt * P5))));
  const r = (z * tt1) / (tt1 - 2) - (w + z * w);
  z = 1 - (r - z);
  j = hiWord(z);
  j += n << 20;
  if (j >> 20 <= 0) z = scalbn(z, n);
  else z = withHigh(z, j);
  return s * z;
}

// ---------------------------------------------------------------------------
// Hyperbolic functions, built on exp and expm1.

export function sinh(x: number): number {
  const hx = hiWord(x);
  const ix = hx & 0x7fffffff;
  if (ix >= 0x7ff00000) return x + x;
  const h = hx < 0 ? -0.5 : 0.5;
  if (ix < 0x40360000) {
    // |x| < 22
    if (ix < 0x3e300000 && 1.0e307 + x > 1) return x;
    const t = expm1(fabs(x));
    if (ix < 0x3ff00000) return h * (2.0 * t - (t * t) / (t + 1));
    return h * (t + t / (t + 1));
  }
  if (ix < 0x40862e42) return h * exp(fabs(x));
  if (ix < 0x408633ce || (ix === 0x408633ce && loWord(x) <= 0x8fb9f87d)) {
    const w = exp(0.5 * fabs(x));
    const t = h * w;
    return t * w;
  }
  return x * 1.0e307;
}

export function cosh(x: number): number {
  const ix = hiWord(x) & 0x7fffffff;
  if (ix >= 0x7ff00000) return x * x;
  if (ix < 0x3fd62e43) {
    // |x| < 0.5 ln2
    const t = expm1(fabs(x));
    const w = 1 + t;
    if (ix < 0x3c800000) return w;
    return 1 + (t * t) / (w + w);
  }
  if (ix < 0x40360000) {
    const t = exp(fabs(x));
    return 0.5 * t + 0.5 / t;
  }
  if (ix < 0x40862e42) return 0.5 * exp(fabs(x));
  if (ix < 0x408633ce || (ix === 0x408633ce && loWord(x) <= 0x8fb9f87d)) {
    const w = exp(0.5 * fabs(x));
    const t = 0.5 * w;
    return t * w;
  }
  return Infinity;
}

export function tanh(x: number): number {
  const jx = hiWord(x);
  const ix = jx & 0x7fffffff;
  if (ix >= 0x7ff00000) return jx >= 0 ? 1 / x + 1 : 1 / x - 1;
  let z: number;
  if (ix < 0x40360000) {
    if (ix < 0x3c800000) return x * (1 + x);
    if (ix >= 0x3ff00000) {
      const t = expm1(2 * fabs(x));
      z = 1 - 2 / (t + 2);
    } else {
      const t = expm1(-2 * fabs(x));
      z = -t / (t + 2);
    }
  } else {
    z = 1 - tiny;
  }
  return jx >= 0 ? z : -z;
}

// ---------------------------------------------------------------------------
// Installation.

/**
 * Every `Math` function this file replaces, by name. `sqrt`, `fround`,
 * `hypot`, `cbrt` and `log2` are not here because the native ones already
 * agree across platforms (measured, as above).
 */
export const DETERMINISTIC_MATH = { sin, cos, tan, atan, atan2, asin, acos, exp, log, pow, expm1, sinh, cosh, tanh } as const;

/** The functions as V8 shipped them, kept so a test can compare against them. */
export const NATIVE_MATH: { readonly [K in keyof typeof DETERMINISTIC_MATH]: (...args: number[]) => number } = {
  sin: Math.sin,
  cos: Math.cos,
  tan: Math.tan,
  atan: Math.atan,
  atan2: Math.atan2,
  asin: Math.asin,
  acos: Math.acos,
  exp: Math.exp,
  log: Math.log,
  pow: Math.pow,
  expm1: Math.expm1,
  sinh: Math.sinh,
  cosh: Math.cosh,
  tanh: Math.tanh,
};

/** Puts the deterministic functions on the global `Math`. Idempotent. */
export function installDeterministicMath(): void {
  const target = Math as unknown as Record<string, unknown>;
  for (const [name, fn] of Object.entries(DETERMINISTIC_MATH)) target[name] = fn;
}

/**
 * **Refuse to build a park on platform-dependent maths.** A park built with
 * the native functions is a different park on an arm64 Mac than on the x64
 * runner that ships it. That is a wrong park, not a slower one.
 */
export function assertDeterministicMath(where: string): void {
  const target = Math as unknown as Record<string, unknown>;
  const missing = Object.entries(DETERMINISTIC_MATH)
    .filter(([name, fn]) => target[name] !== fn)
    .map(([name]) => name);
  if (missing.length > 0) {
    throw new Error(
      `${where}: Math.${missing.join(', Math.')} ${missing.length === 1 ? 'is' : 'are'} still the platform's own. ` +
        'Install src/core/deterministicMath.ts before anything else is evaluated ' +
        '(the resolver --import for Node, test/setupDeterministicMath.ts for vitest, main.ts first import in the browser).',
    );
  }
}
