/**
 * **Is the authored kid the same kid?**
 *
 * ```
 * npm run check:character-parity
 * ```
 *
 * Stage A of the authored-character work moved the player kid's body and head
 * out of code and into `src/art/assets/kid.glb`. The claim that goes with it is
 * that *nothing about her changed*. This is what makes that claim checkable
 * instead of a matter of opinion.
 *
 * ## How it avoids the way these checks lie
 *
 * Twice on this project a parity check has passed while the game was visibly
 * wrong, both times the same way: **the new code was compared against itself.**
 * Face paint was "verified" against a landmark computed from the very constants
 * that had just moved, and the cat whiskers turned out to be 76 mm out, drawn
 * across the child's eyes. ART-AGENT-NOTES.md §6 has the write-up.
 *
 * So both sides here are built **in the same process, from different sources**:
 * `createKid({ geometry: 'procedural' })` is the primitive-built kid that
 * shipped before this change and is still the code the asset was generated
 * from, and `createKid({})` is the authored one the game now uses. Neither is
 * recomputed from the other's numbers.
 *
 * And it **enumerates**: every part in `KID_BODY_PARTS`, every anchor, a
 * silhouette swept at 64 angles, and a whole walk cycle — rather than naming
 * one part and generalising, which is the other way one of these lies.
 *
 * ## What it measures
 *
 * 1. **The asset's contents** — every named part is present, and no extras.
 * 2. **Every vertex**, in world space, as a sorted multiset of
 *    (position, normal, uv). Sorted rather than index-by-index, because a trip
 *    through Blender is allowed to reorder vertices; it is not allowed to move
 *    one.
 * 3. **Winding** — signed volume, and whether the shading normals agree with it.
 *    An inside-out part is *invisible*, not obviously broken; a fortnight was
 *    lost to exactly that.
 * 4. **The silhouette**, cast in from 64 angles at three heights — shape drift
 *    that a bounding box would miss.
 * 5. **The rig**: every anchor's world position, and the measured height.
 * 6. **A full walk cycle**, hand and foot tips frame by frame. This is the
 *    assertion that catches a part exported at the wrong origin.
 * 7. **Our `.glb` reader against three.js's own `GLTFLoader`**, because
 *    `art/style/glb.ts` is hand-rolled and hand-rolled readers get believed
 *    when they should be checked.
 */
import '../scripts/headless-canvas.mjs';
import { readFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import {
  Mesh,
  Object3D,
  Raycaster,
  Vector3,
  type BufferAttribute,
  type BufferGeometry,
} from 'three';
import { GLTFLoader } from 'three/examples/jsm/loaders/GLTFLoader.js';
import { createKid, KID_BODY_PARTS, type KidBodyPart, type KidHandle } from '../src/art/models/kid.ts';
import { kidAssetPartNames } from '../src/art/models/kidAsset.ts';
import { readGlbParts } from '../src/art/style/glb.ts';
import { visibleTop } from '../src/art/style/measure.ts';

const here = dirname(fileURLToPath(import.meta.url));
const GLB = resolve(here, '../src/art/assets/kid.glb');

/**
 * How far anything is allowed to have moved, in metres.
 *
 * Stage A geometry is generated by the code it replaces, so the honest
 * expectation is *zero* — float32 in and float32 out. This is a rounding
 * allowance, not a budget: Stage B gets its own tolerance, agreed separately,
 * and this one must never be widened to make Stage A pass.
 */
const TOLERANCE = 1e-6;

const failures: string[] = [];
const notes: string[] = [];

function check(ok: boolean, message: string): void {
  if (!ok) failures.push(message);
}

function findMesh(root: Object3D, name: string): Mesh {
  let found: Mesh | null = null;
  root.traverse((node) => {
    if (node instanceof Mesh && node.name === name) found = node;
  });
  if (!found) throw new Error(`check:character-parity: no mesh named '${name}'.`);
  return found;
}

// ---------------------------------------------------------------- 1. the asset

const assetNames = [...kidAssetPartNames()].sort();
const wanted = [...KID_BODY_PARTS].sort();
check(
  assetNames.join(',') === wanted.join(','),
  `the asset holds [${assetNames.join(', ')}] but KID_BODY_PARTS wants ` +
    `[${wanted.join(', ')}] — has \`npm run export:kid\` been re-run?`,
);

// ------------------------------------------------- 2. every vertex of every part

/** Every vertex of `mesh`, in the kid's own space, as (x,y,z,nx,ny,nz,u,v). */
function vertices(mesh: Mesh, root: Object3D): number[][] {
  root.updateMatrixWorld(true);
  const geometry: BufferGeometry = mesh.geometry;
  const position = geometry.getAttribute('position') as BufferAttribute;
  const normal = geometry.getAttribute('normal') as BufferAttribute | undefined;
  const uv = geometry.getAttribute('uv') as BufferAttribute | undefined;

  // Into the root's frame, so a part that moved *and* was reshaped to
  // compensate still reads as moved.
  const toRoot = root.matrixWorld.clone().invert().multiply(mesh.matrixWorld);
  const normalMatrix = mesh.matrixWorld.clone().setPosition(0, 0, 0);

  const point = new Vector3();
  const dir = new Vector3();
  const out: number[][] = [];
  for (let i = 0; i < position.count; i += 1) {
    point.fromBufferAttribute(position, i).applyMatrix4(toRoot);
    if (normal) dir.fromBufferAttribute(normal, i).applyMatrix4(normalMatrix).normalize();
    else dir.set(0, 0, 0);
    out.push([
      point.x,
      point.y,
      point.z,
      dir.x,
      dir.y,
      dir.z,
      uv ? uv.getX(i) : 0,
      uv ? uv.getY(i) : 0,
    ]);
  }
  return out;
}

/** Lexicographic, so two vertex lists compare as sets rather than as sequences. */
function sortRows(rows: number[][]): number[][] {
  return rows.slice().sort((a, b) => {
    for (let i = 0; i < a.length; i += 1) {
      const d = (a[i] as number) - (b[i] as number);
      if (Math.abs(d) > 1e-9) return d;
    }
    return 0;
  });
}

/**
 * How far apart two vertex sets are, worst case.
 *
 * The UV columns are counted in the same number as the metres, deliberately: a
 * UV is a fraction of a 512-pixel canvas, so 1e-6 of it is a five-hundredth of
 * a texel — every bit as strict there as a micrometre is on the geometry.
 */
function worstDelta(a: number[][], b: number[][]): number {
  let worst = 0;
  for (let i = 0; i < a.length; i += 1) {
    const rowA = a[i] as number[];
    const rowB = b[i] as number[];
    for (let c = 0; c < rowA.length; c += 1) {
      worst = Math.max(worst, Math.abs((rowA[c] as number) - (rowB[c] as number)));
    }
  }
  return worst;
}

/**
 * Which way round a closed mesh is wound, and whether its normals agree.
 *
 * **Inside-out geometry is invisible, not obviously broken.**
 * `MeshToonMaterial`'s `FrontSide` culls every fragment of it, and both critter
 * hoods' faces were drawn nowhere at all for a fortnight while the mesh, the
 * texture and the code all read correctly (CLAUDE.md). Two independent numbers,
 * because they catch different halves of it:
 *
 * - **`volume`** — the signed volume by the divergence theorem, `Σ a·(b×c)/6`.
 *   Positive means the triangles face outwards. It is the only formulation that
 *   works on *any* closed shell: the obvious "does the face normal point away
 *   from the centroid" test reports 0.10 on a perfectly good torus, because a
 *   torus's centroid is in its hole and its inner surface genuinely faces
 *   inwards. That very false alarm is what this replaced.
 * - **`agreement`** — the mean of `windingNormal · vertexNormal`, near +1 when
 *   the shading normals point the same way the triangles face. This is the half
 *   that actually bit the hoods: a patch whose *normals* pointed at the
 *   wearer's skull.
 */
function winding(mesh: Mesh): { volume: number; agreement: number } {
  const geometry = mesh.geometry;
  const position = geometry.getAttribute('position') as BufferAttribute;
  const normal = geometry.getAttribute('normal') as BufferAttribute | undefined;
  const index = geometry.getIndex();

  const a = new Vector3();
  const b = new Vector3();
  const c = new Vector3();
  const cross = new Vector3();
  const faceNormal = new Vector3();
  const shading = new Vector3();
  const scratch = new Vector3();

  const count = index ? index.count : position.count;
  let volume = 0;
  let agree = 0;
  let faces = 0;
  for (let i = 0; i < count; i += 3) {
    const i0 = index ? index.getX(i) : i;
    const i1 = index ? index.getX(i + 1) : i + 1;
    const i2 = index ? index.getX(i + 2) : i + 2;
    a.fromBufferAttribute(position, i0);
    b.fromBufferAttribute(position, i1);
    c.fromBufferAttribute(position, i2);

    volume += a.dot(cross.crossVectors(b, c)) / 6;

    if (!normal) continue;
    faceNormal.crossVectors(scratch.subVectors(b, a), cross.subVectors(c, a));
    if (faceNormal.lengthSq() === 0) continue;
    faceNormal.normalize();
    shading.set(0, 0, 0);
    for (const v of [i0, i1, i2]) shading.add(scratch.fromBufferAttribute(normal, v));
    if (shading.lengthSq() === 0) continue;
    agree += faceNormal.dot(shading.normalize());
    faces += 1;
  }
  return { volume, agreement: faces ? agree / faces : 0 };
}

const procedural = createKid({ geometry: 'procedural' });
const authored = createKid({});

let worstVertex = 0;
let worstAgreement = 1;
for (const name of KID_BODY_PARTS) {
  const before = findMesh(procedural.root, name);
  const after = findMesh(authored.root, name);

  const rowsBefore = vertices(before, procedural.root);
  const rowsAfter = vertices(after, authored.root);

  check(
    rowsBefore.length === rowsAfter.length,
    `${name}: ${rowsAfter.length} vertices authored against ${rowsBefore.length} procedural`,
  );

  const trisBefore = (before.geometry.getIndex()?.count ?? rowsBefore.length * 3) / 3;
  const trisAfter = (after.geometry.getIndex()?.count ?? rowsAfter.length * 3) / 3;
  check(
    trisBefore === trisAfter,
    `${name}: ${trisAfter} triangles authored against ${trisBefore} procedural`,
  );

  if (rowsBefore.length !== rowsAfter.length) continue;

  const delta = worstDelta(sortRows(rowsBefore), sortRows(rowsAfter));
  worstVertex = Math.max(worstVertex, delta);
  check(
    delta <= TOLERANCE,
    `${name}: a vertex moved by ${(delta * 1000).toFixed(4)} mm (or its uv/normal by ${delta.toExponential(2)})`,
  );

  const windBefore = winding(before);
  const windAfter = winding(after);
  check(
    windAfter.volume > 0,
    `${name}: authored signed volume is ${windAfter.volume.toExponential(2)} — this part is ` +
      `wound inside out and \`FrontSide\` will cull it completely`,
  );
  check(
    windAfter.agreement > 0.9,
    `${name}: authored normals agree with the winding by only ` +
      `${windAfter.agreement.toFixed(3)} — the shading normals point the wrong way`,
  );
  check(
    Math.abs(windAfter.volume - windBefore.volume) < 1e-9 &&
      Math.abs(windAfter.agreement - windBefore.agreement) < 1e-6,
    `${name}: winding changed (volume ${windBefore.volume.toExponential(4)} → ` +
      `${windAfter.volume.toExponential(4)}, agreement ${windBefore.agreement.toFixed(6)} → ` +
      `${windAfter.agreement.toFixed(6)})`,
  );
  worstAgreement = Math.min(worstAgreement, windAfter.agreement);
}
notes.push(
  `  ${KID_BODY_PARTS.length} parts, every vertex/normal/uv within ${worstVertex.toExponential(2)}`,
);
notes.push(
  `  winding: every part is outward-facing, normals agree by at least ` +
    `${worstAgreement.toFixed(4)}`,
);

// ------------------------------------------------------------- 3. the rig

function anchorPositions(kid: KidHandle): Record<string, Vector3> {
  kid.root.updateMatrixWorld(true);
  return {
    hatAnchor: kid.hatAnchor.getWorldPosition(new Vector3()),
    hairAnchor: kid.hairAnchor.getWorldPosition(new Vector3()),
    holdAnchor: kid.holdAnchor.getWorldPosition(new Vector3()),
    backpackAnchor: kid.backpackAnchor.getWorldPosition(new Vector3()),
    head: kid.head.getWorldPosition(new Vector3()),
    body: kid.body.getWorldPosition(new Vector3()),
  };
}

const anchorsBefore = anchorPositions(procedural);
const anchorsAfter = anchorPositions(authored);
for (const [name, before] of Object.entries(anchorsBefore)) {
  const after = anchorsAfter[name] as Vector3;
  const moved = before.distanceTo(after);
  check(moved <= TOLERANCE, `${name} moved ${(moved * 1000).toFixed(4)} mm`);
}

const heightBefore = visibleTop(procedural.root);
const heightAfter = visibleTop(authored.root);
check(
  Math.abs(heightBefore - heightAfter) <= TOLERANCE,
  `height: ${heightAfter.toFixed(6)} m authored against ${heightBefore.toFixed(6)} m procedural`,
);
check(
  Math.abs(procedural.hatAnchorHeight - authored.hatAnchorHeight) <= TOLERANCE,
  `hatAnchorHeight: ${authored.hatAnchorHeight} against ${procedural.hatAnchorHeight}`,
);
notes.push(`  height ${heightAfter.toFixed(4)} m, hat anchor ${authored.hatAnchorHeight.toFixed(4)} m`);

// ------------------------------------------------------ 4. the silhouette sweep

/**
 * Where the character's surface is, seen from 64 directions at three heights.
 *
 * A bounding box would pass a kid whose middle had caved in. A ray cast is what
 * the camera does, and it also honours `material.side`, so a part that has gone
 * inside out answers nothing at all rather than answering wrongly.
 */
function silhouette(kid: KidHandle): (number | null)[] {
  kid.root.updateMatrixWorld(true);
  const targets: Mesh[] = KID_BODY_PARTS.map((name) => findMesh(kid.root, name));
  const raycaster = new Raycaster();
  const out: (number | null)[] = [];
  const from = new Vector3();
  const towards = new Vector3();

  for (const height of [0.25, 0.75, 1.4]) {
    for (let i = 0; i < 64; i += 1) {
      const angle = (i / 64) * Math.PI * 2;
      const x = Math.sin(angle);
      const z = Math.cos(angle);
      from.set(x * 4, height, z * 4);
      towards.set(-x, 0, -z).normalize();
      raycaster.set(from, towards);
      const hit = raycaster.intersectObjects(targets, false)[0];
      out.push(hit ? hit.distance : null);
    }
  }
  return out;
}

const silBefore = silhouette(procedural);
const silAfter = silhouette(authored);
let worstSilhouette = 0;
let missing = 0;
for (let i = 0; i < silBefore.length; i += 1) {
  const before = silBefore[i];
  const after = silAfter[i];
  if (before === null || after === null) {
    if (before !== after) missing += 1;
    continue;
  }
  worstSilhouette = Math.max(worstSilhouette, Math.abs(before - after));
}
check(missing === 0, `the silhouette differs at ${missing} of 192 sampled rays (a hit became a miss, or the reverse)`);
check(
  worstSilhouette <= TOLERANCE,
  `the silhouette moved by up to ${(worstSilhouette * 1000).toFixed(4)} mm across 192 rays`,
);
notes.push(
  `  silhouette: 192 rays, worst ${(worstSilhouette * 1000).toFixed(4)} mm, ` +
    `${silAfter.filter((d) => d !== null).length} hits`,
);

// ------------------------------------------------------------ 5. the walk cycle

/** The tip of each hand and foot, right through one stride. */
function walkTrack(kid: KidHandle): number[] {
  const out: number[] = [];
  const tips = KID_BODY_PARTS.filter(
    (name) => name.startsWith('hand-') || name.startsWith('foot-'),
  );
  for (let frame = 0; frame < 24; frame += 1) {
    kid.setWalkPhase(frame / 24, 1);
    kid.root.updateMatrixWorld(true);
    for (const name of tips) {
      const mesh = findMesh(kid.root, name);
      const world = mesh.getWorldPosition(new Vector3());
      out.push(world.x, world.y, world.z);
    }
  }
  kid.setWalkPhase(0, 0);
  kid.root.updateMatrixWorld(true);
  return out;
}

const walkBefore = walkTrack(procedural);
const walkAfter = walkTrack(authored);
let worstWalk = 0;
for (let i = 0; i < walkBefore.length; i += 1) {
  worstWalk = Math.max(worstWalk, Math.abs((walkBefore[i] as number) - (walkAfter[i] as number)));
}
check(
  worstWalk <= TOLERANCE,
  `the walk cycle moved a hand or foot by up to ${(worstWalk * 1000).toFixed(4)} mm`,
);
notes.push(`  walk cycle: 24 frames × 4 limb tips, worst ${(worstWalk * 1000).toFixed(4)} mm`);

// -------------------------------------------- 6. our reader against three.js's

/**
 * `art/style/glb.ts` is hand-rolled, and a hand-rolled reader that looks right
 * is exactly the sort of thing this project has been caught by. So the same
 * file is read twice — once by ours, once by three.js's own `GLTFLoader` — and
 * the two have to agree on every number.
 */
const bytes = readFileSync(GLB);
const ours = readGlbParts(
  bytes.buffer.slice(bytes.byteOffset, bytes.byteOffset + bytes.byteLength) as ArrayBuffer,
);

const gltf = await new Promise<{ scene: Object3D }>((ok, fail) => {
  new GLTFLoader().parse(
    bytes.buffer.slice(bytes.byteOffset, bytes.byteOffset + bytes.byteLength) as ArrayBuffer,
    '',
    (result) => ok(result as unknown as { scene: Object3D }),
    fail,
  );
});

let worstReader = 0;
for (const name of KID_BODY_PARTS) {
  const mine = ours.get(name);
  const theirs = findMesh(gltf.scene, name);
  if (!mine) {
    check(false, `our reader did not find '${name}' in the .glb`);
    continue;
  }

  const attrs = ['position', 'normal', 'uv'] as const;
  for (const attribute of attrs) {
    const a = mine.geometry.getAttribute(attribute) as BufferAttribute | undefined;
    const b = theirs.geometry.getAttribute(attribute) as BufferAttribute | undefined;
    if (!a || !b) {
      check(Boolean(a) === Boolean(b), `${name}: the two readers disagree on whether '${attribute}' exists`);
      continue;
    }
    check(a.count === b.count, `${name}.${attribute}: ${a.count} against ${b.count}`);
    const n = Math.min(a.array.length, b.array.length);
    for (let i = 0; i < n; i += 1) {
      worstReader = Math.max(
        worstReader,
        Math.abs((a.array[i] as number) - (b.array[i] as number)),
      );
    }
  }

  const ia = mine.geometry.getIndex();
  const ib = theirs.geometry.getIndex();
  check(Boolean(ia) === Boolean(ib), `${name}: the two readers disagree on whether there is an index`);
  if (ia && ib) {
    check(ia.count === ib.count, `${name}: index ${ia.count} against ${ib.count}`);
    for (let i = 0; i < Math.min(ia.count, ib.count); i += 1) {
      if (ia.getX(i) !== ib.getX(i)) {
        check(false, `${name}: index ${i} is ${ia.getX(i)} to us and ${ib.getX(i)} to three.js`);
        break;
      }
    }
  }

  const posDelta = mine.position.distanceTo(theirs.position);
  const scaleDelta = mine.scale.distanceTo(theirs.scale);
  const rotDelta = Math.abs(mine.quaternion.dot(theirs.quaternion));
  check(posDelta < 1e-6, `${name}: the readers disagree on the node position by ${posDelta}`);
  check(scaleDelta < 1e-6, `${name}: the readers disagree on the node scale by ${scaleDelta}`);
  check(rotDelta > 1 - 1e-6, `${name}: the readers disagree on the node rotation`);
}
check(worstReader === 0, `our .glb reader and three.js's disagree by up to ${worstReader}`);
notes.push(`  .glb read twice — ours and three.js's GLTFLoader agree exactly`);

// ----------------------------------------------------------------------- done

console.log(`\ncheck:character-parity — authored kid against the procedural one\n`);
console.log(notes.join('\n'));

if (failures.length) {
  console.error(`\n${failures.length} problem(s):`);
  for (const failure of failures) console.error(`  ✗ ${failure}`);
  process.exit(1);
}
console.log(`\nThe authored kid is the same kid, to ${TOLERANCE} m.\n`);
