/**
 * **Is the authored kid the same kid?**
 *
 * ```
 * npm run check:character-parity
 * ```
 *
 * Stage A of the authored-character work moved the player kid's body and head
 * out of code and into `src/art/assets/kid.glb`. The claim that goes with it is
 * that *nothing about her changed*. This is what makes that claim checkable
 * instead of a matter of opinion.
 *
 * ## How it avoids the way these checks lie
 *
 * Twice on this project a parity check has passed while the game was visibly
 * wrong, both times the same way: **the new code was compared against itself.**
 * Face paint was "verified" against a landmark computed from the very constants
 * that had just moved, and the cat whiskers turned out to be 76 mm out, drawn
 * across the child's eyes. ART-AGENT-NOTES.md §6 has the write-up.
 *
 * So both sides here are built **in the same process, from different sources**:
 * `createKid({ geometry: 'procedural' })` is the primitive-built kid that
 * shipped before this change and is still the code the asset was generated
 * from, and `createKid({})` is the authored one the game now uses. Neither is
 * recomputed from the other's numbers.
 *
 * And it **enumerates**: every part in `KID_BODY_PARTS`, every anchor, a
 * silhouette swept at 64 angles, and a whole walk cycle — rather than naming
 * one part and generalising, which is the other way one of these lies.
 *
 * ## What it measures
 *
 * 1. **The asset's contents** — every named part is present, and no extras.
 * 2. **Every drawn vertex and every triangle.** The two builds' vertices are
 *    paired by where they are, not by index — a trip through Blender may
 *    reorder them, and does — and then each pair's position, uv and normal are
 *    compared, and each triangle is checked to join the same three *paired*
 *    vertices. Position and uv have to match to a micrometre; normals get a
 *    stated tolerance, for the reason at {@link NORMAL_TOLERANCE}.
 * 3. **Winding** — signed volume, and whether the shading normals agree with it.
 *    An inside-out part is *invisible*, not obviously broken; a fortnight was
 *    lost to exactly that.
 * 4. **The silhouette**, cast in from 64 angles at three heights — shape drift
 *    that a bounding box would miss.
 * 5. **The rig**: every anchor's world position, and the measured height.
 * 6. **A full walk cycle**, hand and foot tips frame by frame. This is the
 *    assertion that catches a part exported at the wrong origin.
 * 7. **Our `.glb` reader against three.js's own `GLTFLoader`**, because
 *    `art/style/glb.ts` is hand-rolled and hand-rolled readers get believed
 *    when they should be checked.
 */
import '../scripts/headless-canvas.mjs';
import { readFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import {
  Matrix3,
  Mesh,
  Object3D,
  Raycaster,
  Vector3,
  type BufferAttribute,
  type BufferGeometry,
} from 'three';
import { GLTFLoader } from 'three/examples/jsm/loaders/GLTFLoader.js';
import { createKid, KID_BODY_PARTS, type KidBodyPart, type KidHandle } from '../src/art/models/kid.ts';
import { kidAssetPartNames } from '../src/art/models/kidAsset.ts';
import { readGlbParts } from '../src/art/style/glb.ts';
import { visibleTop } from '../src/art/style/measure.ts';

const here = dirname(fileURLToPath(import.meta.url));
const GLB = resolve(here, '../src/art/assets/kid.glb');

/**
 * How far anything is allowed to have moved, in metres.
 *
 * Stage A geometry is generated by the code it replaces, so the honest
 * expectation is *zero* — float32 in and float32 out. This is a rounding
 * allowance, not a budget: Stage B gets its own tolerance, agreed separately,
 * and this one must never be widened to make Stage A pass.
 */
const TOLERANCE = 1e-6;

/**
 * How far a shading normal may have turned — the **one** thing the Blender round
 * trip really changes, and the reason there are two numbers rather than one.
 *
 * Blender does not store an imported custom normal as a vector. It stores it
 * relative to a **tangent frame built per corner**, and that frame is
 * ill-conditioned wherever a fan of triangles meets at a single point. So the
 * error is not uniform: it is a rounding wobble almost everywhere, and a real
 * tilt at exactly the places a surface degenerates to a point.
 *
 * Measured, by `scripts/_tmp-normals.mts` during the Stage A round trip:
 *
 * | where | worst |
 * | --- | --- |
 * | ordinary vertices, every part | 0.019° |
 * | the poles of the four capsules (torso, arms, legs) | 1.076° |
 *
 * So each gets its own bound. `ORDINARY` is tight enough that any real change
 * to a normal fails it. `FAN_APEX` is loose, and it is loose *only* at a
 * vertex whose position is shared by three or more others — a fan apex, which
 * is a single point on the model with no area of its own, on parts whose poles
 * sit inside the hem, the shoulder and the shoe. Against a four-band toon ramp
 * whose narrowest band spans some 60° of surface, one degree at one point
 * cannot move a band edge anywhere a camera can see it.
 *
 * These are *stated* tolerances, not quietly-widened ones. If either has to
 * grow, that is a finding to write down, not a number to edit.
 */
const NORMAL_TOLERANCE = {
  ordinary: (0.05 * Math.PI) / 180,
  fanApex: (1.2 * Math.PI) / 180,
} as const;

const failures: string[] = [];
const notes: string[] = [];

function check(ok: boolean, message: string): void {
  if (!ok) failures.push(message);
}

function findMesh(root: Object3D, name: string): Mesh {
  let found: Mesh | null = null;
  root.traverse((node) => {
    if (node instanceof Mesh && node.name === name) found = node;
  });
  if (!found) throw new Error(`check:character-parity: no mesh named '${name}'.`);
  return found;
}

// ---------------------------------------------------------------- 1. the asset

const assetNames = [...kidAssetPartNames()].sort();
const wanted = [...KID_BODY_PARTS].sort();
check(
  assetNames.join(',') === wanted.join(','),
  `the asset holds [${assetNames.join(', ')}] but KID_BODY_PARTS wants ` +
    `[${wanted.join(', ')}] — has \`npm run export:kid\` been re-run?`,
);

// ------------------------------------------------- 2. every vertex of every part

/**
 * The **surface** a mesh describes, in the kid's own space.
 *
 * Deliberately not "the contents of its buffers", and the difference is the
 * whole reason this function is shaped the way it is. A `.glb` that has been
 * through Blender is not byte-identical to one that has not, and two of the
 * ways it differs are *not* changes to the model:
 *
 * - **three.js's `SphereGeometry` emits two vertices no triangle ever
 *   references** — leftovers of the extra pole column — and Blender drops
 *   them. Measured: 285 → 283 on a hand, 1170 → 1168 on the skull, with the
 *   *referenced* count 283 and 1168 on both sides and the triangle set
 *   identical. Nothing on screen can depend on a vertex nothing draws.
 * - **normals come back re-rounded** at about 1e-5, being float32 through a
 *   different pipeline.
 *
 * So this walks the triangles rather than the vertex array: every triangle as
 * its three positions, and every *referenced* vertex as its position, uv and
 * normal. Positions and uvs are then compared exactly, and normals as an angle
 * with a stated tolerance. Comparing raw buffers would have failed on two dead
 * vertices, which is a check crying wolf — and a check that cries wolf gets
 * relaxed until it is useless.
 */
/** A position rounded to a micrometre, for grouping vertices that coincide. */
function key(...values: number[]): string {
  return values.map((n) => Math.round(n * 1e6)).join(',');
}

interface Vertex {
  readonly position: Vector3;
  readonly uv: [number, number];
  readonly normal: Vector3;
}

interface Surface {
  /** Every *drawn* vertex, in the kid's own space. */
  readonly points: Vertex[];
  /** Every triangle, as three indices into {@link points}. */
  readonly triangles: [number, number, number][];
  /** How many vertices the buffer holds, against how many any triangle uses. */
  readonly stored: number;
}

/**
 * The **surface** a mesh describes, in the kid's own space.
 *
 * Deliberately not "the contents of its buffers". A `.glb` that has been
 * through Blender is not byte-identical to one that has not, and one of the
 * ways it differs is not a change to the model: **three.js's `SphereGeometry`
 * emits two vertices no triangle ever references** — leftovers of the extra
 * pole column — and Blender drops them. Measured: 285 → 283 on a hand,
 * 1170 → 1168 on the skull, with the *drawn* count 283 and 1168 on both sides.
 * Nothing on screen can depend on a vertex nothing draws, so this walks the
 * triangles and keeps only the vertices they reach.
 */
function surfaceOf(mesh: Mesh, root: Object3D): Surface {
  root.updateMatrixWorld(true);
  const geometry: BufferGeometry = mesh.geometry;
  const position = geometry.getAttribute('position') as BufferAttribute;
  const normal = geometry.getAttribute('normal') as BufferAttribute | undefined;
  const uv = geometry.getAttribute('uv') as BufferAttribute | undefined;
  const index = geometry.getIndex();

  // Into the root's frame, so a part that moved *and* was reshaped to
  // compensate still reads as moved.
  const toRoot = root.matrixWorld.clone().invert().multiply(mesh.matrixWorld);
  // The correct transform for a direction under a possibly non-uniform scale,
  // which almost every part of this character has — `blob` squashes on the
  // mesh's own scale.
  const forNormals = new Matrix3().getNormalMatrix(mesh.matrixWorld);

  const slot = new Map<number, number>();
  const points: Vertex[] = [];
  const take = (i: number): number => {
    const existing = slot.get(i);
    if (existing !== undefined) return existing;
    const dir = new Vector3();
    if (normal) dir.fromBufferAttribute(normal, i).applyMatrix3(forNormals).normalize();
    points.push({
      position: new Vector3().fromBufferAttribute(position, i).applyMatrix4(toRoot),
      uv: uv ? [uv.getX(i), uv.getY(i)] : [0, 0],
      normal: dir,
    });
    slot.set(i, points.length - 1);
    return points.length - 1;
  };

  const triangles: [number, number, number][] = [];
  const count = index ? index.count : position.count;
  for (let i = 0; i < count; i += 3) {
    triangles.push([
      take(index ? index.getX(i) : i),
      take(index ? index.getX(i + 1) : i + 1),
      take(index ? index.getX(i + 2) : i + 2),
    ]);
  }

  return { points, triangles, stored: position.count };
}

/**
 * Pairs each of `a`'s vertices with the one in `b` that is in the same place.
 *
 * **Why proximity and not sorting or hashing.** Both were tried and both lied.
 * A `.glb` that has been through Blender comes back with positions agreeing to
 * about a ten-thousandth of a millimetre — but *many coordinates on this model
 * are mathematically equal to one another* (a torus rotated on its side has
 * nine distinct heights across two hundred vertices), so noise of that size
 * breaks ties in a different order on each side and a plain sort pairs a
 * vertex on the collar with one 623 mm away. Rounding to a key has the mirror
 * problem: any value near a boundary reads as one vertex lost and another
 * gained, which cost eight phantom failures on the skirt hem.
 *
 * So: a 1 mm spatial hash, the 27 surrounding cells searched, and the nearest
 * candidate by position **and** uv together — the uv is what separates the two
 * copies of a vertex either side of a UV seam, which share a position exactly.
 * The pairing is then asserted to be one-to-one, so a genuine loss still fails.
 */
function pairVertices(a: Surface, b: Surface): number[] {
  const CELL = 1e-3;
  const cell = (v: Vector3): string =>
    `${Math.floor(v.x / CELL)},${Math.floor(v.y / CELL)},${Math.floor(v.z / CELL)}`;

  const buckets = new Map<string, number[]>();
  b.points.forEach((point, i) => {
    const k = cell(point.position);
    const list = buckets.get(k);
    if (list) list.push(i);
    else buckets.set(k, [i]);
  });

  const taken = new Set<number>();
  return a.points.map((point) => {
    const cx = Math.floor(point.position.x / CELL);
    const cy = Math.floor(point.position.y / CELL);
    const cz = Math.floor(point.position.z / CELL);
    let best = -1;
    let bestCost = Infinity;
    for (let dx = -1; dx <= 1; dx += 1) {
      for (let dy = -1; dy <= 1; dy += 1) {
        for (let dz = -1; dz <= 1; dz += 1) {
          for (const j of buckets.get(`${cx + dx},${cy + dy},${cz + dz}`) ?? []) {
            if (taken.has(j)) continue;
            const other = b.points[j] as Vertex;
            const cost =
              point.position.distanceTo(other.position) +
              Math.abs(point.uv[0] - other.uv[0]) +
              Math.abs(point.uv[1] - other.uv[1]);
            if (cost < bestCost) {
              bestCost = cost;
              best = j;
            }
          }
        }
      }
    }
    if (best >= 0) taken.add(best);
    return best;
  });
}

/**
 * Which way round a closed mesh is wound, and whether its normals agree.
 *
 * **Inside-out geometry is invisible, not obviously broken.**
 * `MeshToonMaterial`'s `FrontSide` culls every fragment of it, and both critter
 * hoods' faces were drawn nowhere at all for a fortnight while the mesh, the
 * texture and the code all read correctly (CLAUDE.md). Two independent numbers,
 * because they catch different halves of it:
 *
 * - **`volume`** — the signed volume by the divergence theorem, `Σ a·(b×c)/6`.
 *   Positive means the triangles face outwards. It is the only formulation that
 *   works on *any* closed shell: the obvious "does the face normal point away
 *   from the centroid" test reports 0.10 on a perfectly good torus, because a
 *   torus's centroid is in its hole and its inner surface genuinely faces
 *   inwards. That very false alarm is what this replaced.
 * - **`agreement`** — the mean of `windingNormal · vertexNormal`, near +1 when
 *   the shading normals point the same way the triangles face. This is the half
 *   that actually bit the hoods: a patch whose *normals* pointed at the
 *   wearer's skull.
 */
function winding(mesh: Mesh): { volume: number; agreement: number } {
  const geometry = mesh.geometry;
  const position = geometry.getAttribute('position') as BufferAttribute;
  const normal = geometry.getAttribute('normal') as BufferAttribute | undefined;
  const index = geometry.getIndex();

  const a = new Vector3();
  const b = new Vector3();
  const c = new Vector3();
  const cross = new Vector3();
  const faceNormal = new Vector3();
  const shading = new Vector3();
  const scratch = new Vector3();

  const count = index ? index.count : position.count;
  let volume = 0;
  let agree = 0;
  let faces = 0;
  for (let i = 0; i < count; i += 3) {
    const i0 = index ? index.getX(i) : i;
    const i1 = index ? index.getX(i + 1) : i + 1;
    const i2 = index ? index.getX(i + 2) : i + 2;
    a.fromBufferAttribute(position, i0);
    b.fromBufferAttribute(position, i1);
    c.fromBufferAttribute(position, i2);

    volume += a.dot(cross.crossVectors(b, c)) / 6;

    if (!normal) continue;
    faceNormal.crossVectors(scratch.subVectors(b, a), cross.subVectors(c, a));
    if (faceNormal.lengthSq() === 0) continue;
    faceNormal.normalize();
    shading.set(0, 0, 0);
    for (const v of [i0, i1, i2]) shading.add(scratch.fromBufferAttribute(normal, v));
    if (shading.lengthSq() === 0) continue;
    agree += faceNormal.dot(shading.normalize());
    faces += 1;
  }
  return { volume, agreement: faces ? agree / faces : 0 };
}

const procedural = createKid({ geometry: 'procedural' });
const authored = createKid({});

let worstNormal = 0;
let worstApexNormal = 0;
let worstPosition = 0;
let worstUv = 0;
let worstAgreement = 1;
let droppedTotal = 0;
for (const name of KID_BODY_PARTS) {
  const before = findMesh(procedural.root, name);
  const after = findMesh(authored.root, name);

  const a = surfaceOf(before, procedural.root);
  const b = surfaceOf(after, authored.root);

  check(
    a.triangles.length === b.triangles.length,
    `${name}: ${b.triangles.length} triangles authored against ${a.triangles.length} procedural`,
  );
  check(
    a.points.length === b.points.length,
    `${name}: ${b.points.length} vertices are drawn, against ${a.points.length} procedural`,
  );
  if (a.triangles.length !== b.triangles.length || a.points.length !== b.points.length) continue;

  const pairing = pairVertices(a, b);
  check(
    new Set(pairing).size === pairing.length && !pairing.includes(-1),
    `${name}: the two builds' vertices do not pair one to one — ` +
      `${pairing.filter((p) => p < 0).length} unmatched`,
  );
  if (new Set(pairing).size !== pairing.length || pairing.includes(-1)) continue;

  // Which vertices sit at a fan apex — a point three or more of them share.
  // Counted off the built mesh, not assumed from which primitive made it.
  const crowdedness = new Map<string, number>();
  for (const point of a.points) {
    const at = key(point.position.x, point.position.y, point.position.z);
    crowdedness.set(at, (crowdedness.get(at) ?? 0) + 1);
  }

  // Position, uv and normal on each paired vertex.
  let partPosition = 0;
  let partUv = 0;
  let partNormal = 0;
  let partApexNormal = 0;
  a.points.forEach((one, i) => {
    const other = b.points[pairing[i] as number] as Vertex;
    partPosition = Math.max(partPosition, one.position.distanceTo(other.position));
    partUv = Math.max(
      partUv,
      Math.abs(one.uv[0] - other.uv[0]),
      Math.abs(one.uv[1] - other.uv[1]),
    );
    const turned = Math.acos(Math.min(1, Math.max(-1, one.normal.dot(other.normal))));
    const at = key(one.position.x, one.position.y, one.position.z);
    if ((crowdedness.get(at) ?? 1) >= 3) partApexNormal = Math.max(partApexNormal, turned);
    else partNormal = Math.max(partNormal, turned);
  });
  check(partPosition <= TOLERANCE, `${name}: a vertex moved ${(partPosition * 1000).toFixed(5)} mm`);
  check(partUv <= TOLERANCE, `${name}: a uv moved by ${partUv.toExponential(2)}`);
  check(
    partNormal <= NORMAL_TOLERANCE.ordinary,
    `${name}: an ordinary vertex's normal turned by ${((partNormal * 180) / Math.PI).toFixed(4)}°`,
  );
  check(
    partApexNormal <= NORMAL_TOLERANCE.fanApex,
    `${name}: a fan apex's normal turned by ${((partApexNormal * 180) / Math.PI).toFixed(4)}°`,
  );
  worstApexNormal = Math.max(worstApexNormal, partApexNormal);

  // The triangles, put through that pairing: not "roughly the same shape" but
  // literally the same triangles between the same vertices.
  const label = (tri: readonly number[]): string => [...tri].sort((x, y) => x - y).join('-');
  const mine = a.triangles.map((tri) => label(tri.map((v) => pairing[v] as number))).sort();
  const theirs = b.triangles.map(label).sort();
  const differing = mine.filter((tri, i) => tri !== theirs[i]).length;
  check(
    differing === 0,
    `${name}: ${differing} of ${mine.length} triangles join a different set of vertices`,
  );

  worstPosition = Math.max(worstPosition, partPosition);
  worstUv = Math.max(worstUv, partUv);
  worstNormal = Math.max(worstNormal, partNormal);
  droppedTotal += a.stored - a.points.length - (b.stored - b.points.length);

  const windBefore = winding(before);
  const windAfter = winding(after);
  check(
    windAfter.volume > 0,
    `${name}: authored signed volume is ${windAfter.volume.toExponential(2)} — this part is ` +
      `wound inside out and \`FrontSide\` will cull it completely`,
  );
  check(
    windAfter.agreement > 0.9,
    `${name}: authored normals agree with the winding by only ` +
      `${windAfter.agreement.toFixed(3)} — the shading normals point the wrong way`,
  );
  check(
    Math.abs(windAfter.volume - windBefore.volume) < 1e-9,
    `${name}: enclosed volume changed, ${windBefore.volume.toExponential(6)} → ` +
      `${windAfter.volume.toExponential(6)}`,
  );
  worstAgreement = Math.min(worstAgreement, windAfter.agreement);
}
notes.push(
  `  ${KID_BODY_PARTS.length} parts: every triangle between the same points; worst vertex ` +
    `${(worstPosition * 1000).toFixed(6)} mm, worst uv ${worstUv.toExponential(2)}`,
);
notes.push(
  `  normals: ordinary vertices turned at most ${((worstNormal * 180) / Math.PI).toFixed(4)}°, ` +
    `fan apexes ${((worstApexNormal * 180) / Math.PI).toFixed(4)}° ` +
    `(bounds ${((NORMAL_TOLERANCE.ordinary * 180) / Math.PI).toFixed(2)}° and ` +
    `${((NORMAL_TOLERANCE.fanApex * 180) / Math.PI).toFixed(2)}°)`,
);
notes.push(
  `  winding: every part outward-facing, normals agree by at least ` +
    `${worstAgreement.toFixed(4)}; ${droppedTotal} undrawn vertices dropped by the round trip`,
);

// ------------------------------------------------------------- 3. the rig

function anchorPositions(kid: KidHandle): Record<string, Vector3> {
  kid.root.updateMatrixWorld(true);
  return {
    hatAnchor: kid.hatAnchor.getWorldPosition(new Vector3()),
    hairAnchor: kid.hairAnchor.getWorldPosition(new Vector3()),
    holdAnchor: kid.holdAnchor.getWorldPosition(new Vector3()),
    backpackAnchor: kid.backpackAnchor.getWorldPosition(new Vector3()),
    head: kid.head.getWorldPosition(new Vector3()),
    body: kid.body.getWorldPosition(new Vector3()),
  };
}

const anchorsBefore = anchorPositions(procedural);
const anchorsAfter = anchorPositions(authored);
for (const [name, before] of Object.entries(anchorsBefore)) {
  const after = anchorsAfter[name] as Vector3;
  const moved = before.distanceTo(after);
  check(moved <= TOLERANCE, `${name} moved ${(moved * 1000).toFixed(4)} mm`);
}

const heightBefore = visibleTop(procedural.root);
const heightAfter = visibleTop(authored.root);
check(
  Math.abs(heightBefore - heightAfter) <= TOLERANCE,
  `height: ${heightAfter.toFixed(6)} m authored against ${heightBefore.toFixed(6)} m procedural`,
);
check(
  Math.abs(procedural.hatAnchorHeight - authored.hatAnchorHeight) <= TOLERANCE,
  `hatAnchorHeight: ${authored.hatAnchorHeight} against ${procedural.hatAnchorHeight}`,
);
notes.push(`  height ${heightAfter.toFixed(4)} m, hat anchor ${authored.hatAnchorHeight.toFixed(4)} m`);

// ------------------------------------------------------ 4. the silhouette sweep

/**
 * Where the character's surface is, seen from 64 directions at three heights.
 *
 * A bounding box would pass a kid whose middle had caved in. A ray cast is what
 * the camera does, and it also honours `material.side`, so a part that has gone
 * inside out answers nothing at all rather than answering wrongly.
 */
function silhouette(kid: KidHandle): (number | null)[] {
  kid.root.updateMatrixWorld(true);
  const targets: Mesh[] = KID_BODY_PARTS.map((name) => findMesh(kid.root, name));
  const raycaster = new Raycaster();
  const out: (number | null)[] = [];
  const from = new Vector3();
  const towards = new Vector3();

  for (const height of [0.25, 0.75, 1.4]) {
    for (let i = 0; i < 64; i += 1) {
      const angle = (i / 64) * Math.PI * 2;
      const x = Math.sin(angle);
      const z = Math.cos(angle);
      from.set(x * 4, height, z * 4);
      towards.set(-x, 0, -z).normalize();
      raycaster.set(from, towards);
      const hit = raycaster.intersectObjects(targets, false)[0];
      out.push(hit ? hit.distance : null);
    }
  }
  return out;
}

const silBefore = silhouette(procedural);
const silAfter = silhouette(authored);
let worstSilhouette = 0;
let missing = 0;
for (let i = 0; i < silBefore.length; i += 1) {
  const before = silBefore[i];
  const after = silAfter[i];
  if (before === null || after === null) {
    if (before !== after) missing += 1;
    continue;
  }
  worstSilhouette = Math.max(worstSilhouette, Math.abs(before - after));
}
check(missing === 0, `the silhouette differs at ${missing} of 192 sampled rays (a hit became a miss, or the reverse)`);
check(
  worstSilhouette <= TOLERANCE,
  `the silhouette moved by up to ${(worstSilhouette * 1000).toFixed(4)} mm across 192 rays`,
);
notes.push(
  `  silhouette: 192 rays, worst ${(worstSilhouette * 1000).toFixed(4)} mm, ` +
    `${silAfter.filter((d) => d !== null).length} hits`,
);

// ------------------------------------------------------------ 5. the walk cycle

/** The tip of each hand and foot, right through one stride. */
function walkTrack(kid: KidHandle): number[] {
  const out: number[] = [];
  const tips = KID_BODY_PARTS.filter(
    (name) => name.startsWith('hand-') || name.startsWith('foot-'),
  );
  for (let frame = 0; frame < 24; frame += 1) {
    kid.setWalkPhase(frame / 24, 1);
    kid.root.updateMatrixWorld(true);
    for (const name of tips) {
      const mesh = findMesh(kid.root, name);
      const world = mesh.getWorldPosition(new Vector3());
      out.push(world.x, world.y, world.z);
    }
  }
  kid.setWalkPhase(0, 0);
  kid.root.updateMatrixWorld(true);
  return out;
}

const walkBefore = walkTrack(procedural);
const walkAfter = walkTrack(authored);
let worstWalk = 0;
for (let i = 0; i < walkBefore.length; i += 1) {
  worstWalk = Math.max(worstWalk, Math.abs((walkBefore[i] as number) - (walkAfter[i] as number)));
}
check(
  worstWalk <= TOLERANCE,
  `the walk cycle moved a hand or foot by up to ${(worstWalk * 1000).toFixed(4)} mm`,
);
notes.push(`  walk cycle: 24 frames × 4 limb tips, worst ${(worstWalk * 1000).toFixed(4)} mm`);

// -------------------------------------------- 6. our reader against three.js's

/**
 * `art/style/glb.ts` is hand-rolled, and a hand-rolled reader that looks right
 * is exactly the sort of thing this project has been caught by. So the same
 * file is read twice — once by ours, once by three.js's own `GLTFLoader` — and
 * the two have to agree on every number.
 */
const bytes = readFileSync(GLB);
const ours = readGlbParts(
  bytes.buffer.slice(bytes.byteOffset, bytes.byteOffset + bytes.byteLength) as ArrayBuffer,
);

const gltf = await new Promise<{ scene: Object3D }>((ok, fail) => {
  new GLTFLoader().parse(
    bytes.buffer.slice(bytes.byteOffset, bytes.byteOffset + bytes.byteLength) as ArrayBuffer,
    '',
    (result) => ok(result as unknown as { scene: Object3D }),
    fail,
  );
});

let worstReader = 0;
for (const name of KID_BODY_PARTS) {
  const mine = ours.get(name);
  const theirs = findMesh(gltf.scene, name);
  if (!mine) {
    check(false, `our reader did not find '${name}' in the .glb`);
    continue;
  }

  const attrs = ['position', 'normal', 'uv'] as const;
  for (const attribute of attrs) {
    const a = mine.geometry.getAttribute(attribute) as BufferAttribute | undefined;
    const b = theirs.geometry.getAttribute(attribute) as BufferAttribute | undefined;
    if (!a || !b) {
      check(Boolean(a) === Boolean(b), `${name}: the two readers disagree on whether '${attribute}' exists`);
      continue;
    }
    check(a.count === b.count, `${name}.${attribute}: ${a.count} against ${b.count}`);
    const n = Math.min(a.array.length, b.array.length);
    for (let i = 0; i < n; i += 1) {
      worstReader = Math.max(
        worstReader,
        Math.abs((a.array[i] as number) - (b.array[i] as number)),
      );
    }
  }

  const ia = mine.geometry.getIndex();
  const ib = theirs.geometry.getIndex();
  check(Boolean(ia) === Boolean(ib), `${name}: the two readers disagree on whether there is an index`);
  if (ia && ib) {
    check(ia.count === ib.count, `${name}: index ${ia.count} against ${ib.count}`);
    for (let i = 0; i < Math.min(ia.count, ib.count); i += 1) {
      if (ia.getX(i) !== ib.getX(i)) {
        check(false, `${name}: index ${i} is ${ia.getX(i)} to us and ${ib.getX(i)} to three.js`);
        break;
      }
    }
  }

  const posDelta = mine.position.distanceTo(theirs.position);
  const scaleDelta = mine.scale.distanceTo(theirs.scale);
  const rotDelta = Math.abs(mine.quaternion.dot(theirs.quaternion));
  check(posDelta < 1e-6, `${name}: the readers disagree on the node position by ${posDelta}`);
  check(scaleDelta < 1e-6, `${name}: the readers disagree on the node scale by ${scaleDelta}`);
  check(rotDelta > 1 - 1e-6, `${name}: the readers disagree on the node rotation`);
}
check(worstReader === 0, `our .glb reader and three.js's disagree by up to ${worstReader}`);
notes.push(`  .glb read twice — ours and three.js's GLTFLoader agree exactly`);

// ----------------------------------------------------------------------- done

console.log(`\ncheck:character-parity — authored kid against the procedural one\n`);
console.log(notes.join('\n'));

if (failures.length) {
  console.error(`\n${failures.length} problem(s):`);
  for (const failure of failures) console.error(`  ✗ ${failure}`);
  process.exit(1);
}
console.log(`\nThe authored kid is the same kid, to ${TOLERANCE} m.\n`);
