/**
 * **Every coplanar seam that already existed when #472's gate was written.**
 *
 * Generated — `pnpm run check:coplanar -- --print-baseline`. Do not hand-edit
 * to make a check pass: an entry here means "this was already wrong", and a
 * finding that is not here means somebody has just made a new one.
 *
 * `area` is the worst shared plane seen across the seed pool, in square
 * metres. Where two objects meet in two *parallel* planes those fold into one
 * entry and this is their sum, so a second seam between the same two things
 * shows up here as growth.
 *
 * `seams` is how many distinct **facings** the two share on the worst single
 * seed. Two objects can meet pointing more than one way, and two different
 * objects can share a path — `hotel.wall` appears twice below, because both
 * meshes are called that — so without a count a third wall joining an existing
 * key would pass in silence.
 *
 * `fighting` is true where the two faces are within 0.1 mm — the depth buffer
 * has nothing to resolve and the seam strobes now; false means they are held
 * apart by a maintained stand-off under 1 cm, which `ART_DIRECTION.md` calls a
 * smell in its own right.
 *
 * The way an entry leaves this table is by the seam being fixed, at which point
 * `check:coplanar` prints BASELINE LOOSE and asks for the line to be deleted.
 */

/** The worst a known seam has been measured at. */
export interface BaselineEntry {
  /** Square metres of shared plane, worst across the pool. */
  readonly area: number;
  /** Distinct facings these two shared, on the worst single seed. */
  readonly seams: number;
  /** True where the faces are within 0.1 mm of each other. */
  readonly fighting: boolean;
}

export const COPLANAR_BASELINE: Readonly<Record<string, BaselineEntry>> = {
  "garden|anchor-plots/anchor:waterFight/waterfight:plot/<Mesh:CircleGeometry>|anchor-plots/anchor:waterFight/waterfight:plot/<Mesh:RoundedBoxGeometry>": { area: 16.4799, seams: 1, fighting: false },
  "castle.mall|the-big-building-inside/building-shell/building-shell-floor-0/deck-0|the-big-building-inside/building-shell/building-shell-floor-0/interior-porch/<Mesh:BoxGeometry>": { area: 8.3250, seams: 1, fighting: true },
  "castle.hall|the-big-building-inside/building-shell/building-shell-floor-1/castle-decor-1/castle-furniture-1/castle.feastTable/table-legs|the-big-building-inside/building-shell/building-shell-floor-1/castle-decor-1/castle-furniture-1/castle.feastTable/table-top/<Mesh:BufferGeometry>": { area: 8.3160, seams: 1, fighting: false },
  "hotel.suite|the-land-hotel-inside/hotel:hotel.suite/hotel.bed/bed-mattress|the-land-hotel-inside/hotel:hotel.suite/hotel.napBlanket/<Mesh:BoxGeometry>/<Mesh:BoxGeometry>": { area: 5.9577, seams: 1, fighting: false },
  "garden|entrance/welcome-sign/<Mesh:BoxGeometry>|entrance/welcome-sign/<Mesh:PlaneGeometry>": { area: 5.6443, seams: 1, fighting: false },
  "castle.hall|the-big-building-inside/building-shell/building-shell-floor-1/deck-1|the-big-building-inside/building-shell/building-shell-floor-1/lift-alcove/hotel.liftCar/lift-car-floor": { area: 5.2882, seams: 1, fighting: true },
  "castle.mall|the-big-building-inside/building-shell/building-shell-floor-0/deck-0|the-big-building-inside/building-shell/building-shell-floor-0/lift-alcove/hotel.liftCar/lift-car-floor": { area: 5.2882, seams: 1, fighting: true },
  "castle.roof|the-big-building-inside/building-shell/building-shell-floor-2/deck-2|the-big-building-inside/building-shell/building-shell-floor-2/lift-alcove/hotel.liftCar/lift-car-floor": { area: 5.2882, seams: 1, fighting: true },
  "hotel.lobby|the-land-hotel-inside/hotel:hotel.lobby/hotel.wall|the-land-hotel-inside/hotel:hotel.lobby/hotel.wall": { area: 4.4500, seams: 3, fighting: true },
  "garden|garden/path-kerb|garden/path-surface": { area: 3.9910, seams: 1, fighting: false },
  "hotel.lobby|the-land-hotel-inside/hotel:hotel.lobby/hotel.artwork/<Mesh:BoxGeometry>/<Mesh:BoxGeometry>|the-land-hotel-inside/hotel:hotel.lobby/hotel.wall": { area: 3.7500, seams: 1, fighting: false },
  "garden|anchor-plots/anchor:hotel/the-land-hotel-outside/hotel.tower/tower-main/<Mesh:BufferGeometry>|garden/terrain": { area: 3.4456, seams: 1, fighting: false },
  "garden|scenery/wooden-walls/<Mesh:CylinderGeometry>|scenery/wooden-walls/<Mesh:CylinderGeometry>": { area: 3.4004, seams: 9, fighting: true },
  "garden|garden/path-surface|park-train/train-track/track-ballast": { area: 3.0323, seams: 3, fighting: false },
  "hotel.lobby|the-land-hotel-inside/hotel:hotel.lobby/hotel.column/<Mesh:CylinderGeometry>/<Mesh:CylinderGeometry>|the-land-hotel-inside/hotel:hotel.lobby/hotel.column/<Mesh:CylinderGeometry>/<Mesh:CylinderGeometry>": { area: 3.0179, seams: 1, fighting: false },
  "castle.roof|the-big-building-inside/building-shell/building-shell-floor-2/castle-decor-2/castle-roof-burrows-2/castle-roof-burrow-mounds-2|the-big-building-inside/building-shell/building-shell-floor-2/castle-decor-2/castle-roof-burrows-2/castle-roof-burrow-mouths-2": { area: 2.9668, seams: 1, fighting: false },
  "castle.mall|the-big-building-inside/building-shell/building-shell-floor-0/shop:balloon/shop-stage:balloon/kiosk:balloon/<Mesh:BoxGeometry>|the-big-building-inside/building-shell/building-shell-floor-0/shop:balloon/shop-stage:balloon/unit-placeholder/<Mesh:BoxGeometry>": { area: 2.5080, seams: 3, fighting: true },
  "castle.mall|the-big-building-inside/building-shell/building-shell-floor-0/shop:candyFloss/shop-stage:candyFloss/kiosk:candyFloss/<Mesh:BoxGeometry>|the-big-building-inside/building-shell/building-shell-floor-0/shop:candyFloss/shop-stage:candyFloss/unit-placeholder/<Mesh:BoxGeometry>": { area: 2.5080, seams: 3, fighting: true },
  "castle.mall|the-big-building-inside/building-shell/building-shell-floor-0/shop:hat/shop-stage:hat/kiosk:hat/<Mesh:BoxGeometry>|the-big-building-inside/building-shell/building-shell-floor-0/shop:hat/shop-stage:hat/unit-placeholder/<Mesh:BoxGeometry>": { area: 2.5080, seams: 3, fighting: true },
  "castle.mall|the-big-building-inside/building-shell/building-shell-floor-0/shop:iceCream/shop-stage:iceCream/kiosk:iceCream/<Mesh:BoxGeometry>|the-big-building-inside/building-shell/building-shell-floor-0/shop:iceCream/shop-stage:iceCream/unit-placeholder/<Mesh:BoxGeometry>": { area: 2.5080, seams: 3, fighting: true },
  "castle.mall|the-big-building-inside/building-shell/building-shell-floor-0/shop:stickerPet/shop-stage:stickerPet/kiosk:stickerPet/<Mesh:BoxGeometry>|the-big-building-inside/building-shell/building-shell-floor-0/shop:stickerPet/shop-stage:stickerPet/unit-placeholder/<Mesh:BoxGeometry>": { area: 2.5080, seams: 3, fighting: true },
  "castle.mall|the-big-building-inside/building-shell/building-shell-floor-0/shop:surpriseEgg/shop-stage:surpriseEgg/kiosk:surpriseEgg/<Mesh:BoxGeometry>|the-big-building-inside/building-shell/building-shell-floor-0/shop:surpriseEgg/shop-stage:surpriseEgg/unit-placeholder/<Mesh:BoxGeometry>": { area: 2.5080, seams: 3, fighting: true },
  "castle.mall|the-big-building-inside/building-shell/building-shell-floor-0/shop:toy/shop-stage:toy/kiosk:toy/<Mesh:BoxGeometry>|the-big-building-inside/building-shell/building-shell-floor-0/shop:toy/shop-stage:toy/unit-placeholder/<Mesh:BoxGeometry>": { area: 2.5080, seams: 3, fighting: true },
  "garden|entrance/entrance-road-gateway|garden/path-surface": { area: 2.4910, seams: 3, fighting: false },
  "garden|anchor-plots/anchor:waterFight/waterfight:plot/<Mesh:RoundedBoxGeometry>|anchor-plots/anchor:waterFight/waterfight:plot/<Mesh:RoundedBoxGeometry>/<Mesh:RoundedBoxGeometry>": { area: 2.4824, seams: 1, fighting: false },
  "hotel.lobby|the-land-hotel-inside/hotel:hotel.lobby/hotel.artwork/<Mesh:BoxGeometry>|the-land-hotel-inside/hotel:hotel.lobby/hotel.artwork/<Mesh:PlaneGeometry>": { area: 2.2800, seams: 1, fighting: false },
  "hotel.lobby|the-land-hotel-inside/hotel:hotel.lobby/hotel.column/<Mesh:CylinderGeometry>|the-land-hotel-inside/hotel:hotel.lobby/hotel.column/<Mesh:CylinderGeometry>": { area: 2.0203, seams: 1, fighting: true },
  "hotel.breakfast|the-land-hotel-inside/hotel:hotel.breakfast/hotel.artwork/<Mesh:BoxGeometry>/<Mesh:BoxGeometry>|the-land-hotel-inside/hotel:hotel.breakfast/hotel.wall": { area: 1.9200, seams: 1, fighting: false },
  "hotel.garden|the-land-hotel-inside/hotel:hotel.garden/hotel.artwork/<Mesh:BoxGeometry>/<Mesh:BoxGeometry>|the-land-hotel-inside/hotel:hotel.garden/hotel.wall": { area: 1.9200, seams: 1, fighting: false },
  "castle.hall|the-big-building-inside/building-shell/building-shell-floor-1/castle-decor-1/castle-paintings-1/castle-painting-1-dragon/<Mesh:BufferGeometry>|the-big-building-inside/building-shell/building-shell-floor-1/castle-decor-1/castle-paintings-1/castle-painting-1-dragon/<Mesh:PlaneGeometry>": { area: 1.8750, seams: 1, fighting: false },
  "castle.mall|the-big-building-inside/building-shell/building-shell-floor-0/castle-decor-0/castle-paintings-0/castle-painting-0-dragon/<Mesh:BufferGeometry>|the-big-building-inside/building-shell/building-shell-floor-0/castle-decor-0/castle-paintings-0/castle-painting-0-dragon/<Mesh:PlaneGeometry>": { area: 1.8750, seams: 1, fighting: false },
  "garden|railRace/railRace:race-ring/railRace:arch/railRace:finish-rainbow-leg-4-outer|railRace/railRace:race-ring/railRace:arch/railRace:finish-rainbow-leg-5-outer/<Mesh:CylinderGeometry>": { area: 1.8660, seams: 1, fighting: false },
  "garden|railRace/railRace:race-ring/railRace:arch/railRace:finish-rainbow-leg-3-outer|railRace/railRace:race-ring/railRace:arch/railRace:finish-rainbow-leg-4-outer/<Mesh:CylinderGeometry>": { area: 1.8652, seams: 1, fighting: false },
  "garden|railRace/railRace:race-ring/railRace:arch/railRace:finish-rainbow-leg-2-outer|railRace/railRace:race-ring/railRace:arch/railRace:finish-rainbow-leg-3-outer/<Mesh:CylinderGeometry>": { area: 1.8644, seams: 1, fighting: false },
  "garden|railRace/railRace:race-ring/railRace:arch/railRace:finish-rainbow-leg-1-outer|railRace/railRace:race-ring/railRace:arch/railRace:finish-rainbow-leg-2-outer/<Mesh:CylinderGeometry>": { area: 1.8636, seams: 1, fighting: false },
  "garden|railRace/railRace:race-ring/railRace:arch/railRace:finish-rainbow-leg-0-outer|railRace/railRace:race-ring/railRace:arch/railRace:finish-rainbow-leg-1-outer/<Mesh:CylinderGeometry>": { area: 1.8628, seams: 1, fighting: false },
  "hotel.suite|the-land-hotel-inside/hotel:hotel.suite/hotel.artwork/<Mesh:BoxGeometry>/<Mesh:BoxGeometry>|the-land-hotel-inside/hotel:hotel.suite/hotel.wall": { area: 1.7250, seams: 1, fighting: false },
  "garden|anchor-plots/anchor:building/the-big-building-outside/building-facade/castle-walls/castle-wall-upper|anchor-plots/anchor:building/the-big-building-outside/building-facade/cruiser-windows/cruiser-window-stones": { area: 1.6051, seams: 1, fighting: true },
  "hotel.garden|the-land-hotel-inside/hotel:hotel.garden/hotel.wall|the-land-hotel-inside/hotel:hotel.garden/hotel.wall": { area: 1.6000, seams: 3, fighting: true },
  "hotel.ocean|the-land-hotel-inside/hotel:hotel.ocean/hotel.wall|the-land-hotel-inside/hotel:hotel.ocean/hotel.wall": { area: 1.5500, seams: 3, fighting: true },
  "hotel.corridor|the-land-hotel-inside/hotel:hotel.corridor/hotel.wall|the-land-hotel-inside/hotel:hotel.corridor/hotel.wall": { area: 1.5000, seams: 3, fighting: true },
  "hotel.suite|the-land-hotel-inside/hotel:hotel.suite/hotel.wall|the-land-hotel-inside/hotel:hotel.suite/hotel.wall": { area: 1.5000, seams: 2, fighting: true },
  "hotel.breakfast|the-land-hotel-inside/hotel:hotel.breakfast/hotel.wall|the-land-hotel-inside/hotel:hotel.breakfast/hotel.wall": { area: 1.5000, seams: 3, fighting: true },
  "hotel.breakfast|the-land-hotel-inside/hotel:hotel.breakfast/hotel.artwork/<Mesh:BoxGeometry>|the-land-hotel-inside/hotel:hotel.breakfast/hotel.artwork/<Mesh:PlaneGeometry>": { area: 1.1700, seams: 1, fighting: false },
  "hotel.garden|the-land-hotel-inside/hotel:hotel.garden/hotel.artwork/<Mesh:BoxGeometry>|the-land-hotel-inside/hotel:hotel.garden/hotel.artwork/<Mesh:PlaneGeometry>": { area: 1.1700, seams: 1, fighting: false },
  "garden|anchor-plots/anchor:building/the-big-building-outside/building-facade/castle-walls/castle-wall-window|anchor-plots/anchor:building/the-big-building-outside/building-facade/cruiser-windows/cruiser-window-stones": { area: 1.0793, seams: 1, fighting: true },
  "castle.mall|the-big-building-inside/building-shell/building-shell-floor-0/toilets/<Mesh:BoxGeometry>|the-big-building-inside/building-shell/building-shell-floor-0/toilets/<Mesh:BoxGeometry>": { area: 1.0740, seams: 3, fighting: true },
  "hotel.suite|the-land-hotel-inside/hotel:hotel.suite/hotel.artwork/<Mesh:BoxGeometry>|the-land-hotel-inside/hotel:hotel.suite/hotel.artwork/<Mesh:PlaneGeometry>": { area: 1.0200, seams: 1, fighting: false },
  "hotel.lobby|the-land-hotel-inside/hotel:hotel.lobby/hotel:lobby/overhang/hotel.sofa/<Mesh:BoxGeometry>/<Mesh:BoxGeometry>|the-land-hotel-inside/hotel:hotel.lobby/hotel:lobby/overhang/hotel.sofa/<Mesh:BoxGeometry>/<Mesh:BoxGeometry>": { area: 0.7072, seams: 3, fighting: true },
  "hotel.lobby|the-land-hotel-inside/hotel:hotel.lobby/hotel.sofa/<Mesh:BoxGeometry>/<Mesh:BoxGeometry>|the-land-hotel-inside/hotel:hotel.lobby/hotel.sofa/<Mesh:BoxGeometry>/<Mesh:BoxGeometry>": { area: 0.7072, seams: 3, fighting: true },
  "garden|railRace/railRace:race-ring/railRace:sleepers|railRace/railRace:walk-past-ring/railRace:sleepers": { area: 0.6854, seams: 3, fighting: false },
  "castle.hall|the-big-building-inside/building-shell/building-shell-floor-1/corner-pillars|the-big-building-inside/building-shell/building-shell-floor-1/trim-1": { area: 0.6724, seams: 1, fighting: true },
  "castle.mall|the-big-building-inside/building-shell/building-shell-floor-0/corner-pillars|the-big-building-inside/building-shell/building-shell-floor-0/trim-0": { area: 0.6724, seams: 1, fighting: true },
  "hotel.lobby|the-land-hotel-inside/hotel:hotel.lobby/hotel:lobby/overhang/<Mesh:BoxGeometry>|the-land-hotel-inside/hotel:hotel.lobby/hotel:lobby/overhang/hotel.bridgeRailing/bridge-rail-plinth": { area: 0.5702, seams: 2, fighting: true },
  "castle.hall|the-big-building-inside/building-shell/building-shell-floor-1/castle-decor-1/castle-furniture-1/castle.bench/bench-plank|the-big-building-inside/building-shell/building-shell-floor-1/castle-decor-1/castle-furniture-1/castle.bench/bench-plank/<Mesh:BufferGeometry>": { area: 0.4517, seams: 2, fighting: false },
  "garden|railRace/railRace:race-ring/railRace:arch/railRace:finish-rainbow-leg-4-inner/<Mesh:CylinderGeometry>|railRace/railRace:race-ring/railRace:arch/railRace:finish-rainbow-leg-5-inner": { area: 0.4420, seams: 1, fighting: false },
  "garden|railRace/railRace:race-ring/railRace:arch/railRace:finish-rainbow-leg-3-inner/<Mesh:CylinderGeometry>|railRace/railRace:race-ring/railRace:arch/railRace:finish-rainbow-leg-4-inner": { area: 0.4415, seams: 1, fighting: false },
  "garden|railRace/railRace:race-ring/railRace:arch/railRace:finish-rainbow-leg-2-inner/<Mesh:CylinderGeometry>|railRace/railRace:race-ring/railRace:arch/railRace:finish-rainbow-leg-3-inner": { area: 0.4411, seams: 1, fighting: false },
  "garden|railRace/railRace:race-ring/railRace:arch/railRace:finish-rainbow-leg-1-inner/<Mesh:CylinderGeometry>|railRace/railRace:race-ring/railRace:arch/railRace:finish-rainbow-leg-2-inner": { area: 0.4408, seams: 1, fighting: false },
  "garden|railRace/railRace:race-ring/railRace:arch/railRace:finish-rainbow-leg-0-inner/<Mesh:CylinderGeometry>|railRace/railRace:race-ring/railRace:arch/railRace:finish-rainbow-leg-1-inner": { area: 0.4405, seams: 1, fighting: false },
  "hotel.lobby|the-land-hotel-inside/hotel:hotel.lobby/hotel.wall|the-land-hotel-inside/hotel:hotel.lobby/hotel:lobby/overhang/hotel.sconce/<Mesh:BoxGeometry>/<Mesh:BoxGeometry>": { area: 0.4400, seams: 1, fighting: false },
  "garden|railRace/railRace:walk-past-ring/<Mesh:BoxGeometry>|railRace/railRace:walk-past-ring/railRace:duck-bars": { area: 0.4400, seams: 1, fighting: false },
  "garden|garden/boundary-wall/<Mesh:BoxGeometry>|garden/boundary-wall/boundary-blocks": { area: 0.4340, seams: 3, fighting: false },
  "garden|park-train/railway-bridges/bridge-2.0/shell|park-train/railway-bridges/bridge-2.0/wallTop": { area: 0.3869, seams: 18, fighting: true },
  "castle.hall|the-big-building-inside/building-shell/building-shell-floor-1/lift-alcove/hotel.liftDial/lift-dial|the-big-building-inside/building-shell/building-shell-floor-1/lift-alcove/hotel.liftDial/lift-dial-face": { area: 0.3652, seams: 1, fighting: false },
  "castle.mall|the-big-building-inside/building-shell/building-shell-floor-0/lift-alcove/hotel.liftDial/lift-dial|the-big-building-inside/building-shell/building-shell-floor-0/lift-alcove/hotel.liftDial/lift-dial-face": { area: 0.3652, seams: 1, fighting: false },
  "castle.roof|the-big-building-inside/building-shell/building-shell-floor-2/lift-alcove/hotel.liftDial/lift-dial|the-big-building-inside/building-shell/building-shell-floor-2/lift-alcove/hotel.liftDial/lift-dial-face": { area: 0.3652, seams: 1, fighting: false },
  "hotel.breakfast|the-land-hotel-inside/hotel:hotel.breakfast/lift-alcove/hotel.liftDial/lift-dial|the-land-hotel-inside/hotel:hotel.breakfast/lift-alcove/hotel.liftDial/lift-dial-face": { area: 0.3652, seams: 1, fighting: false },
  "hotel.corridor|the-land-hotel-inside/hotel:hotel.corridor/lift-alcove/hotel.liftDial/lift-dial|the-land-hotel-inside/hotel:hotel.corridor/lift-alcove/hotel.liftDial/lift-dial-face": { area: 0.3652, seams: 1, fighting: false },
  "hotel.garden|the-land-hotel-inside/hotel:hotel.garden/lift-alcove/hotel.liftDial/lift-dial|the-land-hotel-inside/hotel:hotel.garden/lift-alcove/hotel.liftDial/lift-dial-face": { area: 0.3652, seams: 1, fighting: false },
  "hotel.lobby|the-land-hotel-inside/hotel:hotel.lobby/lift-alcove/hotel.liftDial/lift-dial|the-land-hotel-inside/hotel:hotel.lobby/lift-alcove/hotel.liftDial/lift-dial-face": { area: 0.3652, seams: 1, fighting: false },
  "hotel.ocean|the-land-hotel-inside/hotel:hotel.ocean/lift-alcove/hotel.liftDial/lift-dial|the-land-hotel-inside/hotel:hotel.ocean/lift-alcove/hotel.liftDial/lift-dial-face": { area: 0.3652, seams: 1, fighting: false },
  "hotel.lobby|the-land-hotel-inside/hotel:hotel.lobby/hotel.sofa/<Mesh:BoxGeometry>|the-land-hotel-inside/hotel:hotel.lobby/hotel.sofa/<Mesh:BoxGeometry>": { area: 0.3468, seams: 1, fighting: true },
  "hotel.lobby|the-land-hotel-inside/hotel:hotel.lobby/hotel:lobby/overhang/hotel.sofa/<Mesh:BoxGeometry>|the-land-hotel-inside/hotel:hotel.lobby/hotel:lobby/overhang/hotel.sofa/<Mesh:BoxGeometry>": { area: 0.3468, seams: 1, fighting: true },
  "castle.mall|the-big-building-inside/building-shell/building-shell-floor-0/shop:hat/shop-stage:hat/kiosk:hat/stall-dress:hat/<Group>/<Mesh:BoxGeometry>|the-big-building-inside/building-shell/building-shell-floor-0/shop:hat/shop-stage:hat/kiosk:hat/stall-dress:hat/<Group>/<Mesh:BoxGeometry>": { area: 0.3360, seams: 2, fighting: true },
  "hotel.lobby|the-land-hotel-inside/hotel:hotel.lobby/hotel.sconce/<Mesh:BoxGeometry>/<Mesh:BoxGeometry>|the-land-hotel-inside/hotel:hotel.lobby/hotel.wall": { area: 0.3300, seams: 2, fighting: false },
  "garden|anchor-plots/anchor:hotel/the-land-hotel-outside/hotel.tower/tower-door-jamb/<Mesh:BufferGeometry>|anchor-plots/anchor:hotel/the-land-hotel-outside/hotel.tower/tower-main/<Mesh:BufferGeometry>": { area: 0.3261, seams: 1, fighting: true },
  "garden|park-train/railway-bridges/bridge-142.0/shell|park-train/railway-bridges/bridge-142.0/wallTop": { area: 0.3100, seams: 20, fighting: true },
  "garden|park-train/railway-bridges/bridge-0.0/shell|park-train/railway-bridges/bridge-0.0/wallTop": { area: 0.3096, seams: 21, fighting: true },
  "castle.roof|the-big-building-inside/building-shell/building-shell-floor-2/deck-benches-2|the-big-building-inside/building-shell/building-shell-floor-2/trampoline/<Mesh:TorusGeometry>": { area: 0.2821, seams: 1, fighting: false },
  "hotel.breakfast|the-land-hotel-inside/hotel:hotel.breakfast/hotel.breakfastTable/table-leg|the-land-hotel-inside/hotel:hotel.breakfast/hotel.breakfastTable/table-top/<Mesh:BufferGeometry>": { area: 0.2762, seams: 1, fighting: false },
  "hotel.suite|the-land-hotel-inside/hotel:hotel.suite/hotel.napBlanket/<Mesh:BoxGeometry>/<Mesh:BoxGeometry>|the-land-hotel-inside/hotel:hotel.suite/hotel.napBlanket/<Mesh:BoxGeometry>/<Mesh:BoxGeometry>": { area: 0.2700, seams: 2, fighting: true },
  "garden|park-train/railway-bridges/bridge-62.0/shell|park-train/railway-bridges/bridge-62.0/wallTop": { area: 0.2699, seams: 19, fighting: true },
  "garden|park-train/railway-bridges/bridge-16.0/shell|park-train/railway-bridges/bridge-16.0/wallTop": { area: 0.2388, seams: 14, fighting: true },
  "garden|park-train/railway-bridges/bridge-20.0/shell|park-train/railway-bridges/bridge-20.0/wallTop": { area: 0.2325, seams: 18, fighting: true },
  "hotel.corridor|the-land-hotel-inside/hotel:hotel.corridor/hotel.yoursDoor/door-leaf/<Mesh:BufferGeometry>|the-land-hotel-inside/hotel:hotel.corridor/hotel.yoursDoor/door-plaque/<Mesh:BufferGeometry>": { area: 0.2303, seams: 1, fighting: false },
  "garden|garden/terrain|park-train/railway-bridges/bridge-2.0/wallTop": { area: 0.2295, seams: 1, fighting: false },
  "garden|park-train/railway-bridges/bridge-244.0/shell|park-train/railway-bridges/bridge-244.0/wallTop": { area: 0.2295, seams: 20, fighting: true },
  "garden|park-train/railway-bridges/bridge-224.0/shell|park-train/railway-bridges/bridge-224.0/wallTop": { area: 0.2291, seams: 19, fighting: true },
  "garden|park-train/railway-bridges/bridge-200.0/shell|park-train/railway-bridges/bridge-200.0/wallTop": { area: 0.2287, seams: 18, fighting: true },
  "garden|park-train/railway-bridges/bridge-12.0/shell|park-train/railway-bridges/bridge-12.0/wallTop": { area: 0.2277, seams: 19, fighting: true },
  "hotel.garden|the-land-hotel-inside/hotel:hotel.garden/hotel.sconce/<Mesh:BoxGeometry>/<Mesh:BoxGeometry>|the-land-hotel-inside/hotel:hotel.garden/hotel.wall": { area: 0.2200, seams: 2, fighting: false },
  "hotel.corridor|the-land-hotel-inside/hotel:hotel.corridor/hotel.sconce/<Mesh:BoxGeometry>/<Mesh:BoxGeometry>|the-land-hotel-inside/hotel:hotel.corridor/hotel.wall": { area: 0.2200, seams: 1, fighting: false },
  "hotel.ocean|the-land-hotel-inside/hotel:hotel.ocean/hotel.sconce/<Mesh:BoxGeometry>/<Mesh:BoxGeometry>|the-land-hotel-inside/hotel:hotel.ocean/hotel.wall": { area: 0.2200, seams: 1, fighting: false },
  "hotel.suite|the-land-hotel-inside/hotel:hotel.suite/hotel.sconce/<Mesh:BoxGeometry>/<Mesh:BoxGeometry>|the-land-hotel-inside/hotel:hotel.suite/hotel.wall": { area: 0.2200, seams: 2, fighting: false },
  "hotel.breakfast|the-land-hotel-inside/hotel:hotel.breakfast/hotel.sconce/<Mesh:BoxGeometry>/<Mesh:BoxGeometry>|the-land-hotel-inside/hotel:hotel.breakfast/hotel.wall": { area: 0.2200, seams: 1, fighting: false },
  "garden|park-train/railway-bridges/bridge-234.0/shell|park-train/railway-bridges/bridge-234.0/wallTop": { area: 0.1974, seams: 15, fighting: true },
  "garden|park-train/railway-bridges/bridge-30.0/shell|park-train/railway-bridges/bridge-30.0/wallTop": { area: 0.1973, seams: 16, fighting: true },
  "garden|park-train/railway-bridges/bridge-312.0/shell|park-train/railway-bridges/bridge-312.0/wallTop": { area: 0.1970, seams: 16, fighting: true },
  "garden|park-train/railway-bridges/bridge-4.0/shell|park-train/railway-bridges/bridge-4.0/wallTop": { area: 0.1957, seams: 16, fighting: true },
  "garden|park-train/railway-bridges/bridge-104.0/shell|park-train/railway-bridges/bridge-104.0/wallTop": { area: 0.1951, seams: 15, fighting: true },
  "garden|park-train/railway-bridges/bridge-284.0/shell|park-train/railway-bridges/bridge-284.0/wallTop": { area: 0.1911, seams: 20, fighting: true },
  "hotel.suite|the-land-hotel-inside/hotel:hotel.suite/hotel.petBed/petbed-blanket/<Mesh:BufferGeometry>|the-land-hotel-inside/hotel:hotel.suite/hotel.petBed/petbed-bolster": { area: 0.1855, seams: 1, fighting: false },
  "garden|garden/terrain|park-train/railway-bridges/bridge-200.0/wallTop": { area: 0.1797, seams: 1, fighting: false },
  "garden|entrance/cat-bus-arrival/cat-bus/chassis/cat-bus-step/<Mesh:RoundedBoxGeometry>|entrance/cat-bus-arrival/cat-bus/chassis/cat-bus-step/cat-bus-step-tread": { area: 0.1787, seams: 31, fighting: true },
  "garden|garden/terrain|park-train/railway-bridges/bridge-20.0/wallTop": { area: 0.1778, seams: 1, fighting: false },
  "hotel.garden|the-land-hotel-inside/hotel:hotel.garden/hotel.sofa/<Mesh:BoxGeometry>/<Mesh:BoxGeometry>|the-land-hotel-inside/hotel:hotel.garden/hotel.sofa/<Mesh:BoxGeometry>/<Mesh:BoxGeometry>": { area: 0.1768, seams: 3, fighting: true },
  "hotel.suite|the-land-hotel-inside/hotel:hotel.suite/hotel.sofa/<Mesh:BoxGeometry>|the-land-hotel-inside/hotel:hotel.suite/hotel.sofa/<Mesh:BoxGeometry>": { area: 0.1768, seams: 2, fighting: true },
  "hotel.ocean|the-land-hotel-inside/hotel:hotel.ocean/hotel.sofa/<Mesh:BoxGeometry>/<Mesh:BoxGeometry>|the-land-hotel-inside/hotel:hotel.ocean/hotel.sofa/<Mesh:BoxGeometry>/<Mesh:BoxGeometry>": { area: 0.1768, seams: 3, fighting: true },
  "castle.hall|the-big-building-inside/building-shell/building-shell-floor-1/lift-alcove/hotel.liftDoors/lift-door-left/<Mesh:BufferGeometry>|the-big-building-inside/building-shell/building-shell-floor-1/lift-alcove/hotel.liftDoors/lift-door-right": { area: 0.1732, seams: 1, fighting: false },
  "castle.mall|the-big-building-inside/building-shell/building-shell-floor-0/lift-alcove/hotel.liftDoors/lift-door-left/<Mesh:BufferGeometry>|the-big-building-inside/building-shell/building-shell-floor-0/lift-alcove/hotel.liftDoors/lift-door-right": { area: 0.1732, seams: 1, fighting: false },
  "castle.roof|the-big-building-inside/building-shell/building-shell-floor-2/lift-alcove/hotel.liftDoors/lift-door-left/<Mesh:BufferGeometry>|the-big-building-inside/building-shell/building-shell-floor-2/lift-alcove/hotel.liftDoors/lift-door-right": { area: 0.1732, seams: 1, fighting: false },
  "hotel.breakfast|the-land-hotel-inside/hotel:hotel.breakfast/lift-alcove/hotel.liftDoors/lift-door-left/<Mesh:BufferGeometry>|the-land-hotel-inside/hotel:hotel.breakfast/lift-alcove/hotel.liftDoors/lift-door-right": { area: 0.1732, seams: 1, fighting: false },
  "hotel.corridor|the-land-hotel-inside/hotel:hotel.corridor/lift-alcove/hotel.liftDoors/lift-door-left/<Mesh:BufferGeometry>|the-land-hotel-inside/hotel:hotel.corridor/lift-alcove/hotel.liftDoors/lift-door-right": { area: 0.1732, seams: 1, fighting: false },
  "hotel.garden|the-land-hotel-inside/hotel:hotel.garden/lift-alcove/hotel.liftDoors/lift-door-left/<Mesh:BufferGeometry>|the-land-hotel-inside/hotel:hotel.garden/lift-alcove/hotel.liftDoors/lift-door-right": { area: 0.1732, seams: 1, fighting: false },
  "hotel.lobby|the-land-hotel-inside/hotel:hotel.lobby/lift-alcove/hotel.liftDoors/lift-door-left/<Mesh:BufferGeometry>|the-land-hotel-inside/hotel:hotel.lobby/lift-alcove/hotel.liftDoors/lift-door-right": { area: 0.1732, seams: 1, fighting: false },
  "hotel.ocean|the-land-hotel-inside/hotel:hotel.ocean/lift-alcove/hotel.liftDoors/lift-door-left/<Mesh:BufferGeometry>|the-land-hotel-inside/hotel:hotel.ocean/lift-alcove/hotel.liftDoors/lift-door-right": { area: 0.1732, seams: 1, fighting: false },
  "garden|park-train/railway-bridges/bridge-18.0/shell|park-train/railway-bridges/bridge-18.0/wallTop": { area: 0.1584, seams: 16, fighting: true },
  "garden|park-train/railway-bridges/bridge-56.0/shell|park-train/railway-bridges/bridge-56.0/wallTop": { area: 0.1581, seams: 14, fighting: true },
  "hotel.corridor|the-land-hotel-inside/hotel:hotel.corridor/hotel.yoursDoor/door-frame|the-land-hotel-inside/hotel:hotel.corridor/hotel.yoursDoor/door-leaf/<Mesh:BufferGeometry>": { area: 0.1544, seams: 3, fighting: false },
  "hotel.corridor|the-land-hotel-inside/hotel:hotel.corridor/hotel.yoursDoor/door-frame/<Mesh:BufferGeometry>|the-land-hotel-inside/hotel:hotel.corridor/hotel.yoursDoor/door-leaf": { area: 0.1544, seams: 3, fighting: true },
  "garden|stalls/stall:spookyHouse/<Group>/<Mesh:BoxGeometry>|stalls/stall:spookyHouse/<Group>/<Mesh:CylinderGeometry>": { area: 0.1454, seams: 2, fighting: false },
  "garden|stalls/stall:skyCruiser/<Group>/<Mesh:BoxGeometry>|stalls/stall:skyCruiser/<Group>/<Mesh:CylinderGeometry>": { area: 0.1438, seams: 2, fighting: false },
  "garden|stalls/stall:spaceFerrisWheel/<Group>/<Mesh:BoxGeometry>|stalls/stall:spaceFerrisWheel/<Group>/<Mesh:CylinderGeometry>": { area: 0.1433, seams: 2, fighting: false },
  "garden|garden/terrain|park-train/railway-bridges/bridge-2.0/shell": { area: 0.1396, seams: 1, fighting: false },
  "castle.hall|the-big-building-inside/building-shell/building-shell-floor-1/castle-decor-1/castle-furniture-1/castle.chest/chest-bands/<Mesh:BufferGeometry>|the-big-building-inside/building-shell/building-shell-floor-1/castle-decor-1/castle-furniture-1/castle.chest/chest-body/<Mesh:BufferGeometry>": { area: 0.1350, seams: 1, fighting: false },
  "hotel.lobby|the-land-hotel-inside/hotel:hotel.lobby/hotel:lobby/overhang/hotel.bridgeNewel/bridge-newel/<Mesh:BufferGeometry>|the-land-hotel-inside/hotel:hotel.lobby/hotel:lobby/overhang/hotel.bridgeRailing/bridge-rail-plinth/<Mesh:BufferGeometry>": { area: 0.1338, seams: 1, fighting: false },
  "hotel.suite|the-land-hotel-inside/hotel:hotel.suite/hotel.sofa/<Mesh:BoxGeometry>/<Mesh:BoxGeometry>|the-land-hotel-inside/hotel:hotel.suite/hotel.sofa/<Mesh:BoxGeometry>/<Mesh:BoxGeometry>": { area: 0.1326, seams: 2, fighting: true },
  "castle.hall|the-big-building-inside/building-shell/building-shell-floor-1/castle-decor-1/castle-furniture-1/castle.chest/chest-bands|the-big-building-inside/building-shell/building-shell-floor-1/castle-decor-1/castle-furniture-1/castle.chest/chest-body": { area: 0.1320, seams: 1, fighting: true },
  "garden|stalls/stall:waterFight/<Group>/<Mesh:BoxGeometry>|stalls/stall:waterFight/<Group>/<Mesh:CylinderGeometry>": { area: 0.1284, seams: 2, fighting: false },
  "hotel.suite|the-land-hotel-inside/hotel:hotel.suite/hotel.bed/bed-blanket/<Mesh:BufferGeometry>|the-land-hotel-inside/hotel:hotel.suite/hotel.napBlanket/<Mesh:BoxGeometry>/<Mesh:BoxGeometry>": { area: 0.1170, seams: 1, fighting: false },
  "hotel.breakfast|the-land-hotel-inside/hotel:hotel.breakfast/hotel.artwork/<Mesh:BoxGeometry>/<Mesh:BoxGeometry>|the-land-hotel-inside/hotel:hotel.breakfast/hotel.sconce/<Mesh:BoxGeometry>/<Mesh:BoxGeometry>": { area: 0.1100, seams: 1, fighting: true },
  "garden|garden/terrain|park-train/railway-bridges/bridge-0.0/wallTop": { area: 0.1079, seams: 1, fighting: false },
  "garden|garden/terrain|park-train/railway-bridges/bridge-20.0/shell": { area: 0.1067, seams: 1, fighting: false },
  "garden|garden/terrain|park-train/railway-bridges/bridge-200.0/shell": { area: 0.1058, seams: 1, fighting: false },
  "garden|park-train/train-locomotive/<Group>/<Mesh:CylinderGeometry>|park-train/train-locomotive/<Group>/<Mesh:CylinderGeometry>": { area: 0.1051, seams: 1, fighting: false },
  "garden|facePaintStall/<Mesh:CylinderGeometry>/<Mesh:CylinderGeometry>|facePaintStall/<Mesh:RoundedBoxGeometry>": { area: 0.0971, seams: 1, fighting: false },
  "hotel.suite|the-land-hotel-inside/hotel:hotel.suite/hotel.bed/bed-blanket|the-land-hotel-inside/hotel:hotel.suite/hotel.napBlanket/<Mesh:BoxGeometry>": { area: 0.0917, seams: 1, fighting: true },
  "hotel.lobby|the-land-hotel-inside/hotel:hotel.lobby/hotel.grandStaircase.left/stair-left-tread|the-land-hotel-inside/hotel:hotel.lobby/hotel:lobby/overhang/hotel.landingNosing/landing-nose": { area: 0.0905, seams: 1, fighting: false },
  "hotel.lobby|the-land-hotel-inside/hotel:hotel.lobby/hotel.grandStaircase.right/stair-right-tread|the-land-hotel-inside/hotel:hotel.lobby/hotel:lobby/overhang/hotel.landingNosing/landing-nose": { area: 0.0904, seams: 1, fighting: false },
  "hotel.garden|the-land-hotel-inside/hotel:hotel.garden/hotel.sofa/<Mesh:BoxGeometry>|the-land-hotel-inside/hotel:hotel.garden/hotel.sofa/<Mesh:BoxGeometry>": { area: 0.0867, seams: 1, fighting: true },
  "hotel.ocean|the-land-hotel-inside/hotel:hotel.ocean/hotel.sofa/<Mesh:BoxGeometry>|the-land-hotel-inside/hotel:hotel.ocean/hotel.sofa/<Mesh:BoxGeometry>": { area: 0.0867, seams: 1, fighting: true },
  "hotel.suite|the-land-hotel-inside/hotel:hotel.suite/<Mesh:BoxGeometry>|the-land-hotel-inside/hotel:hotel.suite/<Mesh:BoxGeometry>": { area: 0.0864, seams: 1, fighting: true },
  "hotel.suite|the-land-hotel-inside/hotel:hotel.suite/hotel.napBlanket/<Mesh:BoxGeometry>|the-land-hotel-inside/hotel:hotel.suite/hotel.napBlanket/<Mesh:BoxGeometry>": { area: 0.0810, seams: 1, fighting: true },
  "garden|stalls/stall:dodgems/<Group>/<Mesh:BoxGeometry>|stalls/stall:dodgems/<Group>/<Mesh:CylinderGeometry>": { area: 0.0798, seams: 2, fighting: false },
  "hotel.lobby|the-land-hotel-inside/hotel:hotel.lobby/hotel.breakfastTable/table-leg|the-land-hotel-inside/hotel:hotel.lobby/hotel.breakfastTable/table-top/<Mesh:BufferGeometry>": { area: 0.0789, seams: 1, fighting: false },
  "garden|stalls/stall:railRacer/<Group>/<Mesh:BoxGeometry>|stalls/stall:railRacer/<Group>/<Mesh:CylinderGeometry>": { area: 0.0704, seams: 2, fighting: false },
  "hotel.lobby|the-land-hotel-inside/hotel:hotel.lobby/hotel:lobby/overhang/hotel.bridgeNewel/bridge-newel|the-land-hotel-inside/hotel:hotel.lobby/hotel:lobby/overhang/hotel.bridgeRailing/bridge-rail-hand": { area: 0.0635, seams: 1, fighting: true },
  "garden|garden/terrain|park-train/railway-bridges/bridge-0.0/shell": { area: 0.0619, seams: 1, fighting: false },
  "garden|park-train/train-carriage-2/<Mesh:BoxGeometry>|park-train/train-carriage-2/<Mesh:BoxGeometry>": { area: 0.0616, seams: 2, fighting: true },
  "garden|park-train/train-carriage-1/<Mesh:BoxGeometry>|park-train/train-carriage-1/<Mesh:BoxGeometry>": { area: 0.0616, seams: 2, fighting: true },
  "garden|park-train/train-carriage-0/<Mesh:BoxGeometry>|park-train/train-carriage-0/<Mesh:BoxGeometry>": { area: 0.0616, seams: 2, fighting: true },
  "garden|scenery/wooden-walls/<Mesh:BoxGeometry>|scenery/wooden-walls/<Mesh:BoxGeometry>": { area: 0.0588, seams: 1, fighting: true },
  "hotel.ocean|the-land-hotel-inside/hotel:hotel.ocean/hotel.sconce/<Mesh:CylinderGeometry>|the-land-hotel-inside/hotel:hotel.ocean/hotel.wall": { area: 0.0566, seams: 1, fighting: false },
  "hotel.garden|the-land-hotel-inside/hotel:hotel.garden/hotel.artwork/<Mesh:BoxGeometry>/<Mesh:BoxGeometry>|the-land-hotel-inside/hotel:hotel.garden/hotel.sconce/<Mesh:BoxGeometry>/<Mesh:BoxGeometry>": { area: 0.0550, seams: 1, fighting: true },
  "hotel.suite|the-land-hotel-inside/hotel:hotel.suite/hotel.breakfastTable/table-top|the-land-hotel-inside/hotel:hotel.suite/hotel.gameBoy/gameboy-body/<Mesh:BufferGeometry>": { area: 0.0538, seams: 1, fighting: false },
  "garden|garden/boundary-wall/boundary-blocks|park-train/rail-fence/<Mesh:BoxGeometry>": { area: 0.0507, seams: 1, fighting: false },
  "garden|railRace/railRace:cart/hopper/<Mesh:BufferGeometry>|railRace/railRace:cart/pet-seat/<Mesh:BufferGeometry>": { area: 0.0504, seams: 4, fighting: false },
  "hotel.lobby|the-land-hotel-inside/hotel:hotel.lobby/hotel.grandStaircase.right/stair-right-stringer/<Mesh:BufferGeometry>|the-land-hotel-inside/hotel:hotel.lobby/hotel.grandStaircase.right/stair-right-tread/<Mesh:BufferGeometry>": { area: 0.0503, seams: 2, fighting: false },
  "hotel.lobby|the-land-hotel-inside/hotel:hotel.lobby/hotel.grandStaircase.left/stair-left-stringer/<Mesh:BufferGeometry>|the-land-hotel-inside/hotel:hotel.lobby/hotel.grandStaircase.left/stair-left-tread/<Mesh:BufferGeometry>": { area: 0.0503, seams: 3, fighting: false },
  "garden|garden/terrain|stalls/stall:skyCruiser/<Mesh:CylinderGeometry>/<Mesh:CylinderGeometry>": { area: 0.0497, seams: 1, fighting: false },
  "garden|garden/terrain|stalls/stall:dodgems/<Mesh:CylinderGeometry>/<Mesh:CylinderGeometry>": { area: 0.0482, seams: 1, fighting: false },
  "hotel.lobby|the-land-hotel-inside/hotel:hotel.lobby/hotel.straightStaircase/stair-straight-stringer/<Mesh:BufferGeometry>|the-land-hotel-inside/hotel:hotel.lobby/hotel.straightStaircase/stair-straight-tread/<Mesh:BufferGeometry>": { area: 0.0481, seams: 2, fighting: false },
  "garden|scenery/wooden-walls/<Mesh:BoxGeometry>|scenery/wooden-walls/<Mesh:CylinderGeometry>": { area: 0.0450, seams: 1, fighting: false },
  "hotel.lobby|the-land-hotel-inside/hotel:hotel.lobby/hotel.straightStaircase/stair-straight-newel/<Mesh:BufferGeometry>|the-land-hotel-inside/hotel:hotel.lobby/hotel.straightStaircase/stair-straight-stringer/<Mesh:BufferGeometry>": { area: 0.0435, seams: 1, fighting: false },
  "hotel.suite|the-land-hotel-inside/hotel:hotel.suite/hotel.breakfastTable/table-leg|the-land-hotel-inside/hotel:hotel.suite/hotel.breakfastTable/table-top/<Mesh:BufferGeometry>": { area: 0.0395, seams: 1, fighting: false },
  "castle.mall|the-big-building-inside/building-shell/building-shell-floor-0/shop:iceCream/shop-stage:iceCream/kiosk:iceCream/stall-dress:iceCream/<Group>/<Mesh:BoxGeometry>|the-big-building-inside/building-shell/building-shell-floor-0/shop:iceCream/shop-stage:iceCream/kiosk:iceCream/stall-dress:iceCream/<Group>/<Mesh:BoxGeometry>": { area: 0.0308, seams: 1, fighting: true },
  "garden|scenery/wooden-walls/<Mesh:SphereGeometry>|scenery/wooden-walls/<Mesh:SphereGeometry>": { area: 0.0305, seams: 40, fighting: true },
  "hotel.suite|the-land-hotel-inside/hotel:hotel.suite/hotel.artwork/<Mesh:BoxGeometry>/<Mesh:BoxGeometry>|the-land-hotel-inside/hotel:hotel.suite/hotel.sconce/<Mesh:BoxGeometry>/<Mesh:BoxGeometry>": { area: 0.0300, seams: 1, fighting: true },
  "garden|facePaintStall/<Mesh:CylinderGeometry>/<Mesh:CylinderGeometry>|garden/terrain": { area: 0.0280, seams: 1, fighting: false },
  "hotel.lobby|the-land-hotel-inside/hotel:hotel.lobby/hotel.wall|the-land-hotel-inside/hotel:hotel.lobby/hotel:lobby/overhang/hotel.bridgeRailing/bridge-rail-plinth": { area: 0.0251, seams: 1, fighting: true },
  "hotel.lobby|the-land-hotel-inside/hotel:hotel.lobby/hotel.receptionDesk/desk-counter/<Mesh:BufferGeometry>|the-land-hotel-inside/hotel:hotel.lobby/hotel.receptionDesk/desk-front/<Mesh:BufferGeometry>": { area: 0.0247, seams: 1, fighting: true },
  "hotel.lobby|the-land-hotel-inside/hotel:hotel.lobby/hotel.receptionDesk/desk-counter|the-land-hotel-inside/hotel:hotel.lobby/hotel.receptionDesk/desk-front": { area: 0.0247, seams: 1, fighting: true },
  "hotel.lobby|the-land-hotel-inside/hotel:hotel.lobby/hotel.grandStaircase.left/stair-left-newel/<Mesh:BufferGeometry>|the-land-hotel-inside/hotel:hotel.lobby/hotel.grandStaircase.left/stair-left-stringer/<Mesh:BufferGeometry>": { area: 0.0218, seams: 1, fighting: false },
  "hotel.lobby|the-land-hotel-inside/hotel:hotel.lobby/hotel.grandStaircase.right/stair-right-newel/<Mesh:BufferGeometry>|the-land-hotel-inside/hotel:hotel.lobby/hotel.grandStaircase.right/stair-right-stringer/<Mesh:BufferGeometry>": { area: 0.0218, seams: 1, fighting: false },
  "hotel.lobby|the-land-hotel-inside/hotel:hotel.lobby/hotel.straightStaircase/stair-straight-newel|the-land-hotel-inside/hotel:hotel.lobby/hotel.straightStaircase/stair-straight-rail": { area: 0.0209, seams: 1, fighting: true },
  "hotel.lobby|the-land-hotel-inside/hotel:hotel.lobby/hotel:lobby/overhang/<Mesh:BoxGeometry>|the-land-hotel-inside/hotel:hotel.lobby/hotel:lobby/overhang/hotel.landingNosing/landing-nose": { area: 0.0190, seams: 1, fighting: true },
  "garden|park-train/railway-bridges/bridge-20.0/deck|park-train/railway-bridges/bridge-20.0/shell": { area: 0.0174, seams: 1, fighting: true },
  "garden|park-train/railway-bridges/bridge-62.0/deck|park-train/railway-bridges/bridge-62.0/shell": { area: 0.0173, seams: 1, fighting: true },
  "garden|park-train/railway-bridges/bridge-224.0/deck|park-train/railway-bridges/bridge-224.0/shell": { area: 0.0173, seams: 1, fighting: true },
  "garden|park-train/railway-bridges/bridge-0.0/deck|park-train/railway-bridges/bridge-0.0/shell": { area: 0.0173, seams: 1, fighting: true },
  "garden|park-train/railway-bridges/bridge-284.0/deck|park-train/railway-bridges/bridge-284.0/shell": { area: 0.0173, seams: 1, fighting: true },
  "garden|park-train/railway-bridges/bridge-2.0/deck|park-train/railway-bridges/bridge-2.0/shell": { area: 0.0173, seams: 1, fighting: true },
  "garden|park-train/railway-bridges/bridge-12.0/deck|park-train/railway-bridges/bridge-12.0/shell": { area: 0.0173, seams: 1, fighting: true },
  "garden|park-train/railway-bridges/bridge-200.0/deck|park-train/railway-bridges/bridge-200.0/shell": { area: 0.0173, seams: 1, fighting: true },
  "garden|park-train/railway-bridges/bridge-142.0/deck|park-train/railway-bridges/bridge-142.0/shell": { area: 0.0173, seams: 1, fighting: true },
  "garden|park-train/railway-bridges/bridge-244.0/deck|park-train/railway-bridges/bridge-244.0/shell": { area: 0.0173, seams: 1, fighting: true },
  "garden|railRace/railRace:cart/hopper|railRace/railRace:cart/seat-back/<Mesh:BufferGeometry>": { area: 0.0165, seams: 4, fighting: false },
  "hotel.lobby|the-land-hotel-inside/hotel:hotel.lobby/hotel.wall|the-land-hotel-inside/hotel:hotel.lobby/hotel:lobby/overhang/hotel.bridgeRailing/bridge-rail-hand": { area: 0.0165, seams: 1, fighting: true },
  "hotel.lobby|the-land-hotel-inside/hotel:hotel.lobby/hotel.straightStaircase/stair-straight-stringer|the-land-hotel-inside/hotel:hotel.lobby/hotel.straightStaircase/stair-straight-tread": { area: 0.0164, seams: 1, fighting: true },
  "hotel.lobby|the-land-hotel-inside/hotel:hotel.lobby/hotel.grandStaircase.right/stair-right-stringer|the-land-hotel-inside/hotel:hotel.lobby/hotel.grandStaircase.right/stair-right-tread": { area: 0.0164, seams: 1, fighting: true },
  "hotel.lobby|the-land-hotel-inside/hotel:hotel.lobby/hotel.wall|the-land-hotel-inside/hotel:hotel.lobby/hotel:lobby/overhang/hotel.landingNosing/landing-nose": { area: 0.0163, seams: 1, fighting: true },
  "garden|facePaintStall/<Group>/<Mesh:CylinderGeometry>|facePaintStall/<Group>/<Mesh:RoundedBoxGeometry>": { area: 0.0162, seams: 2, fighting: false },
  "garden|railRace/railRace:race-ring/railRace:sleepers|railRace/railRace:walk-past-ring/<Mesh:BoxGeometry>": { area: 0.0149, seams: 1, fighting: false },
  "garden|park-train/railway-bridges/bridge-312.0/deck|park-train/railway-bridges/bridge-312.0/shell": { area: 0.0148, seams: 1, fighting: true },
  "garden|park-train/railway-bridges/bridge-18.0/deck|park-train/railway-bridges/bridge-18.0/shell": { area: 0.0148, seams: 1, fighting: true },
  "garden|park-train/railway-bridges/bridge-4.0/deck|park-train/railway-bridges/bridge-4.0/shell": { area: 0.0148, seams: 1, fighting: true },
  "garden|park-train/railway-bridges/bridge-56.0/deck|park-train/railway-bridges/bridge-56.0/shell": { area: 0.0147, seams: 1, fighting: true },
  "garden|park-train/railway-bridges/bridge-30.0/deck|park-train/railway-bridges/bridge-30.0/shell": { area: 0.0147, seams: 1, fighting: true },
  "garden|park-train/railway-bridges/bridge-234.0/deck|park-train/railway-bridges/bridge-234.0/shell": { area: 0.0147, seams: 1, fighting: true },
  "garden|park-train/railway-bridges/bridge-16.0/deck|park-train/railway-bridges/bridge-16.0/shell": { area: 0.0147, seams: 1, fighting: true },
  "garden|park-train/railway-bridges/bridge-104.0/deck|park-train/railway-bridges/bridge-104.0/shell": { area: 0.0147, seams: 1, fighting: true },
  "castle.mall|the-big-building-inside/building-shell/building-shell-floor-0/shop:toy/shop-stage:toy/kiosk:toy/stall-dress:toy/<Group>/<Mesh:BoxGeometry>|the-big-building-inside/building-shell/building-shell-floor-0/shop:toy/shop-stage:toy/kiosk:toy/stall-dress:toy/<Group>/<Mesh:BoxGeometry>": { area: 0.0126, seams: 1, fighting: true },
  "hotel.lobby|the-land-hotel-inside/hotel:hotel.lobby/hotel.grandStaircase.right/stair-right-newel/<Mesh:BufferGeometry>|the-land-hotel-inside/hotel:hotel.lobby/hotel:lobby/overhang/hotel.bridgeRailing/bridge-rail-plinth/<Mesh:BufferGeometry>": { area: 0.0113, seams: 1, fighting: false },
  "hotel.lobby|the-land-hotel-inside/hotel:hotel.lobby/hotel.grandStaircase.left/stair-left-newel/<Mesh:BufferGeometry>|the-land-hotel-inside/hotel:hotel.lobby/hotel:lobby/overhang/hotel.bridgeRailing/bridge-rail-plinth/<Mesh:BufferGeometry>": { area: 0.0113, seams: 1, fighting: false },
  "hotel.lobby|the-land-hotel-inside/hotel:hotel.lobby/hotel:lobby/overhang/hotel.bridgeRailing/bridge-rail-plinth|the-land-hotel-inside/hotel:hotel.lobby/hotel:lobby/overhang/hotel.landingNosing/landing-nose": { area: 0.0106, seams: 2, fighting: true },
  "hotel.lobby|the-land-hotel-inside/hotel:hotel.lobby/hotel.grandStaircase.right/stair-right-newel|the-land-hotel-inside/hotel:hotel.lobby/hotel.grandStaircase.right/stair-right-rail": { area: 0.0104, seams: 1, fighting: true },
  "hotel.lobby|the-land-hotel-inside/hotel:hotel.lobby/hotel.grandStaircase.left/stair-left-newel|the-land-hotel-inside/hotel:hotel.lobby/hotel.grandStaircase.left/stair-left-rail": { area: 0.0104, seams: 1, fighting: true },
  "hotel.lobby|the-land-hotel-inside/hotel:hotel.lobby/hotel.straightStaircase/stair-straight-newel|the-land-hotel-inside/hotel:hotel.lobby/hotel:lobby/overhang/hotel.bridgeNewel/bridge-newel": { area: 0.0096, seams: 1, fighting: true },
  "garden|anchor-plots/anchor:hotel/the-land-hotel-outside/hotel.tower/tower-door-jamb/<Mesh:BufferGeometry>|garden/terrain": { area: 0.0096, seams: 1, fighting: false },
  "castle.hall|the-big-building-inside/building-shell/building-shell-floor-1/castle-decor-1/castle-furniture-1/castle.armour/armour-trim/<Mesh:BufferGeometry>|the-big-building-inside/building-shell/building-shell-floor-1/castle-decor-1/castle-furniture-1/castle.armour/armour-visor": { area: 0.0090, seams: 1, fighting: false },
  "hotel.garden|the-land-hotel-inside/hotel:hotel.garden/hotel.tuft/<Mesh:SphereGeometry>|the-land-hotel-inside/hotel:hotel.garden/hotel.tuft/<Mesh:SphereGeometry>": { area: 0.0087, seams: 21, fighting: false },
  "hotel.lobby|the-land-hotel-inside/hotel:hotel.lobby/hotel.straightStaircase/stair-straight-newel/<Mesh:BufferGeometry>|the-land-hotel-inside/hotel:hotel.lobby/hotel:lobby/overhang/hotel.bridgeNewel/bridge-newel/<Mesh:BufferGeometry>": { area: 0.0085, seams: 1, fighting: true },
  "castle.hall|the-big-building-inside/building-shell/building-shell-floor-1/castle-decor-1/castle-furniture-1/castle.armour/armour-plate|the-big-building-inside/building-shell/building-shell-floor-1/castle-decor-1/castle-furniture-1/castle.armour/armour-trim": { area: 0.0073, seams: 1, fighting: false },
  "castle.mall|the-big-building-inside/building-shell/building-shell-floor-0/shop:toy/shop-stage:toy/kiosk:toy/<Mesh:BoxGeometry>|the-big-building-inside/building-shell/building-shell-floor-0/shop:toy/shop-stage:toy/shop-detail:toy/gear.jetpack/gear.jetpack:fit/<Mesh:ConeGeometry>": { area: 0.0066, seams: 1, fighting: false },
  "hotel.lobby|the-land-hotel-inside/hotel:hotel.lobby/hotel.straightStaircase/stair-straight-newel/<Mesh:BufferGeometry>|the-land-hotel-inside/hotel:hotel.lobby/hotel.straightStaircase/stair-straight-tread/<Mesh:BufferGeometry>": { area: 0.0066, seams: 1, fighting: false },
  "hotel.lobby|the-land-hotel-inside/hotel:hotel.lobby/hotel:lobby/overhang/hotel.bridgeRailing/bridge-rail-plinth/<Mesh:BufferGeometry>|the-land-hotel-inside/hotel:hotel.lobby/hotel:lobby/overhang/hotel.landingNosing/landing-nose/<Mesh:BufferGeometry>": { area: 0.0062, seams: 2, fighting: false },
  "hotel.garden|the-land-hotel-inside/hotel:hotel.garden/hotel.arch/hotel.tuft/<Mesh:SphereGeometry>|the-land-hotel-inside/hotel:hotel.garden/hotel.arch/hotel.tuft/<Mesh:SphereGeometry>": { area: 0.0060, seams: 20, fighting: false },
  "castle.mall|the-big-building-inside/building-shell/building-shell-floor-0/shop:stickerPet/shop-stage:stickerPet/kiosk:stickerPet/<Mesh:BoxGeometry>|the-big-building-inside/building-shell/building-shell-floor-0/shop:stickerPet/shop-stage:stickerPet/shop-detail:stickerPet/sticker.sheet/<Mesh:BoxGeometry>/<Mesh:BoxGeometry>": { area: 0.0055, seams: 1, fighting: false },
  "castle.mall|the-big-building-inside/building-shell/building-shell-floor-0/shop:stickerPet/shop-stage:stickerPet/kiosk:stickerPet/<Mesh:BoxGeometry>|the-big-building-inside/building-shell/building-shell-floor-0/shop:stickerPet/shop-stage:stickerPet/kiosk:stickerPet/stall-dress:stickerPet/<Group>/<Mesh:BoxGeometry>": { area: 0.0039, seams: 1, fighting: true },
  "hotel.suite|the-land-hotel-inside/hotel:hotel.suite/hotel.gameBoy/gameboy-body|the-land-hotel-inside/hotel:hotel.suite/hotel.gameBoy/gameboy-buttons": { area: 0.0038, seams: 1, fighting: false },
  "hotel.lobby|the-land-hotel-inside/hotel:hotel.lobby/hotel.grandStaircase.left/stair-left-newel|the-land-hotel-inside/hotel:hotel.lobby/hotel:lobby/overhang/hotel.bridgeRailing/bridge-rail-hand": { area: 0.0037, seams: 1, fighting: true },
  "hotel.lobby|the-land-hotel-inside/hotel:hotel.lobby/hotel.grandStaircase.right/stair-right-newel|the-land-hotel-inside/hotel:hotel.lobby/hotel:lobby/overhang/hotel.bridgeRailing/bridge-rail-hand": { area: 0.0036, seams: 1, fighting: true },
  "hotel.lobby|the-land-hotel-inside/hotel:hotel.lobby/hotel.grandStaircase.left/stair-left-rail/<Mesh:BufferGeometry>|the-land-hotel-inside/hotel:hotel.lobby/hotel.grandStaircase.left/stair-left-stringer/<Mesh:BufferGeometry>": { area: 0.0035, seams: 2, fighting: false },
  "hotel.lobby|the-land-hotel-inside/hotel:hotel.lobby/hotel.grandStaircase.right/stair-right-rail|the-land-hotel-inside/hotel:hotel.lobby/hotel.grandStaircase.right/stair-right-stringer": { area: 0.0035, seams: 1, fighting: true },
  "hotel.lobby|the-land-hotel-inside/hotel:hotel.lobby/hotel.grandStaircase.right/stair-right-rail/<Mesh:BufferGeometry>|the-land-hotel-inside/hotel:hotel.lobby/hotel.grandStaircase.right/stair-right-stringer/<Mesh:BufferGeometry>": { area: 0.0035, seams: 1, fighting: false },
  "hotel.lobby|the-land-hotel-inside/hotel:hotel.lobby/hotel.grandStaircase.right/stair-right-newel/<Mesh:BufferGeometry>|the-land-hotel-inside/hotel:hotel.lobby/hotel.grandStaircase.right/stair-right-tread/<Mesh:BufferGeometry>": { area: 0.0032, seams: 1, fighting: false },
  "hotel.lobby|the-land-hotel-inside/hotel:hotel.lobby/hotel.grandStaircase.left/stair-left-newel/<Mesh:BufferGeometry>|the-land-hotel-inside/hotel:hotel.lobby/hotel.grandStaircase.left/stair-left-tread/<Mesh:BufferGeometry>": { area: 0.0032, seams: 1, fighting: false },
  "garden|park-train/train-station-0/<Mesh:BoxGeometry>|park-train/train-station-0/<Mesh:BoxGeometry>": { area: 0.0024, seams: 1, fighting: true },
  "garden|park-train/train-station-1/<Mesh:BoxGeometry>|park-train/train-station-1/<Mesh:BoxGeometry>": { area: 0.0024, seams: 1, fighting: true },
  "garden|railRace/railRace:walk-past-ring/railRace:duck-bars|railRace/railRace:walk-past-ring/railRace:trestle-branches-upper": { area: 0.0024, seams: 1, fighting: false },
  "castle.hall|the-big-building-inside/building-shell/building-shell-floor-1/lift-alcove/hotel.liftFrame/lift-frame-sill/<Mesh:BufferGeometry>|the-big-building-inside/building-shell/building-shell-floor-1/lift-alcove/hotel.liftFrame/lift-frame/<Mesh:BufferGeometry>": { area: 0.0022, seams: 1, fighting: false },
  "castle.mall|the-big-building-inside/building-shell/building-shell-floor-0/lift-alcove/hotel.liftFrame/lift-frame-sill/<Mesh:BufferGeometry>|the-big-building-inside/building-shell/building-shell-floor-0/lift-alcove/hotel.liftFrame/lift-frame/<Mesh:BufferGeometry>": { area: 0.0022, seams: 1, fighting: false },
  "castle.roof|the-big-building-inside/building-shell/building-shell-floor-2/lift-alcove/hotel.liftFrame/lift-frame-sill/<Mesh:BufferGeometry>|the-big-building-inside/building-shell/building-shell-floor-2/lift-alcove/hotel.liftFrame/lift-frame/<Mesh:BufferGeometry>": { area: 0.0022, seams: 1, fighting: false },
  "hotel.breakfast|the-land-hotel-inside/hotel:hotel.breakfast/lift-alcove/hotel.liftFrame/lift-frame-sill/<Mesh:BufferGeometry>|the-land-hotel-inside/hotel:hotel.breakfast/lift-alcove/hotel.liftFrame/lift-frame/<Mesh:BufferGeometry>": { area: 0.0022, seams: 1, fighting: false },
  "hotel.corridor|the-land-hotel-inside/hotel:hotel.corridor/lift-alcove/hotel.liftFrame/lift-frame-sill/<Mesh:BufferGeometry>|the-land-hotel-inside/hotel:hotel.corridor/lift-alcove/hotel.liftFrame/lift-frame/<Mesh:BufferGeometry>": { area: 0.0022, seams: 1, fighting: false },
  "hotel.garden|the-land-hotel-inside/hotel:hotel.garden/lift-alcove/hotel.liftFrame/lift-frame-sill/<Mesh:BufferGeometry>|the-land-hotel-inside/hotel:hotel.garden/lift-alcove/hotel.liftFrame/lift-frame/<Mesh:BufferGeometry>": { area: 0.0022, seams: 1, fighting: false },
  "hotel.lobby|the-land-hotel-inside/hotel:hotel.lobby/lift-alcove/hotel.liftFrame/lift-frame-sill/<Mesh:BufferGeometry>|the-land-hotel-inside/hotel:hotel.lobby/lift-alcove/hotel.liftFrame/lift-frame/<Mesh:BufferGeometry>": { area: 0.0022, seams: 1, fighting: false },
  "hotel.ocean|the-land-hotel-inside/hotel:hotel.ocean/lift-alcove/hotel.liftFrame/lift-frame-sill/<Mesh:BufferGeometry>|the-land-hotel-inside/hotel:hotel.ocean/lift-alcove/hotel.liftFrame/lift-frame/<Mesh:BufferGeometry>": { area: 0.0022, seams: 1, fighting: false },
  "garden|park-train/train-carriage-0/<Mesh:BoxGeometry>|park-train/train-carriage-0/<Mesh:CylinderGeometry>": { area: 0.0015, seams: 1, fighting: false },
  "garden|park-train/train-carriage-2/<Mesh:BoxGeometry>|park-train/train-carriage-2/<Mesh:CylinderGeometry>": { area: 0.0015, seams: 1, fighting: false },
  "garden|park-train/train-carriage-1/<Mesh:BoxGeometry>|park-train/train-carriage-1/<Mesh:CylinderGeometry>": { area: 0.0015, seams: 1, fighting: false },
  "castle.mall|the-big-building-inside/building-shell/building-shell-floor-0/shop:hat/shop-stage:hat/shop-detail:hat/<Mesh:CylinderGeometry>|the-big-building-inside/building-shell/building-shell-floor-0/shop:hat/shop-stage:hat/shop-detail:hat/hat.party/hat.party:fit/<Mesh:ConeGeometry>/<Mesh:ConeGeometry>": { area: 0.0014, seams: 1, fighting: false },
  "garden|railRace/railRace:race-ring/railRace:trestle-branches-lower|railRace/railRace:race-ring/railRace:trestle-branches-upper": { area: 0.0010, seams: 14, fighting: false },
  "garden|garden/terrain|stalls/stall:spookyHouse/<Mesh:CylinderGeometry>/<Mesh:CylinderGeometry>": { area: 0.0009, seams: 1, fighting: false },
  "castle.hall|the-big-building-inside/building-shell/building-shell-floor-1/lift-alcove/hotel.liftDial/lift-dial|the-big-building-inside/building-shell/building-shell-floor-1/lift-alcove/hotel.liftDial/lift-dial-needle/<Mesh:BufferGeometry>": { area: 0.0008, seams: 1, fighting: false },
  "castle.mall|the-big-building-inside/building-shell/building-shell-floor-0/lift-alcove/hotel.liftDial/lift-dial|the-big-building-inside/building-shell/building-shell-floor-0/lift-alcove/hotel.liftDial/lift-dial-needle/<Mesh:BufferGeometry>": { area: 0.0008, seams: 1, fighting: false },
  "castle.roof|the-big-building-inside/building-shell/building-shell-floor-2/lift-alcove/hotel.liftDial/lift-dial|the-big-building-inside/building-shell/building-shell-floor-2/lift-alcove/hotel.liftDial/lift-dial-needle/<Mesh:BufferGeometry>": { area: 0.0008, seams: 1, fighting: false },
  "hotel.breakfast|the-land-hotel-inside/hotel:hotel.breakfast/lift-alcove/hotel.liftDial/lift-dial|the-land-hotel-inside/hotel:hotel.breakfast/lift-alcove/hotel.liftDial/lift-dial-needle/<Mesh:BufferGeometry>": { area: 0.0008, seams: 1, fighting: false },
  "hotel.corridor|the-land-hotel-inside/hotel:hotel.corridor/lift-alcove/hotel.liftDial/lift-dial|the-land-hotel-inside/hotel:hotel.corridor/lift-alcove/hotel.liftDial/lift-dial-needle/<Mesh:BufferGeometry>": { area: 0.0008, seams: 1, fighting: false },
  "hotel.garden|the-land-hotel-inside/hotel:hotel.garden/lift-alcove/hotel.liftDial/lift-dial|the-land-hotel-inside/hotel:hotel.garden/lift-alcove/hotel.liftDial/lift-dial-needle/<Mesh:BufferGeometry>": { area: 0.0008, seams: 1, fighting: false },
  "hotel.lobby|the-land-hotel-inside/hotel:hotel.lobby/lift-alcove/hotel.liftDial/lift-dial|the-land-hotel-inside/hotel:hotel.lobby/lift-alcove/hotel.liftDial/lift-dial-needle/<Mesh:BufferGeometry>": { area: 0.0008, seams: 1, fighting: false },
  "hotel.ocean|the-land-hotel-inside/hotel:hotel.ocean/lift-alcove/hotel.liftDial/lift-dial|the-land-hotel-inside/hotel:hotel.ocean/lift-alcove/hotel.liftDial/lift-dial-needle/<Mesh:BufferGeometry>": { area: 0.0008, seams: 1, fighting: false },
  "garden|flowers/living-flower-stems|park-train/train-track/track-sleepers": { area: 0.0008, seams: 1, fighting: false },
  "hotel.suite|the-land-hotel-inside/hotel:hotel.suite/toilet-basin/<Mesh:CylinderGeometry>|the-land-hotel-inside/hotel:hotel.suite/toilet-basin/<Mesh:CylinderGeometry>": { area: 0.0004, seams: 1, fighting: false },
  "hotel.garden|the-land-hotel-inside/hotel:hotel.garden/toilet-basin/<Mesh:CylinderGeometry>|the-land-hotel-inside/hotel:hotel.garden/toilet-basin/<Mesh:CylinderGeometry>": { area: 0.0004, seams: 1, fighting: false },
  "hotel.lobby|the-land-hotel-inside/hotel:hotel.lobby/toilet-basin/<Mesh:CylinderGeometry>|the-land-hotel-inside/hotel:hotel.lobby/toilet-basin/<Mesh:CylinderGeometry>": { area: 0.0004, seams: 1, fighting: false },
  "castle.mall|the-big-building-inside/building-shell/building-shell-floor-0/shop:hat/shop-stage:hat/shop-detail:hat/hat.ripikaHat/hat.ripikaHat:fit/hoodEarL/<Mesh:BufferGeometry>|the-big-building-inside/building-shell/building-shell-floor-0/shop:hat/shop-stage:hat/shop-detail:hat/hat.ripikaHat/hat.ripikaHat:fit/hoodEarL/<Mesh:BufferGeometry>/<Mesh:BufferGeometry>": { area: 0.0004, seams: 1, fighting: false },
  "castle.mall|the-big-building-inside/building-shell/building-shell-floor-0/shop:hat/shop-stage:hat/shop-detail:hat/hat.ripikaHat/hat.ripikaHat:fit/hoodEarR/<Mesh:BufferGeometry>|the-big-building-inside/building-shell/building-shell-floor-0/shop:hat/shop-stage:hat/shop-detail:hat/hat.ripikaHat/hat.ripikaHat:fit/hoodEarR/<Mesh:BufferGeometry>/<Mesh:BufferGeometry>": { area: 0.0004, seams: 1, fighting: false },
  "garden|railRace/railRace:cart/seat-back|railRace/railRace:cart/seat-base": { area: 0.0004, seams: 4, fighting: false },
  "castle.mall|the-big-building-inside/building-shell/building-shell-floor-0/toilets/toilet-basin/<Mesh:CylinderGeometry>|the-big-building-inside/building-shell/building-shell-floor-0/toilets/toilet-basin/<Mesh:CylinderGeometry>": { area: 0.0003, seams: 1, fighting: false },
  "hotel.breakfast|the-land-hotel-inside/hotel:hotel.breakfast/toilet-basin/<Mesh:CylinderGeometry>|the-land-hotel-inside/hotel:hotel.breakfast/toilet-basin/<Mesh:CylinderGeometry>": { area: 0.0003, seams: 1, fighting: false },
  "hotel.ocean|the-land-hotel-inside/hotel:hotel.ocean/toilet-basin/<Mesh:CylinderGeometry>|the-land-hotel-inside/hotel:hotel.ocean/toilet-basin/<Mesh:CylinderGeometry>": { area: 0.0003, seams: 1, fighting: false },
  "garden|keychainShop/<Group>/keychain.rumi/<Group>/<Mesh:SphereGeometry>/<Mesh:SphereGeometry>|keychainShop/<Group>/keychain.rumi/<Group>/<Mesh:SphereGeometry>/<Mesh:SphereGeometry>": { area: 0.0003, seams: 7, fighting: false },
  "castle.mall|the-big-building-inside/building-shell/building-shell-floor-0/shop:toy/shop-stage:toy/shop-detail:toy/biscuit/<Group>/<Mesh:ExtrudeGeometry>|the-big-building-inside/building-shell/building-shell-floor-0/shop:toy/shop-stage:toy/shop-detail:toy/biscuit/<Group>/<Mesh:ExtrudeGeometry>/<Mesh:ExtrudeGeometry>": { area: 0.0003, seams: 2, fighting: false },
  "castle.mall|the-big-building-inside/building-shell/building-shell-floor-0/shop:hat/shop-stage:hat/shop-detail:hat/hat.ripikaHat/hat.ripikaHat:fit/<Mesh:BufferGeometry>|the-big-building-inside/building-shell/building-shell-floor-0/shop:hat/shop-stage:hat/shop-detail:hat/hat.ripikaHat/hat.ripikaHat:fit/<Mesh:BufferGeometry>": { area: 0.0003, seams: 89, fighting: false },
  "garden|railRace/railRace:walk-past-ring/railRace:trestle-branches-lower|railRace/railRace:walk-past-ring/railRace:trestle-branches-upper": { area: 0.0003, seams: 3, fighting: false },
  "castle.mall|the-big-building-inside/building-shell/building-shell-floor-0/shop:hat/shop-stage:hat/shop-detail:hat/hat.cap/hat.cap:fit/<Mesh:BufferGeometry>|the-big-building-inside/building-shell/building-shell-floor-0/shop:hat/shop-stage:hat/shop-detail:hat/hat.cap/hat.cap:fit/<Mesh:BufferGeometry>": { area: 0.0002, seams: 32, fighting: false },
  "castle.hall|the-big-building-inside/building-shell/building-shell-floor-1/lift-alcove/hotel.liftCar/lift-car|the-big-building-inside/building-shell/building-shell-floor-1/lift-alcove/hotel.liftCar/lift-car-rail": { area: 0.0001, seams: 1, fighting: false },
  "castle.mall|the-big-building-inside/building-shell/building-shell-floor-0/lift-alcove/hotel.liftCar/lift-car|the-big-building-inside/building-shell/building-shell-floor-0/lift-alcove/hotel.liftCar/lift-car-rail": { area: 0.0001, seams: 1, fighting: false },
  "castle.roof|the-big-building-inside/building-shell/building-shell-floor-2/lift-alcove/hotel.liftCar/lift-car|the-big-building-inside/building-shell/building-shell-floor-2/lift-alcove/hotel.liftCar/lift-car-rail": { area: 0.0001, seams: 1, fighting: false },
  "hotel.breakfast|the-land-hotel-inside/hotel:hotel.breakfast/lift-alcove/hotel.liftCar/lift-car|the-land-hotel-inside/hotel:hotel.breakfast/lift-alcove/hotel.liftCar/lift-car-rail": { area: 0.0001, seams: 1, fighting: false },
  "hotel.corridor|the-land-hotel-inside/hotel:hotel.corridor/lift-alcove/hotel.liftCar/lift-car|the-land-hotel-inside/hotel:hotel.corridor/lift-alcove/hotel.liftCar/lift-car-rail": { area: 0.0001, seams: 1, fighting: false },
  "hotel.garden|the-land-hotel-inside/hotel:hotel.garden/lift-alcove/hotel.liftCar/lift-car|the-land-hotel-inside/hotel:hotel.garden/lift-alcove/hotel.liftCar/lift-car-rail": { area: 0.0001, seams: 1, fighting: false },
  "hotel.lobby|the-land-hotel-inside/hotel:hotel.lobby/lift-alcove/hotel.liftCar/lift-car|the-land-hotel-inside/hotel:hotel.lobby/lift-alcove/hotel.liftCar/lift-car-rail": { area: 0.0001, seams: 1, fighting: false },
  "hotel.ocean|the-land-hotel-inside/hotel:hotel.ocean/lift-alcove/hotel.liftCar/lift-car|the-land-hotel-inside/hotel:hotel.ocean/lift-alcove/hotel.liftCar/lift-car-rail": { area: 0.0001, seams: 1, fighting: false },
  "garden|keychainShop/<Group>/keychain.rumi/<Group>/<Mesh:SphereGeometry>|keychainShop/<Group>/keychain.rumi/<Group>/<Mesh:SphereGeometry>": { area: 0.0001, seams: 2, fighting: false },
  "castle.mall|the-big-building-inside/building-shell/building-shell-floor-0/shop:hat/shop-stage:hat/shop-detail:hat/hat.cap/hat.cap:fit/<Mesh:BufferGeometry>|the-big-building-inside/building-shell/building-shell-floor-0/shop:hat/shop-stage:hat/shop-detail:hat/hat.cap/hat.cap:fit/hoodShell/<Mesh:BufferGeometry>": { area: 0.0001, seams: 10, fighting: false },
};
