/**
 * **Which of seeds 0–15 did not build when `check:every-seed-builds` was last
 * re-taken, and why.** Generated by
 * `pnpm run check:every-seed-builds -- --print-baseline`; never edited by hand.
 *
 * Keyed on the **seed number**, which nothing can rename (#520 is what happens
 * to a baseline keyed on names). An entry for a seed the check does not sweep
 * **fails the check**. A seed with no entry must build. A seed that starts
 * building while still listed here fails the check until this file is
 * re-taken — a rung records its own win in a diff, never banks it quietly.
 *
 * Do not add an entry to make the check pass. An entry means "this seed did not
 * build when the gate was last re-taken, for this reason"; a new one means a
 * seed has just been broken. The endpoint is an empty record: every seed
 * builds (Jim, 6 Sep 2026: "fix it properly"). See
 * `docs/DESIGN-round-robin-generation.md`, "Totality, ruled and mechanised".
 */
export const UNBUILT_BASELINE: Readonly<Record<number, string>> = {
  1: 'poi.stranded',
  2: 'crossing.nosite',
  3: 'crossing.nosite',
  4: 'poi.stranded',
  6: 'anchor.reach:waterFight+poi.nospot+poi.stranded',
  7: 'crossing.nosite',
  8: 'rail.unsolvable',
  9: 'rail.unsolvable',
  10: 'rail.unsolvable',
  12: 'anchor.reach:waterFight',
  13: 'poi.stranded',
  15: 'poi.stranded',
};

/**
 * Times decision zero (a whole-park layout restart) was reached, per seed that
 * built — the "built well" measurement. More than recorded fails; fewer fails
 * too, until re-taken.
 */
export const DECISION_ZERO_BASELINE: Readonly<Record<number, number>> = {
  0: 0,
  5: 0,
  11: 0,
  14: 0,
};
