/**
 * **Every flat primitive that already existed when this gate was written.**
 *
 * Generated — `pnpm run check:flat-primitives -- --print-baseline`. Do not
 * hand-edit to make a check pass: an entry here means "this was already flat",
 * and a finding that is not here means somebody has just written a new one.
 *
 * The key is `file::RULE::expression`, not a line number, so an entry survives
 * the code above it moving and dies only when the expression itself goes.
 *
 * **These are not adjudicated.** `RADIAL-INVENTORY.md` sorts ~95 of them into
 * true positives and ~40 into checked-and-correct, and that took a day and a
 * measured control per case. This table makes no such claim: it records what
 * was there, so that what comes next has to be better. The way an entry leaves
 * is by being fixed, at which point the check prints BASELINE LOOSE and asks
 * for the line to be deleted.
 */

export interface BaselineEntry {
  /** How many of this expression were in this file when the gate was written. */
  readonly count: number;
  /** Which of the two mistakes it is an instance of. */
  readonly rule: string;
}

export const FLAT_PRIMITIVE_BASELINE: Readonly<Record<string, BaselineEntry>> = {
  "scripts/check-arrival-camera.mts::Y_DIFFERENCE::focus.y - eye.y": { count: 1, rule: 'Y_DIFFERENCE' },
  "scripts/check-backpack-peek.mts::Y_DIFFERENCE::top - bottom": { count: 1, rule: 'Y_DIFFERENCE' },
  "scripts/check-benches.mts::AXIS_ALIGNED_BOX::box.max.y": { count: 1, rule: 'AXIS_ALIGNED_BOX' },
  "scripts/check-bus-journey.mts::AXIS_ALIGNED_BOX::bodywork.max.y": { count: 1, rule: 'AXIS_ALIGNED_BOX' },
  "scripts/check-bus-journey.mts::AXIS_ALIGNED_BOX::bodywork.min.y": { count: 2, rule: 'AXIS_ALIGNED_BOX' },
  "scripts/check-bus-journey.mts::AXIS_ALIGNED_BOX::box.max.y": { count: 4, rule: 'AXIS_ALIGNED_BOX' },
  "scripts/check-bus-journey.mts::AXIS_ALIGNED_BOX::box.min.y": { count: 4, rule: 'AXIS_ALIGNED_BOX' },
  "scripts/check-bus-journey.mts::AXIS_ALIGNED_BOX::boxIn(lowerShell, toBus).min.y": { count: 1, rule: 'AXIS_ALIGNED_BOX' },
  "scripts/check-bus-journey.mts::AXIS_ALIGNED_BOX::boxIn(torso, toBus).max.y": { count: 1, rule: 'AXIS_ALIGNED_BOX' },
  "scripts/check-bus-journey.mts::AXIS_ALIGNED_BOX::boxIn(upperShell, toBus).max.y": { count: 1, rule: 'AXIS_ALIGNED_BOX' },
  "scripts/check-bus-journey.mts::AXIS_ALIGNED_BOX::glass.min.y": { count: 7, rule: 'AXIS_ALIGNED_BOX' },
  "scripts/check-bus-journey.mts::Y_DIFFERENCE::bodywork.min.y - box.max.y": { count: 1, rule: 'Y_DIFFERENCE' },
  "scripts/check-bus-journey.mts::Y_DIFFERENCE::box.min.y - bodywork.max.y": { count: 1, rule: 'Y_DIFFERENCE' },
  "scripts/check-bus-journey.mts::Y_DIFFERENCE::glass.min.y - lowestShoulder": { count: 1, rule: 'Y_DIFFERENCE' },
  "scripts/check-bus-journey.mts::Y_DIFFERENCE::glass.min.y - skullBottom": { count: 1, rule: 'Y_DIFFERENCE' },
  "scripts/check-bus-journey.mts::Y_DIFFERENCE::lowestShoulder - glass.min.y": { count: 1, rule: 'Y_DIFFERENCE' },
  "scripts/check-bus-journey.mts::Y_DIFFERENCE::skullTop - skullBottom": { count: 1, rule: 'Y_DIFFERENCE' },
  "scripts/check-bus-journey.mts::Y_DIFFERENCE::top.y - bottom.y": { count: 1, rule: 'Y_DIFFERENCE' },
  "scripts/check-bus-journey.mts::Y_THRESHOLD::steepestClimbNose < 0.02": { count: 1, rule: 'Y_THRESHOLD' },
  "scripts/check-cart-shape.mts::AXIS_ALIGNED_BOX::hopper.geometry.boundingBox!.min.y": { count: 1, rule: 'AXIS_ALIGNED_BOX' },
  "scripts/check-cart-shape.mts::AXIS_ALIGNED_BOX::hopperBox.min.y": { count: 2, rule: 'AXIS_ALIGNED_BOX' },
  "scripts/check-cart-shape.mts::AXIS_ALIGNED_BOX::seatBase.geometry.boundingBox!.max.y": { count: 1, rule: 'AXIS_ALIGNED_BOX' },
  "scripts/check-cart-shape.mts::AXIS_ALIGNED_BOX::wheelBox.max.y": { count: 2, rule: 'AXIS_ALIGNED_BOX' },
  "scripts/check-cart-shape.mts::AXIS_ALIGNED_BOX::wheelBox.min.y": { count: 2, rule: 'AXIS_ALIGNED_BOX' },
  "scripts/check-cart-shape.mts::Y_DIFFERENCE::pA.y - pB.y": { count: 1, rule: 'Y_DIFFERENCE' },
  "scripts/check-castle.mts::AXIS_ALIGNED_BOX::armour.min.y": { count: 1, rule: 'AXIS_ALIGNED_BOX' },
  "scripts/check-castle.mts::AXIS_ALIGNED_BOX::box.max.y": { count: 3, rule: 'AXIS_ALIGNED_BOX' },
  "scripts/check-castle.mts::AXIS_ALIGNED_BOX::box.min.y": { count: 6, rule: 'AXIS_ALIGNED_BOX' },
  "scripts/check-castle.mts::AXIS_ALIGNED_BOX::box.setFromObject(object).max.y": { count: 1, rule: 'AXIS_ALIGNED_BOX' },
  "scripts/check-castle.mts::AXIS_ALIGNED_BOX::flameWorld.max.y": { count: 1, rule: 'AXIS_ALIGNED_BOX' },
  "scripts/check-castle.mts::AXIS_ALIGNED_BOX::new Box3().setFromObject(parapetMesh).max.y": { count: 1, rule: 'AXIS_ALIGNED_BOX' },
  "scripts/check-castle.mts::AXIS_ALIGNED_BOX::openingBox.max.y": { count: 2, rule: 'AXIS_ALIGNED_BOX' },
  "scripts/check-castle.mts::AXIS_ALIGNED_BOX::pileWorld.max.y": { count: 1, rule: 'AXIS_ALIGNED_BOX' },
  "scripts/check-castle.mts::AXIS_ALIGNED_BOX::pileWorld.min.y": { count: 1, rule: 'AXIS_ALIGNED_BOX' },
  "scripts/check-castle.mts::AXIS_ALIGNED_BOX::plinth.max.y": { count: 3, rule: 'AXIS_ALIGNED_BOX' },
  "scripts/check-castle.mts::AXIS_ALIGNED_BOX::prop.min.y": { count: 2, rule: 'AXIS_ALIGNED_BOX' },
  "scripts/check-castle.mts::AXIS_ALIGNED_BOX::shellBounds.min.y": { count: 2, rule: 'AXIS_ALIGNED_BOX' },
  "scripts/check-castle.mts::AXIS_ALIGNED_BOX::sootBox.max.y": { count: 1, rule: 'AXIS_ALIGNED_BOX' },
  "scripts/check-castle.mts::AXIS_ALIGNED_BOX::surface.max.y": { count: 3, rule: 'AXIS_ALIGNED_BOX' },
  "scripts/check-castle.mts::AXIS_ALIGNED_BOX::tableTop.max.y": { count: 2, rule: 'AXIS_ALIGNED_BOX' },
  "scripts/check-castle.mts::AXIS_ALIGNED_BOX::world.max.y": { count: 1, rule: 'AXIS_ALIGNED_BOX' },
  "scripts/check-castle.mts::AXIS_ALIGNED_BOX::world.min.y": { count: 1, rule: 'AXIS_ALIGNED_BOX' },
  "scripts/check-castle.mts::AXIS_ALIGNED_BOX::worldBounds.max.y": { count: 2, rule: 'AXIS_ALIGNED_BOX' },
  "scripts/check-castle.mts::AXIS_ALIGNED_BOX::worldBounds.min.y": { count: 5, rule: 'AXIS_ALIGNED_BOX' },
  "scripts/check-castle.mts::HARD_UP::new Vector3(0, -1, 0)": { count: 1, rule: 'HARD_UP' },
  "scripts/check-castle.mts::Y_DIFFERENCE::armour.min.y - plinth.max.y": { count: 1, rule: 'Y_DIFFERENCE' },
  "scripts/check-castle.mts::Y_DIFFERENCE::box.max.y - box.min.y": { count: 1, rule: 'Y_DIFFERENCE' },
  "scripts/check-castle.mts::Y_DIFFERENCE::prop.min.y - tableTop.max.y": { count: 1, rule: 'Y_DIFFERENCE' },
  "scripts/check-cat-bus-suspension.mts::AXIS_ALIGNED_BOX::box.max.y": { count: 2, rule: 'AXIS_ALIGNED_BOX' },
  "scripts/check-cat-bus-suspension.mts::AXIS_ALIGNED_BOX::box.min.y": { count: 4, rule: 'AXIS_ALIGNED_BOX' },
  "scripts/check-cat-bus-suspension.mts::HARD_UP::new Vector3(0, 1, 0)": { count: 1, rule: 'HARD_UP' },
  "scripts/check-cat-bus-suspension.mts::Y_DIFFERENCE::box.max.y - point.y": { count: 1, rule: 'Y_DIFFERENCE' },
  "scripts/check-cat-bus-suspension.mts::Y_DIFFERENCE::box.min.y - point.y": { count: 1, rule: 'Y_DIFFERENCE' },
  "scripts/check-cat-bus-suspension.mts::Y_DIFFERENCE::point.y - box.max.y": { count: 1, rule: 'Y_DIFFERENCE' },
  "scripts/check-cat-bus-suspension.mts::Y_DIFFERENCE::point.y - box.min.y": { count: 1, rule: 'Y_DIFFERENCE' },
  "scripts/check-cat-bus.mts::AXIS_ALIGNED_BOX::box.max.y": { count: 1, rule: 'AXIS_ALIGNED_BOX' },
  "scripts/check-cat-bus.mts::AXIS_ALIGNED_BOX::faceBox.max.y": { count: 2, rule: 'AXIS_ALIGNED_BOX' },
  "scripts/check-cat-bus.mts::AXIS_ALIGNED_BOX::faceBox.min.y": { count: 1, rule: 'AXIS_ALIGNED_BOX' },
  "scripts/check-cat-bus.mts::AXIS_ALIGNED_BOX::shell.max.y": { count: 2, rule: 'AXIS_ALIGNED_BOX' },
  "scripts/check-cat-bus.mts::AXIS_ALIGNED_BOX::shell.min.y": { count: 1, rule: 'AXIS_ALIGNED_BOX' },
  "scripts/check-cat-bus.mts::Y_DIFFERENCE::box.max.y - shell.max.y": { count: 1, rule: 'Y_DIFFERENCE' },
  "scripts/check-cat-bus.mts::Y_DIFFERENCE::faceBox.max.y - faceBox.min.y": { count: 1, rule: 'Y_DIFFERENCE' },
  "scripts/check-cat-bus.mts::Y_DIFFERENCE::shell.max.y - shell.min.y": { count: 1, rule: 'Y_DIFFERENCE' },
  "scripts/check-climb-wave.mts::HARD_UP::new Vector3(0, 1, 0)": { count: 2, rule: 'HARD_UP' },
  "scripts/check-climb-wave.mts::Y_DIFFERENCE::high - low": { count: 1, rule: 'Y_DIFFERENCE' },
  "scripts/check-hair.mts::AXIS_ALIGNED_BOX::handBox.max.y": { count: 1, rule: 'AXIS_ALIGNED_BOX' },
  "scripts/check-hotel.mts::AXIS_ALIGNED_BOX::box.max.y": { count: 6, rule: 'AXIS_ALIGNED_BOX' },
  "scripts/check-hotel.mts::AXIS_ALIGNED_BOX::box.min.y": { count: 2, rule: 'AXIS_ALIGNED_BOX' },
  "scripts/check-hotel.mts::AXIS_ALIGNED_BOX::group.max.y": { count: 1, rule: 'AXIS_ALIGNED_BOX' },
  "scripts/check-hotel.mts::AXIS_ALIGNED_BOX::one.box.max.y": { count: 4, rule: 'AXIS_ALIGNED_BOX' },
  "scripts/check-hotel.mts::AXIS_ALIGNED_BOX::pet.max.y": { count: 2, rule: 'AXIS_ALIGNED_BOX' },
  "scripts/check-hotel.mts::AXIS_ALIGNED_BOX::pet.min.y": { count: 4, rule: 'AXIS_ALIGNED_BOX' },
  "scripts/check-hotel.mts::AXIS_ALIGNED_BOX::two.box.max.y": { count: 3, rule: 'AXIS_ALIGNED_BOX' },
  "scripts/check-hotel.mts::HARD_UP::new Vector3(0, -1, 0)": { count: 1, rule: 'HARD_UP' },
  "scripts/check-hotel.mts::Y_DIFFERENCE::box.max.y - box.min.y": { count: 2, rule: 'Y_DIFFERENCE' },
  "scripts/check-hotel.mts::Y_DIFFERENCE::one.box.max.y - two.box.max.y": { count: 2, rule: 'Y_DIFFERENCE' },
  "scripts/check-hotel.mts::Y_THRESHOLD::box.max.y < -0.1": { count: 1, rule: 'Y_THRESHOLD' },
  "scripts/check-hotel.mts::Y_THRESHOLD::box.max.y > 0.35": { count: 1, rule: 'Y_THRESHOLD' },
  "scripts/check-hotel.mts::Y_THRESHOLD::shot.to.y < 0.35": { count: 1, rule: 'Y_THRESHOLD' },
  "scripts/check-npc-perch.mts::Y_DIFFERENCE::part.position.y - part.scale.y": { count: 1, rule: 'Y_DIFFERENCE' },
  "scripts/check-pet-slide.mts::HARD_UP::new Vector3(0, -1, 0)": { count: 1, rule: 'HARD_UP' },
  "scripts/check-pet-slide.mts::HARD_UP::new Vector3(0, 1, 0)": { count: 1, rule: 'HARD_UP' },
  "scripts/check-pet-slide.mts::HARD_UP::up.set(0, 1, 0)": { count: 1, rule: 'HARD_UP' },
  "scripts/check-pet-slide.mts::Y_OVER_GROUND::cameraWorld.y - groundY": { count: 1, rule: 'Y_OVER_GROUND' },
  "scripts/check-rail-race.mts::AXIS_ALIGNED_BOX::barGeometry.boundingBox.min.y": { count: 1, rule: 'AXIS_ALIGNED_BOX' },
  "scripts/check-rail-race.mts::AXIS_ALIGNED_BOX::cartBox.min.y": { count: 1, rule: 'AXIS_ALIGNED_BOX' },
  "scripts/check-rail-race.mts::AXIS_ALIGNED_BOX::cheeringPose.body.min.y": { count: 2, rule: 'AXIS_ALIGNED_BOX' },
  "scripts/check-rail-race.mts::AXIS_ALIGNED_BOX::duckPumpPose.body.min.y": { count: 2, rule: 'AXIS_ALIGNED_BOX' },
  "scripts/check-rail-race.mts::AXIS_ALIGNED_BOX::duckedPose.body.min.y": { count: 5, rule: 'AXIS_ALIGNED_BOX' },
  "scripts/check-rail-race.mts::AXIS_ALIGNED_BOX::hopperBox.max.y": { count: 1, rule: 'AXIS_ALIGNED_BOX' },
  "scripts/check-rail-race.mts::AXIS_ALIGNED_BOX::new Box3().setFromObject(head).max.y": { count: 1, rule: 'AXIS_ALIGNED_BOX' },
  "scripts/check-rail-race.mts::AXIS_ALIGNED_BOX::visibleBox(player.model.root).min.y": { count: 3, rule: 'AXIS_ALIGNED_BOX' },
  "scripts/check-rail-race.mts::Y_DIFFERENCE::new Box3().setFromObject(head).max.y - railPoint.y": { count: 1, rule: 'Y_DIFFERENCE' },
  "scripts/check-rail-race.mts::Y_DIFFERENCE::point.y - trainPoint.y": { count: 1, rule: 'Y_DIFFERENCE' },
  "scripts/check-rail-race.mts::Y_OVER_GROUND::point.y - ground": { count: 1, rule: 'Y_OVER_GROUND' },
  "scripts/check-rail-race.mts::Y_OVER_GROUND::point.y - terrainHeight(point.x, point.z)": { count: 1, rule: 'Y_OVER_GROUND' },
  "scripts/check-slide-rider.mts::AXIS_ALIGNED_BOX::box.max.y": { count: 1, rule: 'AXIS_ALIGNED_BOX' },
  "scripts/check-slide-rider.mts::AXIS_ALIGNED_BOX::box.min.y": { count: 1, rule: 'AXIS_ALIGNED_BOX' },
  "scripts/check-stall-shape.mts::AXIS_ALIGNED_BOX::bounds.max.y": { count: 2, rule: 'AXIS_ALIGNED_BOX' },
  "scripts/check-stall-shape.mts::AXIS_ALIGNED_BOX::bounds.min.y": { count: 2, rule: 'AXIS_ALIGNED_BOX' },
  "scripts/check-stall-shape.mts::AXIS_ALIGNED_BOX::box.max.y": { count: 3, rule: 'AXIS_ALIGNED_BOX' },
  "scripts/check-stall-shape.mts::AXIS_ALIGNED_BOX::part.min.y": { count: 1, rule: 'AXIS_ALIGNED_BOX' },
  "scripts/check-statue-occlusion.mts::Y_DIFFERENCE::player.y - cam.y": { count: 1, rule: 'Y_DIFFERENCE' },
  "scripts/check-swept-bus.mts::AXIS_ALIGNED_BOX::busBox.max.y": { count: 3, rule: 'AXIS_ALIGNED_BOX' },
  "scripts/check-swept-bus.mts::AXIS_ALIGNED_BOX::busBox.min.y": { count: 3, rule: 'AXIS_ALIGNED_BOX' },
  "scripts/check-swept-bus.mts::Y_OVER_GROUND::sample.y - terrainHeight(sample.x, sample.z)": { count: 1, rule: 'Y_OVER_GROUND' },
  "scripts/diag-clearance.mts::HARD_UP::new Vector3(0, 1, 0)": { count: 1, rule: 'HARD_UP' },
  "scripts/diag-clearance.mts::VERTICAL_RAY::raycaster.set(rayOrigin, worldUp)": { count: 1, rule: 'VERTICAL_RAY' },
  "scripts/diag-clearance.mts::Y_DIFFERENCE::hitA.point.y - routePoint.y": { count: 1, rule: 'Y_DIFFERENCE' },
  "scripts/gate-arch-measure.mts::AXIS_ALIGNED_BOX::box.max.y": { count: 1, rule: 'AXIS_ALIGNED_BOX' },
  "scripts/gate-arch-measure.mts::AXIS_ALIGNED_BOX::box.min.y": { count: 1, rule: 'AXIS_ALIGNED_BOX' },
  "scripts/gate-arch-measure.mts::HARD_UP::new Vector3(0, 1, 0)": { count: 1, rule: 'HARD_UP' },
  "scripts/gate-arch-measure.mts::VERTICAL_RAY::raycaster.set(from, up)": { count: 1, rule: 'VERTICAL_RAY' },
  "scripts/measure-slide-camera.mts::HARD_UP::new Vector3(0, -1, 0)": { count: 1, rule: 'HARD_UP' },
  "scripts/measure-slide-camera.mts::HARD_UP::new Vector3(0, 1, 0)": { count: 1, rule: 'HARD_UP' },
  "scripts/measure-slide-route.mts::Y_DIFFERENCE::b.y - a.y": { count: 2, rule: 'Y_DIFFERENCE' },
  "scripts/measure-torus-480.mts::AXIS_ALIGNED_BOX::box.max.y": { count: 1, rule: 'AXIS_ALIGNED_BOX' },
  "scripts/measure-torus-480.mts::AXIS_ALIGNED_BOX::box.min.y": { count: 1, rule: 'AXIS_ALIGNED_BOX' },
  "scripts/measure-torus-480.mts::Y_THRESHOLD::maxDim < 1.5": { count: 1, rule: 'Y_THRESHOLD' },
  "scripts/playerSim.mts::Y_OVER_GROUND::this.position.y - groundY": { count: 2, rule: 'Y_OVER_GROUND' },
  "scripts/probe-lane-trees.mts::AXIS_ALIGNED_BOX::box.setFromObject(n).max.y": { count: 1, rule: 'AXIS_ALIGNED_BOX' },
  "scripts/probe-sightline.mts::AXIS_ALIGNED_BOX::bounds.max.y": { count: 2, rule: 'AXIS_ALIGNED_BOX' },
  "scripts/probe-slot-search.mts::Y_OVER_GROUND::top.y - ground": { count: 1, rule: 'Y_OVER_GROUND' },
  "scripts/tmp-arrival-frames.mts::Y_DIFFERENCE::c.position.y - p.y": { count: 1, rule: 'Y_DIFFERENCE' },
  "scripts/tmp-projection-audit.mts::Y_DIFFERENCE::c.position.y - p.y": { count: 1, rule: 'Y_DIFFERENCE' },
  "scripts/trace-ride-camera.mts::Y_DIFFERENCE::this.at.y - this.origin.y": { count: 1, rule: 'Y_DIFFERENCE' },
  "scripts/trace-ride-camera.mts::Y_DIFFERENCE::yaw - previousYaw": { count: 1, rule: 'Y_DIFFERENCE' },
  "src/art/effects/rainbowRing.ts::FLAT_DISC::mesh.rotation.x = -Math.PI / 2": { count: 1, rule: 'FLAT_DISC' },
  "src/art/effects/waterSplash.ts::FLAT_DISC::mesh.rotation.x = -Math.PI / 2": { count: 1, rule: 'FLAT_DISC' },
  "src/art/models/balloons.ts::FLAT_DISC::beakTop.rotation.x = Math.PI / 2": { count: 1, rule: 'FLAT_DISC' },
  "src/art/models/balloons.ts::FLAT_DISC::tie.rotation.x = Math.PI / 2": { count: 1, rule: 'FLAT_DISC' },
  "src/art/models/biscuit.ts::FLAT_DISC::collar.rotation.x = Math.PI / 2": { count: 1, rule: 'FLAT_DISC' },
  "src/art/models/biscuit.ts::FLAT_DISC::hem.rotation.x = Math.PI / 2": { count: 1, rule: 'FLAT_DISC' },
  "src/art/models/castleAssets.ts::AXIS_ALIGNED_BOX::box.max.y": { count: 2, rule: 'AXIS_ALIGNED_BOX' },
  "src/art/models/gateArch.ts::AXIS_ALIGNED_BOX::MEDALLION.max.y": { count: 1, rule: 'AXIS_ALIGNED_BOX' },
  "src/art/models/gateArch.ts::AXIS_ALIGNED_BOX::MEDALLION.min.y": { count: 1, rule: 'AXIS_ALIGNED_BOX' },
  "src/art/models/gateArch.ts::AXIS_ALIGNED_BOX::PIERS.max.y": { count: 2, rule: 'AXIS_ALIGNED_BOX' },
  "src/art/models/gateArch.ts::AXIS_ALIGNED_BOX::SIGN.max.y": { count: 1, rule: 'AXIS_ALIGNED_BOX' },
  "src/art/models/gateArch.ts::AXIS_ALIGNED_BOX::SIGN.min.y": { count: 2, rule: 'AXIS_ALIGNED_BOX' },
  "src/art/models/gateArch.ts::Y_DIFFERENCE::SIGN.max.y - SIGN.min.y": { count: 1, rule: 'Y_DIFFERENCE' },
  "src/art/models/hair.ts::FLAT_DISC::new TorusGeometry(radius, tube, 8, 18).rotateX(Math.PI / 2)": { count: 1, rule: 'FLAT_DISC' },
  "src/art/models/hats.ts::FLAT_DISC::mesh.rotation.x = Math.PI / 2": { count: 1, rule: 'FLAT_DISC' },
  "src/art/models/kid.ts::FLAT_DISC::mesh.rotation.x = Math.PI / 2": { count: 2, rule: 'FLAT_DISC' },
  "src/art/models/ponytail.ts::HARD_UP::new Vector3(0, 1, 0)": { count: 1, rule: 'HARD_UP' },
  "src/art/models/ponytail.ts::Y_DIFFERENCE::point.y - prev.y": { count: 1, rule: 'Y_DIFFERENCE' },
  "src/art/models/ponytail.ts::Y_DIFFERENCE::point.y - scratchOrigin.y": { count: 1, rule: 'Y_DIFFERENCE' },
  "src/art/models/shoes.ts::FLAT_DISC::new TorusGeometry(0.13, 0.034, 8, 24).rotateX(Math.PI / 2)": { count: 1, rule: 'FLAT_DISC' },
  "src/art/models/shoes.ts::HARD_UP::new Vector3(0, 1, 0)": { count: 1, rule: 'HARD_UP' },
  "src/art/models/tapMarker.ts::FLAT_DISC::this.disc.rotation.x = -Math.PI / 2": { count: 1, rule: 'FLAT_DISC' },
  "src/art/models/tapMarker.ts::FLAT_DISC::this.ring.rotation.x = -Math.PI / 2": { count: 1, rule: 'FLAT_DISC' },
  "src/art/style/shapes.ts::Y_DIFFERENCE::to.y - from.y": { count: 1, rule: 'Y_DIFFERENCE' },
  "src/core/IsoCamera.ts::HARD_UP::new Vector3(0, 1, 0)": { count: 1, rule: 'HARD_UP' },
  "src/core/IsoCamera.ts::Y_DIFFERENCE::eye.y - this.offset.y": { count: 1, rule: 'Y_DIFFERENCE' },
  "src/core/deviceOrientationLook.ts::HARD_UP::up.set(0, 1, 0)": { count: 1, rule: 'HARD_UP' },
  "src/core/input/PointerControls.ts::Y_DIFFERENCE::first.y - second.y": { count: 1, rule: 'Y_DIFFERENCE' },
  "src/entities/Player.ts::Y_OVER_GROUND::this.position.y - groundY": { count: 4, rule: 'Y_OVER_GROUND' },
  "src/entities/TapNavigator.ts::Y_DIFFERENCE::this.player.position.y - this.target.y": { count: 1, rule: 'Y_DIFFERENCE' },
  "src/entities/WornKeychain.ts::Y_DIFFERENCE::this.worldPos.y - this.previousPos.y": { count: 1, rule: 'Y_DIFFERENCE' },
  "src/entities/balloonString.ts::HARD_UP::new Vector3(0, 1, 0)": { count: 1, rule: 'HARD_UP' },
  "src/entities/balloonString.ts::Y_DIFFERENCE::point.y - prev.y": { count: 1, rule: 'Y_DIFFERENCE' },
  "src/entities/npc/NpcCharacter.ts::Y_OVER_GROUND::this.position.y - groundY": { count: 2, rule: 'Y_OVER_GROUND' },
  "src/entities/npc/petBlob.ts::FLAT_DISC::collar.rotation.x = Math.PI / 2": { count: 1, rule: 'FLAT_DISC' },
  "src/entities/parade/BackpackPeek.ts::Y_DIFFERENCE::top - bottom": { count: 1, rule: 'Y_DIFFERENCE' },
  "src/entities/parade/ParadeMember.ts::AXIS_ALIGNED_BOX::box.min.y": { count: 2, rule: 'AXIS_ALIGNED_BOX' },
  "src/entities/parade/ParadeMember.ts::Y_DIFFERENCE::target.y - this.position.y": { count: 1, rule: 'Y_DIFFERENCE' },
  "src/entities/parade/trail.ts::Y_DIFFERENCE::b.y - a.y": { count: 1, rule: 'Y_DIFFERENCE' },
  "src/minigames/dodgems/Dodgems.ts::FLAT_DISC::this.youMarker.rotation.x = -Math.PI / 2": { count: 1, rule: 'FLAT_DISC' },
  "src/minigames/dodgems/arena.ts::FLAT_DISC::floor.rotation.x = -Math.PI / 2": { count: 1, rule: 'FLAT_DISC' },
  "src/minigames/dodgems/arena.ts::FLAT_DISC::kerb.rotation.x = Math.PI / 2": { count: 1, rule: 'FLAT_DISC' },
  "src/minigames/dodgems/arena.ts::FLAT_DISC::rail.rotation.x = Math.PI / 2": { count: 1, rule: 'FLAT_DISC' },
  "src/minigames/dodgems/arena.ts::FLAT_DISC::ring.rotation.x = -Math.PI / 2": { count: 1, rule: 'FLAT_DISC' },
  "src/minigames/dodgems/arena.ts::FLAT_DISC::surround.rotation.x = -Math.PI / 2": { count: 1, rule: 'FLAT_DISC' },
  "src/minigames/dodgems/arena.ts::FLAT_DISC::wire.rotation.x = Math.PI / 2": { count: 1, rule: 'FLAT_DISC' },
  "src/minigames/dodgems/car.ts::FLAT_DISC::bumper.rotation.x = Math.PI / 2": { count: 1, rule: 'FLAT_DISC' },
  "src/minigames/dodgems/plot.ts::FLAT_DISC::fleck.rotation.x = -Math.PI / 2": { count: 1, rule: 'FLAT_DISC' },
  "src/minigames/dodgems/plot.ts::FLAT_DISC::floor.rotation.x = -Math.PI / 2": { count: 1, rule: 'FLAT_DISC' },
  "src/minigames/dodgems/plot.ts::FLAT_DISC::railRing.rotation.x = Math.PI / 2": { count: 1, rule: 'FLAT_DISC' },
  "src/minigames/dodgems/plot.ts::FLAT_DISC::ring.rotation.x = -Math.PI / 2": { count: 1, rule: 'FLAT_DISC' },
  "src/minigames/dodgems/plot.ts::FLAT_DISC::wire.rotation.x = Math.PI / 2": { count: 1, rule: 'FLAT_DISC' },
  "src/minigames/dodgems/tree.ts::FLAT_DISC::beak.rotation.x = Math.PI / 2": { count: 1, rule: 'FLAT_DISC' },
  "src/minigames/dodgems/tree.ts::Y_THRESHOLD::apple.y < 0.26": { count: 1, rule: 'Y_THRESHOLD' },
  "src/minigames/dodgems/tree.ts::Y_THRESHOLD::apple.y < 1.5": { count: 1, rule: 'Y_THRESHOLD' },
  "src/minigames/dodgems/tree.ts::Y_THRESHOLD::apple.y > 0.1": { count: 1, rule: 'Y_THRESHOLD' },
  "src/minigames/dodgems/tree.ts::Y_THRESHOLD::leaf.y < 0.02": { count: 1, rule: 'Y_THRESHOLD' },
  "src/minigames/ferrisWheel/friends.ts::FLAT_DISC::domeRing.rotation.x = Math.PI / 2": { count: 1, rule: 'FLAT_DISC' },
  "src/minigames/ferrisWheel/gondola.ts::FLAT_DISC::hub.rotation.x = Math.PI / 2": { count: 1, rule: 'FLAT_DISC' },
  "src/minigames/ferrisWheel/gondola.ts::FLAT_DISC::rug.rotation.x = -Math.PI / 2": { count: 1, rule: 'FLAT_DISC' },
  "src/minigames/ferrisWheel/gondola.ts::FLAT_DISC::skylightRing.rotation.x = Math.PI / 2": { count: 1, rule: 'FLAT_DISC' },
  "src/minigames/ferrisWheel/space.ts::FLAT_DISC::blob.rotateX(Math.PI / 2)": { count: 1, rule: 'FLAT_DISC' },
  "src/minigames/ferrisWheel/space.ts::FLAT_DISC::crater.rotateX(Math.PI / 2)": { count: 1, rule: 'FLAT_DISC' },
  "src/minigames/ferrisWheel/space.ts::FLAT_DISC::spot.rotateX(Math.PI / 2)": { count: 1, rule: 'FLAT_DISC' },
  "src/minigames/ferrisWheel/wheelProp.ts::FLAT_DISC::axle.rotation.x = Math.PI / 2": { count: 1, rule: 'FLAT_DISC' },
  "src/minigames/ferrisWheel/wheelProp.ts::FLAT_DISC::hub.rotation.x = Math.PI / 2": { count: 1, rule: 'FLAT_DISC' },
  "src/minigames/ferrisWheel/wheelProp.ts::HARD_UP::new Vector3(0, 1, 0)": { count: 1, rule: 'HARD_UP' },
  "src/minigames/spookyHouse/candyShower.ts::AXIS_ALIGNED_BOX::box.min.y": { count: 1, rule: 'AXIS_ALIGNED_BOX' },
  "src/minigames/spookyHouse/face.ts::FLAT_DISC::pivot.rotation.x = Math.PI / 2": { count: 1, rule: 'FLAT_DISC' },
  "src/minigames/spookyHouse/room.ts::FLAT_DISC::rib.rotation.x = Math.PI / 2": { count: 1, rule: 'FLAT_DISC' },
  "src/minigames/spookyHouse/room.ts::FLAT_DISC::rugRing.rotation.x = Math.PI / 2": { count: 1, rule: 'FLAT_DISC' },
  "src/minigames/stallProp.ts::FLAT_DISC::ring.rotation.x = Math.PI / 2": { count: 1, rule: 'FLAT_DISC' },
  "src/minigames/waterFight/WaterFight.ts::FLAT_DISC::this.aimRing.rotation.x = -Math.PI / 2": { count: 1, rule: 'FLAT_DISC' },
  "src/minigames/waterFight/child.ts::FLAT_DISC::band.rotation.x = Math.PI / 2": { count: 1, rule: 'FLAT_DISC' },
  "src/minigames/waterFight/child.ts::FLAT_DISC::barrel.rotation.x = Math.PI / 2": { count: 1, rule: 'FLAT_DISC' },
  "src/minigames/waterFight/child.ts::FLAT_DISC::nozzle.rotation.x = Math.PI / 2": { count: 1, rule: 'FLAT_DISC' },
  "src/minigames/waterFight/child.ts::FLAT_DISC::pump.rotation.x = Math.PI / 2": { count: 1, rule: 'FLAT_DISC' },
  "src/minigames/waterFight/child.ts::FLAT_DISC::tank.rotation.x = Math.PI / 2": { count: 1, rule: 'FLAT_DISC' },
  "src/minigames/waterFight/child.ts::FLAT_DISC::tankWater.rotation.x = Math.PI / 2": { count: 1, rule: 'FLAT_DISC' },
  "src/minigames/waterFight/garden.ts::FLAT_DISC::deep.rotation.x = -Math.PI / 2": { count: 1, rule: 'FLAT_DISC' },
  "src/minigames/waterFight/garden.ts::FLAT_DISC::field.rotation.x = -Math.PI / 2": { count: 1, rule: 'FLAT_DISC' },
  "src/minigames/waterFight/garden.ts::FLAT_DISC::rim.rotation.x = Math.PI / 2": { count: 1, rule: 'FLAT_DISC' },
  "src/minigames/waterFight/garden.ts::FLAT_DISC::water.rotation.x = -Math.PI / 2": { count: 1, rule: 'FLAT_DISC' },
  "src/minigames/waterFight/plot.ts::FLAT_DISC::barrel.rotation.x = Math.PI / 2": { count: 1, rule: 'FLAT_DISC' },
  "src/minigames/waterFight/plot.ts::FLAT_DISC::rim.rotation.x = Math.PI / 2": { count: 1, rule: 'FLAT_DISC' },
  "src/minigames/waterFight/plot.ts::FLAT_DISC::surface.rotation.x = -Math.PI / 2": { count: 1, rule: 'FLAT_DISC' },
  "src/minigames/waterFight/plot.ts::FLAT_DISC::tank.rotation.x = Math.PI / 2": { count: 1, rule: 'FLAT_DISC' },
  "src/ui/ParkMap.ts::Y_DIFFERENCE::b.y - a.y": { count: 1, rule: 'Y_DIFFERENCE' },
  "src/ui/ParkMap.ts::Y_DIFFERENCE::point.y - previous.y": { count: 1, rule: 'Y_DIFFERENCE' },
  "src/world/AnchorPlots.ts::FLAT_DISC::hoop.rotation.x = Math.PI / 2": { count: 1, rule: 'FLAT_DISC' },
  "src/world/DayNight.ts::HARD_UP::new Vector3(0, -1, 0)": { count: 1, rule: 'HARD_UP' },
  "src/world/DayNight.ts::HARD_UP::new Vector3(0, 1, 0)": { count: 2, rule: 'HARD_UP' },
  "src/world/FacePaintStall.ts::FLAT_DISC::mirrorGlass.rotation.x = Math.PI / 2": { count: 1, rule: 'FLAT_DISC' },
  "src/world/FacePaintStall.ts::FLAT_DISC::mirrorShine.rotation.x = Math.PI / 2": { count: 1, rule: 'FLAT_DISC' },
  "src/world/FacePaintStall.ts::FLAT_DISC::ring.rotation.x = Math.PI / 2": { count: 1, rule: 'FLAT_DISC' },
  "src/world/FoliageFade.ts::Y_DIFFERENCE::player.y - camera.y": { count: 1, rule: 'Y_DIFFERENCE' },
  "src/world/Fountain.ts::FLAT_DISC::rim.rotation.x = Math.PI / 2": { count: 1, rule: 'FLAT_DISC' },
  "src/world/Fountain.ts::FLAT_DISC::this.waterGeometry.rotateX(-Math.PI / 2)": { count: 1, rule: 'FLAT_DISC' },
  "src/world/Fountain.ts::HARD_UP::new Vector3(0, 1, 0)": { count: 1, rule: 'HARD_UP' },
  "src/world/Highlights.ts::FLAT_DISC::this.ring.rotation.x = -Math.PI / 2": { count: 1, rule: 'FLAT_DISC' },
  "src/world/LampPosts.ts::FLAT_DISC::glowGeometry.rotateX(-Math.PI / 2)": { count: 1, rule: 'FLAT_DISC' },
  "src/world/NavGrid.ts::Y_DIFFERENCE::b.y - a.y": { count: 1, rule: 'Y_DIFFERENCE' },
  "src/world/Selection.ts::Y_DIFFERENCE::position.y - zone.y": { count: 2, rule: 'Y_DIFFERENCE' },
  "src/world/Sky.ts::HARD_UP::VIEW_UP.set(0, 1, 0)": { count: 1, rule: 'HARD_UP' },
  "src/world/Sky.ts::HARD_UP::new Vector3(0, 1, 0)": { count: 2, rule: 'HARD_UP' },
  "src/world/building/BallPit.ts::FLAT_DISC::rim.rotation.x = Math.PI / 2": { count: 1, rule: 'FLAT_DISC' },
  "src/world/building/Building.ts::Y_OVER_GROUND::player.position.y - this.trampoline.surfaceY": { count: 1, rule: 'Y_OVER_GROUND' },
  "src/world/building/FloorArrows.ts::FLAT_DISC::mesh.rotation.x = -Math.PI / 2": { count: 1, rule: 'FLAT_DISC' },
  "src/world/building/GrownUp.ts::FLAT_DISC::scarf.rotation.x = Math.PI / 2": { count: 1, rule: 'FLAT_DISC' },
  "src/world/building/Shell.ts::FLAT_DISC::disc.rotation.x = -Math.PI / 2": { count: 1, rule: 'FLAT_DISC' },
  "src/world/building/Shell.ts::HARD_UP::new Vector3(0, 1, 0)": { count: 1, rule: 'HARD_UP' },
  "src/world/building/SlideRide.ts::HARD_UP::new Vector3(0, 1, 0)": { count: 1, rule: 'HARD_UP' },
  "src/world/building/Toilets.ts::FLAT_DISC::rim.rotation.x = Math.PI / 2": { count: 1, rule: 'FLAT_DISC' },
  "src/world/building/Toilets.ts::FLAT_DISC::spout.rotation.x = Math.PI / 2": { count: 1, rule: 'FLAT_DISC' },
  "src/world/building/Trampoline.ts::FLAT_DISC::rim.rotation.x = Math.PI / 2": { count: 1, rule: 'FLAT_DISC' },
  "src/world/building/castleDecor.ts::FLAT_DISC::rug.rotation.x = -Math.PI / 2": { count: 1, rule: 'FLAT_DISC' },
  "src/world/building/castleDecor.ts::FLAT_DISC::top.rotateX(Math.PI / 2)": { count: 1, rule: 'FLAT_DISC' },
  "src/world/building/castleDecor.ts::HARD_UP::new Vector3(0, 1, 0)": { count: 3, rule: 'HARD_UP' },
  "src/world/building/castleFabric.ts::HARD_UP::new Vector3(0, 1, 0)": { count: 1, rule: 'HARD_UP' },
  "src/world/building/castleLighting.ts::HARD_UP::new Vector3(0, 1, 0)": { count: 2, rule: 'HARD_UP' },
  "src/world/building/castleMasonry.ts::HARD_UP::new Vector3(0, 1, 0)": { count: 1, rule: 'HARD_UP' },
  "src/world/building/dressing.ts::HARD_UP::new Vector3(0, 1, 0)": { count: 1, rule: 'HARD_UP' },
  "src/world/building/parts.ts::FLAT_DISC::geometry.rotateX(-Math.PI / 2)": { count: 1, rule: 'FLAT_DISC' },
  "src/world/building/roofClouds.ts::HARD_UP::new Vector3(0, 1, 0)": { count: 1, rule: 'HARD_UP' },
  "src/world/building/roofMeadow.ts::FLAT_DISC::mouthGeometry.rotateX(-Math.PI / 2)": { count: 1, rule: 'FLAT_DISC' },
  "src/world/building/roofMeadow.ts::FLAT_DISC::turfGeometry.rotateX(-Math.PI / 2)": { count: 1, rule: 'FLAT_DISC' },
  "src/world/building/roofMeadow.ts::HARD_UP::new Vector3(0, 1, 0)": { count: 1, rule: 'HARD_UP' },
  "src/world/building/shops/fitouts.ts::FLAT_DISC::basketRim.rotation.x = Math.PI / 2": { count: 1, rule: 'FLAT_DISC' },
  "src/world/building/shops/fitouts.ts::FLAT_DISC::rim.rotation.x = Math.PI / 2": { count: 1, rule: 'FLAT_DISC' },
  "src/world/building/shops/stallShape.ts::HARD_UP::new Vector3(0, 1, 0)": { count: 2, rule: 'HARD_UP' },
  "src/world/coaster/Coaster.ts::HARD_UP::new Vector3(0, 1, 0)": { count: 1, rule: 'HARD_UP' },
  "src/world/coaster/clearance.ts::AXIS_ALIGNED_BOX::box.max.y": { count: 1, rule: 'AXIS_ALIGNED_BOX' },
  "src/world/coaster/pylons.ts::Y_OVER_GROUND::point.y - ground": { count: 1, rule: 'Y_OVER_GROUND' },
  "src/world/coaster/route.ts::Y_DIFFERENCE::point.y - train.y": { count: 2, rule: 'Y_DIFFERENCE' },
  "src/world/coaster/route.ts::Y_OVER_GROUND::point.y - terrainHeight(point.x, point.z)": { count: 2, rule: 'Y_OVER_GROUND' },
  "src/world/coaster/route.ts::Y_OVER_GROUND::probe.y - terrainHeight(probe.x, probe.z)": { count: 2, rule: 'Y_OVER_GROUND' },
  "src/world/entrance/ArrivalSequence.ts::Y_DIFFERENCE::focus.y - eye.y": { count: 1, rule: 'Y_DIFFERENCE' },
  "src/world/entrance/BusJourney.ts::AXIS_ALIGNED_BOX::new Box3().setFromObject(kid.root).max.y": { count: 1, rule: 'AXIS_ALIGNED_BOX' },
  "src/world/entrance/BusJourney.ts::FLAT_DISC::geometry.rotateX(-Math.PI / 2)": { count: 1, rule: 'FLAT_DISC' },
  "src/world/entrance/BusJourney.ts::FLAT_DISC::roadGeometry.rotateX(-Math.PI / 2)": { count: 1, rule: 'FLAT_DISC' },
  "src/world/entrance/BusJourney.ts::HARD_UP::new Vector3(0, 1, 0)": { count: 1, rule: 'HARD_UP' },
  "src/world/entrance/Entrance.ts::FLAT_DISC::pawB.rotation.x = -Math.PI / 2": { count: 1, rule: 'FLAT_DISC' },
  "src/world/ferrisWheel/clouds.ts::HARD_UP::new Vector3(0, 1, 0)": { count: 1, rule: 'HARD_UP' },
  "src/world/hotel/Hotel.ts::AXIS_ALIGNED_BOX::box.min.y": { count: 1, rule: 'AXIS_ALIGNED_BOX' },
  "src/world/hotel/Hotel.ts::FLAT_DISC::plate.rotation.x = -Math.PI / 2": { count: 1, rule: 'FLAT_DISC' },
  "src/world/hotel/Hotel.ts::Y_THRESHOLD::player.position.y < -2": { count: 1, rule: 'Y_THRESHOLD' },
  "src/world/hotel/dressing.ts::FLAT_DISC::arch.rotation.x = Math.PI / 2": { count: 1, rule: 'FLAT_DISC' },
  "src/world/hotel/dressing.ts::FLAT_DISC::rays.rotation.x = -Math.PI / 2": { count: 1, rule: 'FLAT_DISC' },
  "src/world/hotel/dressing.ts::FLAT_DISC::ring.rotation.x = -Math.PI / 2": { count: 1, rule: 'FLAT_DISC' },
  "src/world/hotel/dressing.ts::FLAT_DISC::ring.rotation.x = Math.PI / 2": { count: 1, rule: 'FLAT_DISC' },
  "src/world/hotel/dressing.ts::FLAT_DISC::shape.rotation.x = Math.PI / 2": { count: 1, rule: 'FLAT_DISC' },
  "src/world/railRace/camera.ts::HARD_UP::new Vector3(0, 1, 0)": { count: 1, rule: 'HARD_UP' },
  "src/world/railRace/cart.ts::HARD_UP::new Vector3(0, 1, 0)": { count: 1, rule: 'HARD_UP' },
  "src/world/railRace/track.ts::AXIS_ALIGNED_BOX::postBox.max.y": { count: 1, rule: 'AXIS_ALIGNED_BOX' },
  "src/world/railRace/track.ts::AXIS_ALIGNED_BOX::postBox.min.y": { count: 1, rule: 'AXIS_ALIGNED_BOX' },
  "src/world/railRace/track.ts::HARD_UP::new Vector3(0, 1, 0)": { count: 1, rule: 'HARD_UP' },
  "src/world/railRace/track.ts::Y_DIFFERENCE::postBox.max.y - postBox.min.y": { count: 1, rule: 'Y_DIFFERENCE' },
  "src/world/railRace/track.ts::Y_DIFFERENCE::top.y - foot.y": { count: 1, rule: 'Y_DIFFERENCE' },
  "src/world/railRace/track.ts::Y_OVER_GROUND::trunkTop.y - ground": { count: 1, rule: 'Y_OVER_GROUND' },
  "src/world/slide/cameras.ts::HARD_UP::new Vector3(0, 1, 0)": { count: 1, rule: 'HARD_UP' },
  "src/world/slide/chaseEye.ts::Y_OVER_GROUND::eye.y - terrainHeight(eye.x, eye.z)": { count: 1, rule: 'Y_OVER_GROUND' },
  "src/world/slide/petRiders.ts::HARD_UP::new Vector3(0, 1, 0)": { count: 1, rule: 'HARD_UP' },
  "src/world/slide/solve.ts::Y_DIFFERENCE::b.y - a.y": { count: 1, rule: 'Y_DIFFERENCE' },
  "src/world/slide/solve.ts::Y_DIFFERENCE::near.y - point.y": { count: 1, rule: 'Y_DIFFERENCE' },
  "src/world/slide/supports.ts::Y_OVER_GROUND::point.y - ground": { count: 1, rule: 'Y_OVER_GROUND' },
  "src/world/train/bridgeStonework.ts::HARD_UP::new Vector3(0, 1, 0)": { count: 1, rule: 'HARD_UP' },
  "src/world/train/bridges.ts::HARD_UP::new Vector3(0, 1, 0)": { count: 1, rule: 'HARD_UP' },
  "src/world/train/plan.ts::Y_OVER_GROUND::probe.y - terrainHeight(probe.x, probe.z)": { count: 1, rule: 'Y_OVER_GROUND' },
  "src/world/train/route.ts::Y_OVER_GROUND::probe.y - terrainHeight(probe.x, probe.z)": { count: 1, rule: 'Y_OVER_GROUND' },
  "src/world/train/trainModel.ts::FLAT_DISC::band.rotation.x = Math.PI / 2": { count: 1, rule: 'FLAT_DISC' },
  "src/world/train/trainModel.ts::FLAT_DISC::boiler.rotation.x = Math.PI / 2": { count: 1, rule: 'FLAT_DISC' },
  "test/coplanar/sweepControls.test.ts::FLAT_DISC::down.rotation.x = Math.PI / 2": { count: 1, rule: 'FLAT_DISC' },
  "test/coplanar/sweepControls.test.ts::FLAT_DISC::floor.rotation.x = -Math.PI / 2": { count: 1, rule: 'FLAT_DISC' },
  "test/coplanar/sweepControls.test.ts::FLAT_DISC::mesh.rotation.x = -Math.PI / 2": { count: 1, rule: 'FLAT_DISC' },
  "test/coplanar/sweepControls.test.ts::FLAT_DISC::tile.rotation.x = Math.PI / 2": { count: 1, rule: 'FLAT_DISC' },
  "test/geo/core.test.ts::HARD_UP::new Vector3(0, 1, 0)": { count: 3, rule: 'HARD_UP' },
  "test/geo/core.test.ts::Y_OVER_GROUND::world.y - terrainHeight(world.x, world.z)": { count: 1, rule: 'Y_OVER_GROUND' },
  "test/procgen/invariants.ts::AXIS_ALIGNED_BOX::new Box3().setFromObject(deckMesh).min.y": { count: 2, rule: 'AXIS_ALIGNED_BOX' },
  "test/procgen/invariants.ts::HARD_UP::new Vector3(0, 1, 0)": { count: 2, rule: 'HARD_UP' },
  "test/procgen/invariants.ts::VERTICAL_RAY::raycaster.set(from, up)": { count: 1, rule: 'VERTICAL_RAY' },
  "test/procgen/invariants.ts::VERTICAL_RAY::raycaster.set(rayOrigin, up)": { count: 1, rule: 'VERTICAL_RAY' },
  "test/procgen/invariants.ts::Y_DIFFERENCE::first.point.y - routePoint.y": { count: 1, rule: 'Y_DIFFERENCE' },
  "test/procgen/invariants.ts::Y_DIFFERENCE::rail.y - under.y": { count: 1, rule: 'Y_DIFFERENCE' },
  "test/procgen/invariants.ts::Y_OVER_GROUND::hit.point.y - ground": { count: 1, rule: 'Y_OVER_GROUND' },
  "test/procgen/invariants.ts::Y_OVER_GROUND::soffit - groundY": { count: 1, rule: 'Y_OVER_GROUND' },
  "test/procgen/parkFacts.ts::AXIS_ALIGNED_BOX::bounds.max.y": { count: 1, rule: 'AXIS_ALIGNED_BOX' },
  "test/procgen/parkFacts.ts::AXIS_ALIGNED_BOX::box.max.y": { count: 5, rule: 'AXIS_ALIGNED_BOX' },
  "test/procgen/parkFacts.ts::AXIS_ALIGNED_BOX::box.min.y": { count: 1, rule: 'AXIS_ALIGNED_BOX' },
  "test/procgen/parkFacts.ts::AXIS_ALIGNED_BOX::busBox.setFromObject(node).max.y": { count: 1, rule: 'AXIS_ALIGNED_BOX' },
  "test/procgen/parkFacts.ts::AXIS_ALIGNED_BOX::new Box3().setFromObject(child).min.y": { count: 1, rule: 'AXIS_ALIGNED_BOX' },
  "test/procgen/parkFacts.ts::AXIS_ALIGNED_BOX::shell.max.y": { count: 1, rule: 'AXIS_ALIGNED_BOX' },
  "test/procgen/parkFacts.ts::HARD_UP::new Vector3(0, 1, 0)": { count: 1, rule: 'HARD_UP' },
  "test/procgen/parkFacts.ts::Y_DIFFERENCE::box.max.y - shell.max.y": { count: 1, rule: 'Y_DIFFERENCE' },
  "test/procgen/parkFacts.ts::Y_OVER_GROUND::point.y - terrainHeight(point.x, point.z)": { count: 1, rule: 'Y_OVER_GROUND' },
};
