import './headless-dom.mjs';
import { Vector3 } from 'three';
import { writeFileSync } from 'node:fs';
import crypto from 'node:crypto';
await import('./headless-canvas.mjs');
const { Scene } = await import('three');
const { World } = await import('../src/world/World.ts');
const { Sky } = await import('../src/world/Sky.ts');
const { IsoCamera } = await import('../src/core/IsoCamera.ts');
const liveControls = { cancelWalk: () => {}, iris: (m: () => void) => m(), flash: () => {}, snapCamera: () => {} };
const scene = new Scene();
const world = new World(scene, new Sky(), liveControls as never, new IsoCamera());
scene.updateMatrixWorld(true);
const parts: string[] = [];
const v = new Vector3();
const path = (o: any): string => { const s = []; let n = o; while (n) { s.push(n.name || n.type); n = n.parent; } return s.reverse().join('/'); };
scene.traverse((o: any) => {
  v.setFromMatrixPosition(o.matrixWorld);
  parts.push(`${path(o)}\t${v.x.toExponential(17)},${v.y.toExponential(17)},${v.z.toExponential(17)}`);
});
console.log('nodes', parts.length);
console.log('sceneHash', crypto.createHash('sha256').update(parts.join('\n')).digest('hex'));
const out = process.argv[2];
if (out) writeFileSync(out, parts.join('\n') + '\n');
