/**
 * **What the cat bus was already driving through when `check:swept-bus` was written.**
 *
 * Generated by `pnpm run check:swept-bus -- --print-baseline`. Each entry is a
 * **seed number** and the count of distinct drawn trestle posts the bus's body
 * reaches on that seed. Keyed on the seed and nothing else, deliberately:
 * issue #520 is that `check:coplanar`'s baseline is keyed on mesh names, so a
 * rename silently loses the finding. A seed number cannot be renamed, and an
 * entry here for a seed that is not in `PARK_SEED_POOL` **fails the check**
 * rather than sitting quietly.
 *
 * A seed with no entry allows **zero**. Do not add an entry to make the check
 * pass — an entry means "this was already wrong when the gate was written", and
 * a new one means the road or the ride has just been made worse.
 *
 * Stage 3, step 2 drives this to empty and deletes the file. See
 * `docs/DESIGN-round-robin-generation.md`.
 */
export const SWEPT_BUS_BASELINE: Readonly<Record<number, number>> = {
  5: 27,
  11: 25,
  24: 16,
  115: 24,
  128: 21,
  131: 24,
  208: 24,
  225: 24,
  267: 26,
  274: 22,
  288: 26,
  326: 10,
  346: 24,
  428: 30,
  451: 13,
  20260728: 28,
};
